INSERT INTO sources (slug, name, url, tier, trust_score, language, country, categories, rss_feeds, scrape_interval)
VALUES
  ('sky-news',       'Sky News',                'https://news.sky.com',           'national', 0.88, 'en', 'GB', '{breaking,geopolitics,conflict}',  '{https://feeds.skynews.com/feeds/rss/world.xml}',                                        600),
  ('npr-world',      'NPR World',               'https://npr.org/sections/world',  'national', 0.91, 'en', 'US', '{geopolitics,culture,economy}',   '{https://feeds.npr.org/1004/rss.xml}',                                                   900),
  ('cbc-news',       'CBC News',                'https://cbc.ca/news',            'national', 0.90, 'en', 'CA', '{breaking,geopolitics,economy}',   '{https://www.cbc.ca/cmlink/rss-topstories}',                                             900),
  ('nhk-world',      'NHK World',               'https://www3.nhk.or.jp/nhkworld','national', 0.91, 'en', 'JP', '{geopolitics,economy,disaster}',   '{https://www3.nhk.or.jp/nhkworld/en/news/feeds/}',                                       900),
  ('euronews',       'Euronews',                'https://euronews.com',           'national', 0.85, 'en', 'FR', '{geopolitics,economy,culture}',    '{https://www.euronews.com/rss}',                                                         900),
  ('voa-news',       'Voice of America',        'https://voanews.com',            'national', 0.87, 'en', 'US', '{geopolitics,conflict,economy}',   '{https://www.voanews.com/rss?section=world-news}',                                       900),
  ('abc-australia',  'ABC Australia',           'https://abc.net.au/news',        'national', 0.88, 'en', 'AU', '{geopolitics,economy,climate}',    '{https://www.abc.net.au/news/feed/51120/rss.xml}',                                       900),
  ('trt-world',      'TRT World',               'https://trtworld.com',           'national', 0.82, 'en', 'TR', '{geopolitics,conflict,culture}',   '{https://www.trtworld.com/rss}',                                                         900),
  ('spiegel-intl',   'Der Spiegel International','https://spiegel.de/international','national',0.89,'en','DE', '{geopolitics,economy,culture}',    '{https://www.spiegel.de/international/index.rss}',                                       1200),
  ('rferl',          'Radio Free Europe/RL',    'https://rferl.org',              'national', 0.83, 'en', 'CZ', '{geopolitics,conflict,elections}',  '{https://www.rferl.org/api/zp-jqyhzpjeiq}',                                              900),
  ('dawn-pk',        'Dawn (Pakistan)',          'https://dawn.com',               'national', 0.83, 'en', 'PK', '{geopolitics,conflict,economy}',   '{https://www.dawn.com/feed}',                                                            1200),
  ('cna-world',      'Channel NewsAsia',        'https://channelnewsasia.com',    'national', 0.86, 'en', 'SG', '{geopolitics,economy,health}',     '{https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511}',   900),
  ('japan-times',    'Japan Times',             'https://japantimes.co.jp',       'national', 0.86, 'en', 'JP', '{geopolitics,economy,culture}',    '{https://www.japantimes.co.jp/feed/}',                                                   1200),
  ('gdacs',          'GDACS',                   'https://gdacs.org',              'wire',     0.97, 'en', 'XX', '{disaster}',                       '{https://www.gdacs.org/xml/rss.xml}',                                                    300),
  ('reliefweb',      'ReliefWeb / OCHA',        'https://reliefweb.int',          'wire',     0.95, 'en', 'XX', '{disaster,health,conflict}',       '{https://reliefweb.int/updates/rss.xml}',                                                600),
  ('emsc-quakes',    'EMSC Earthquakes',        'https://emsc-csem.org',          'wire',     0.99, 'en', 'XX', '{disaster}',                       '{https://www.emsc-csem.org/service/rss/rss.php}',                                        300),
  ('cdc-global',     'CDC Global Health',       'https://cdc.gov',                'wire',     0.98, 'en', 'US', '{health}',                         '{https://tools.cdc.gov/api/v2/resources/media/132608.rss}',                              1800),
  ('bellingcat',     'Bellingcat',              'https://bellingcat.com',         'national', 0.88, 'en', 'GB', '{conflict,security,geopolitics}',  '{https://www.bellingcat.com/feed/}',                                                     1800),
  ('un-news',        'UN News',                 'https://news.un.org',            'wire',     0.95, 'en', 'XX', '{geopolitics,health,disaster}',    '{https://news.un.org/feed/subscribe/en/news/all/rss.xml}',                               900),
  ('swissinfo',      'SWI swissinfo.ch',        'https://swissinfo.ch',           'national', 0.87, 'en', 'CH', '{geopolitics,economy,culture}',    '{https://www.swissinfo.ch/eng/rss/Top_News_English}',                                    1200)
ON CONFLICT (slug) DO NOTHING;
