import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 400+ feeds
 *
 * Adds 54 new high-quality global RSS sources across underrepresented verticals:
 *
 *   - Southeast Asia Depth:    Bangkok Post TH, Straits Times SG, Rappler PH,
 *                              VnExpress International VN, Nikkei Asia (pan-ASEAN),
 *                              Phnom Penh Post KH, Myanmar Now MM, Vientiane Times LA,
 *                              Tempo.co ID
 *   - Central Asia & Caucasus: Eurasianet (pan-region), OC Media GE/AM/AZ,
 *                              Akipress KG, Asia-Plus TJ, The Astana Times KZ,
 *                              Daryo UZ, JAMnews (pan-Caucasus)
 *   - Eastern Mediterranean:   Ekathimerini GR, Cyprus Mail CY, Hürriyet Daily News TR,
 *                              Balkan Insight (pan-Balkans), N1 (pan-Balkans)
 *   - Oceania & Pacific:       RNZ Pacific NZ, ABC Pacific AU, Islands Business FJ,
 *                              Devpolicy Blog (Pacific development), PNG Post-Courier PG
 *   - Global Health:           STAT News, The Lancet (news), WHO News,
 *                              Devex Global Health, Health Policy Watch
 *   - Energy & Resources:      Oilprice.com, Renewables Now, Carbon Brief,
 *                              Upstream Online, Argus Media
 *   - Tech & Cyber Depth:      The Record (Recorded Future), BleepingComputer,
 *                              CyberScoop, Risky.biz, Dark Reading
 *   - Migration & Refugees:    UNHCR News, Mixed Migration Centre,
 *                              The New Humanitarian, Refugees International,
 *                              InfoMigrants
 *   - Arms & Disarmament:      Arms Control Association, SIPRI News,
 *                              Defense Post, War on the Rocks, Janes
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Southeast Asia Depth ────────────────────────────────────────────────
    {
      slug:            'bangkok-post',
      name:            'Bangkok Post',
      description:     'Thailand\'s leading English-language daily covering ASEAN politics, economics, and regional affairs',
      url:             'https://www.bangkokpost.com',
      tier:            'major',
      trust_score:     0.83,
      language:        'en',
      country:         'TH',
      categories:      JSON.stringify(['politics', 'economy', 'breaking', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.bangkokpost.com/rss/data/topstories.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'straits-times-sg',
      name:            'The Straits Times',
      description:     'Singapore\'s flagship newspaper — authoritative coverage of ASEAN, Asia-Pacific diplomacy, and finance',
      url:             'https://www.straitstimes.com',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'SG',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.straitstimes.com/news/asia/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'rappler-ph',
      name:            'Rappler',
      description:     'Philippines\' leading digital-native news platform covering democracy, disinformation, and Southeast Asian affairs',
      url:             'https://www.rappler.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'PH',
      categories:      JSON.stringify(['politics', 'breaking', 'technology', 'elections']),
      rss_feeds:       JSON.stringify(['https://www.rappler.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'vnexpress-international',
      name:            'VnExpress International',
      description:     'Vietnam\'s most-read English news outlet — economy, society, and Southeast Asian integration',
      url:             'https://e.vnexpress.net',
      tier:            'major',
      trust_score:     0.80,
      language:        'en',
      country:         'VN',
      categories:      JSON.stringify(['economy', 'politics', 'technology', 'breaking']),
      rss_feeds:       JSON.stringify(['https://e.vnexpress.net/rss/news.rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'nikkei-asia',
      name:            'Nikkei Asia',
      description:     'Pan-Asian business intelligence from Japan\'s Nikkei group — essential for ASEAN economic coverage',
      url:             'https://asia.nikkei.com',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'JP',
      categories:      JSON.stringify(['economy', 'geopolitics', 'technology', 'markets']),
      rss_feeds:       JSON.stringify(['https://asia.nikkei.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'phnom-penh-post',
      name:            'Phnom Penh Post',
      description:     'Cambodia\'s English-language newspaper of record covering politics and development',
      url:             'https://www.phnompenhpost.com',
      tier:            'regional',
      trust_score:     0.72,
      language:        'en',
      country:         'KH',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.phnompenhpost.com/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'myanmar-now',
      name:            'Myanmar Now',
      description:     'Independent journalism from Myanmar covering post-coup resistance, conflict, and human rights',
      url:             'https://myanmar-now.org',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'MM',
      categories:      JSON.stringify(['conflict', 'politics', 'breaking', 'security']),
      rss_feeds:       JSON.stringify(['https://myanmar-now.org/en/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'vientiane-times',
      name:            'Vientiane Times',
      description:     'Laos\' primary English-language newspaper covering governance and Mekong region development',
      url:             'https://www.vientianetimes.org.la',
      tier:            'regional',
      trust_score:     0.65,
      language:        'en',
      country:         'LA',
      categories:      JSON.stringify(['politics', 'economy', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.vientianetimes.org.la/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'tempo-co-id',
      name:            'Tempo.co',
      description:     'Indonesia\'s premier investigative news magazine — politics, corruption, and regional security',
      url:             'https://en.tempo.co',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'ID',
      categories:      JSON.stringify(['politics', 'economy', 'security', 'breaking']),
      rss_feeds:       JSON.stringify(['https://en.tempo.co/rss']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Central Asia & Caucasus ─────────────────────────────────────────────
    {
      slug:            'eurasianet',
      name:            'Eurasianet',
      description:     'Independent coverage of Central Asia, the Caucasus, and the wider Eurasian region',
      url:             'https://eurasianet.org',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'politics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://eurasianet.org/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'oc-media-caucasus',
      name:            'OC Media',
      description:     'Open Caucasus Media — independent journalism from Georgia, Armenia, and Azerbaijan',
      url:             'https://oc-media.org',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'GE',
      categories:      JSON.stringify(['politics', 'conflict', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://oc-media.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'akipress-kg',
      name:            'AKIpress',
      description:     'Kyrgyzstan\'s leading news agency — Central Asian politics and security',
      url:             'https://akipress.com',
      tier:            'regional',
      trust_score:     0.72,
      language:        'en',
      country:         'KG',
      categories:      JSON.stringify(['politics', 'security', 'economy']),
      rss_feeds:       JSON.stringify(['https://akipress.com/rss/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'asia-plus-tj',
      name:            'Asia-Plus',
      description:     'Tajikistan\'s independent news — Central Asian affairs, border conflicts, and regional development',
      url:             'https://asiaplustj.info/en',
      tier:            'regional',
      trust_score:     0.70,
      language:        'en',
      country:         'TJ',
      categories:      JSON.stringify(['politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://asiaplustj.info/en/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'astana-times-kz',
      name:            'The Astana Times',
      description:     'Kazakhstan\'s English-language newspaper covering diplomacy, energy, and Central Asian geopolitics',
      url:             'https://astanatimes.com',
      tier:            'regional',
      trust_score:     0.70,
      language:        'en',
      country:         'KZ',
      categories:      JSON.stringify(['geopolitics', 'economy', 'energy', 'politics']),
      rss_feeds:       JSON.stringify(['https://astanatimes.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'daryo-uz',
      name:            'Daryo',
      description:     'Uzbekistan\'s leading independent online news outlet — reform era coverage and regional affairs',
      url:             'https://daryo.uz/en',
      tier:            'regional',
      trust_score:     0.68,
      language:        'en',
      country:         'UZ',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://daryo.uz/en/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'jamnews-caucasus',
      name:            'JAMnews',
      description:     'Pan-Caucasus independent journalism covering Georgia, Armenia, Azerbaijan, and the North Caucasus',
      url:             'https://jam-news.net',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'GE',
      categories:      JSON.stringify(['conflict', 'politics', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://jam-news.net/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Eastern Mediterranean & Balkans ─────────────────────────────────────
    {
      slug:            'ekathimerini-gr',
      name:            'Ekathimerini',
      description:     'Greece\'s English-language newspaper of record — EU politics, migration, Eastern Mediterranean energy',
      url:             'https://www.ekathimerini.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'GR',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics', 'migration']),
      rss_feeds:       JSON.stringify(['https://www.ekathimerini.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'cyprus-mail',
      name:            'Cyprus Mail',
      description:     'Cyprus\' oldest English-language daily — EU affairs, Eastern Mediterranean geopolitics',
      url:             'https://cyprus-mail.com',
      tier:            'regional',
      trust_score:     0.76,
      language:        'en',
      country:         'CY',
      categories:      JSON.stringify(['politics', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://cyprus-mail.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'hurriyet-daily-news-tr',
      name:            'Hürriyet Daily News',
      description:     'Turkey\'s leading English-language daily — key for NATO, migration, and Middle East coverage',
      url:             'https://www.hurriyetdailynews.com',
      tier:            'major',
      trust_score:     0.78,
      language:        'en',
      country:         'TR',
      categories:      JSON.stringify(['politics', 'geopolitics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.hurriyetdailynews.com/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'balkan-insight',
      name:            'Balkan Insight',
      description:     'BIRN\'s investigative journalism across the Balkans — EU accession, war crimes, corruption',
      url:             'https://balkaninsight.com',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'RS',
      categories:      JSON.stringify(['politics', 'security', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://balkaninsight.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'n1-info-balkans',
      name:            'N1',
      description:     'CNN-affiliated pan-Balkan news network covering Serbia, Croatia, Bosnia-Herzegovina',
      url:             'https://n1info.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'RS',
      categories:      JSON.stringify(['politics', 'breaking', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://n1info.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Oceania & Pacific ───────────────────────────────────────────────────
    {
      slug:            'rnz-pacific',
      name:            'RNZ Pacific',
      description:     'Radio New Zealand\'s Pacific service — essential for Pacific Islands diplomacy and climate coverage',
      url:             'https://www.rnz.co.nz/international',
      tier:            'major',
      trust_score:     0.88,
      language:        'en',
      country:         'NZ',
      categories:      JSON.stringify(['geopolitics', 'climate', 'politics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.rnz.co.nz/rss/pacific.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'abc-pacific-au',
      name:            'ABC Pacific',
      description:     'Australian Broadcasting Corporation\'s Pacific beat — geopolitics, climate adaptation, development',
      url:             'https://www.abc.net.au/pacific',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['geopolitics', 'climate', 'politics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.abc.net.au/news/feed/2942460/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'islands-business-fj',
      name:            'Islands Business',
      description:     'Pacific Islands regional business and politics magazine — Fiji-based, pan-Pacific coverage',
      url:             'https://islandsbusiness.com',
      tier:            'regional',
      trust_score:     0.72,
      language:        'en',
      country:         'FJ',
      categories:      JSON.stringify(['economy', 'politics', 'climate']),
      rss_feeds:       JSON.stringify(['https://islandsbusiness.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'devpolicy-blog-pacific',
      name:            'Devpolicy Blog',
      description:     'ANU\'s Development Policy Centre — evidence-based analysis on Pacific development and aid',
      url:             'https://devpolicy.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['economy', 'geopolitics', 'climate', 'health']),
      rss_feeds:       JSON.stringify(['https://devpolicy.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Global Health ───────────────────────────────────────────────────────
    {
      slug:            'stat-news',
      name:            'STAT News',
      description:     'Premier health and medicine journalism — pharma, biotech, public health, and pandemic preparedness',
      url:             'https://www.statnews.com',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'science', 'technology', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.statnews.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'lancet-news',
      name:            'The Lancet',
      description:     'World\'s most prestigious medical journal — breaking health research and global health policy',
      url:             'https://www.thelancet.com',
      tier:            'premium',
      trust_score:     0.95,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['health', 'science']),
      rss_feeds:       JSON.stringify(['https://www.thelancet.com/rssfeed/lancet_online.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'who-news',
      name:            'WHO News',
      description:     'World Health Organization official news — disease outbreaks, health emergencies, policy guidance',
      url:             'https://www.who.int/news',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['health', 'breaking', 'science']),
      rss_feeds:       JSON.stringify(['https://www.who.int/rss-feeds/news-english.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'devex-global-health',
      name:            'Devex',
      description:     'Global development platform — health aid, funding, and development policy news',
      url:             'https://www.devex.com',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.devex.com/news/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'health-policy-watch',
      name:            'Health Policy Watch',
      description:     'Geneva-based global health policy journalism — WHO, pandemic preparedness, health financing',
      url:             'https://healthpolicy-watch.news',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['health', 'politics', 'science']),
      rss_feeds:       JSON.stringify(['https://healthpolicy-watch.news/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Energy & Resources ──────────────────────────────────────────────────
    {
      slug:            'oilprice-com',
      name:            'OilPrice.com',
      description:     'Leading energy markets news — oil, gas, renewables pricing, and geopolitical supply disruptions',
      url:             'https://oilprice.com',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['energy', 'markets', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://oilprice.com/rss/main']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'renewables-now',
      name:            'Renewables Now',
      description:     'Global renewable energy news — solar, wind, storage, green hydrogen, and energy transition',
      url:             'https://renewablesnow.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'BG',
      categories:      JSON.stringify(['energy', 'climate', 'technology', 'economy']),
      rss_feeds:       JSON.stringify(['https://renewablesnow.com/news/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'carbon-brief',
      name:            'Carbon Brief',
      description:     'UK-based climate science and energy policy analysis — authoritative climate reporting',
      url:             'https://www.carbonbrief.org',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['climate', 'energy', 'science', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.carbonbrief.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'upstream-online',
      name:            'Upstream Online',
      description:     'Oil & gas industry intelligence from NHST Media — exploration, production, offshore energy',
      url:             'https://www.upstreamonline.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['energy', 'economy', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.upstreamonline.com/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'argus-media',
      name:            'Argus Media',
      description:     'Global energy and commodity price reporting — crucial for market intelligence and supply chain tracking',
      url:             'https://www.argusmedia.com',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['energy', 'markets', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.argusmedia.com/en/blog/rss']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Tech & Cyber Depth ──────────────────────────────────────────────────
    {
      slug:            'the-record-recorded-future',
      name:            'The Record',
      description:     'Recorded Future\'s cybersecurity newsroom — threat intelligence, nation-state campaigns, breaches',
      url:             'https://therecord.media',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'technology', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://therecord.media/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'bleepingcomputer',
      name:            'BleepingComputer',
      description:     'Cybersecurity news and malware analysis — ransomware tracking, vulnerability disclosures',
      url:             'https://www.bleepingcomputer.com',
      tier:            'major',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'technology', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.bleepingcomputer.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'cyberscoop',
      name:            'CyberScoop',
      description:     'Cybersecurity policy and intelligence — government cyber, defense, and national security tech',
      url:             'https://cyberscoop.com',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'politics', 'technology']),
      rss_feeds:       JSON.stringify(['https://cyberscoop.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'risky-biz',
      name:            'Risky Business',
      description:     'Infosec news and analysis podcast/newsletter — insider perspective on threat landscape',
      url:             'https://risky.biz',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['security', 'technology', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://risky.biz/feeds/risky-business/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'dark-reading',
      name:            'Dark Reading',
      description:     'Enterprise cybersecurity news — zero-days, APTs, cloud security, and CISO perspectives',
      url:             'https://www.darkreading.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'technology', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.darkreading.com/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Migration & Refugees ────────────────────────────────────────────────
    {
      slug:            'unhcr-news',
      name:            'UNHCR News',
      description:     'UN Refugee Agency official news — displacement crises, refugee policy, humanitarian emergencies',
      url:             'https://www.unhcr.org/news',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['migration', 'conflict', 'breaking', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.unhcr.org/rss/news.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'mixed-migration-centre',
      name:            'Mixed Migration Centre',
      description:     'Data-driven migration analysis — routes, risks, and policy from the Danish Refugee Council',
      url:             'https://mixedmigration.org',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'DK',
      categories:      JSON.stringify(['migration', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://mixedmigration.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'new-humanitarian',
      name:            'The New Humanitarian',
      description:     'Independent humanitarian journalism — conflict, displacement, aid, and development crises',
      url:             'https://www.thenewhumanitarian.org',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['conflict', 'migration', 'health', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.thenewhumanitarian.org/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'refugees-international',
      name:            'Refugees International',
      description:     'Advocacy and field research on displacement — independent recommendations to policymakers',
      url:             'https://www.refugeesinternational.org',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['migration', 'geopolitics', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.refugeesinternational.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'infomigrants',
      name:            'InfoMigrants',
      description:     'France Médias Monde migration journalism — Mediterranean routes, European policy, migrant perspectives',
      url:             'https://www.infomigrants.net/en',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['migration', 'breaking', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.infomigrants.net/en/rss']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Arms & Disarmament ──────────────────────────────────────────────────
    {
      slug:            'arms-control-association',
      name:            'Arms Control Association',
      description:     'Nonpartisan arms control analysis — nuclear treaties, missile defense, WMD nonproliferation',
      url:             'https://www.armscontrol.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'geopolitics', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.armscontrol.org/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'sipri-news',
      name:            'SIPRI',
      description:     'Stockholm International Peace Research Institute — arms transfers, military spending, conflict data',
      url:             'https://www.sipri.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'SE',
      categories:      JSON.stringify(['security', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.sipri.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'defense-post',
      name:            'The Defense Post',
      description:     'Military and defense news — operations, procurement, and strategic developments worldwide',
      url:             'https://www.thedefensepost.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'conflict', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.thedefensepost.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'war-on-the-rocks',
      name:            'War on the Rocks',
      description:     'Expert commentary on national security, defense, and foreign policy — think-tank caliber analysis',
      url:             'https://warontherocks.com',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'geopolitics', 'politics']),
      rss_feeds:       JSON.stringify(['https://warontherocks.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'janes-defence',
      name:            'Janes',
      description:     'Premium defense and security intelligence — military equipment, threat assessments, country risk',
      url:             'https://www.janes.com',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['security', 'geopolitics', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.janes.com/feeds/news']),
      scrape_interval: 1800,
      active:          true,
    },
  ]

  // Idempotent: ON CONFLICT(slug) DO NOTHING
  for (const src of sources) {
    await knex('sources').insert(src).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'bangkok-post', 'straits-times-sg', 'rappler-ph', 'vnexpress-international',
    'nikkei-asia', 'phnom-penh-post', 'myanmar-now', 'vientiane-times', 'tempo-co-id',
    'eurasianet', 'oc-media-caucasus', 'akipress-kg', 'asia-plus-tj',
    'astana-times-kz', 'daryo-uz', 'jamnews-caucasus',
    'ekathimerini-gr', 'cyprus-mail', 'hurriyet-daily-news-tr',
    'balkan-insight', 'n1-info-balkans',
    'rnz-pacific', 'abc-pacific-au', 'islands-business-fj', 'devpolicy-blog-pacific',
    'stat-news', 'lancet-news', 'who-news', 'devex-global-health', 'health-policy-watch',
    'oilprice-com', 'renewables-now', 'carbon-brief', 'upstream-online', 'argus-media',
    'the-record-recorded-future', 'bleepingcomputer', 'cyberscoop', 'risky-biz', 'dark-reading',
    'unhcr-news', 'mixed-migration-centre', 'new-humanitarian', 'refugees-international', 'infomigrants',
    'arms-control-association', 'sipri-news', 'defense-post', 'war-on-the-rocks', 'janes-defence',
  ]
  await knex('sources').whereIn('slug', slugs).del()
}
