import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 250+ feeds
 *
 * Adds 40 new high-quality global RSS sources across:
 *   - SE Asia depth:        Rappler (PH), Coconuts Media (SE Asia), Vietnam News (VN),
 *                           Tempo English (ID), Thai PBS World (TH), Vietnam Insider (VN),
 *                           Free Malaysia Today (MY), The Irrawaddy (MM)
 *   - Nordic / Scandinavia: Copenhagen Post (DK), Norway Today (NO),
 *                           Arctic Today (Arctic), High North News (NO)
 *   - Eastern Europe:       Radio Prague International (CZ), Hungary Today (HU),
 *                           Romania Insider (RO), Sofia Globe (BG), Croatia Week (HR),
 *                           Slovak Spectator (SK), bne IntelliNews (EE/pan-Eastern Europe),
 *                           Moldova Now (MD)
 *   - Space Technology:     Spaceflight Now (US), NASASpaceflight (US), SpaceNews (US)
 *   - Health / Pandemic:    PAHO News (Americas), Global Health Now (US),
 *                           Outbreak News Today (global)
 *   - Francophone Africa:   Africa Confidential (UK/Africa), The Continent (SA),
 *                           News of Cameroon (CM), Agence Ecofin English (CI)
 *   - Maritime / Ocean:     The Maritime Executive (US), Splash247 (global), gCaptain (US)
 *   - Migration:            Migration Policy Institute (US), IOM News (global)
 *   - South Asia depth:     Nepali Times (NP), Dhaka Tribune (BD)
 *   - Pacific depth:        Islands Business (Pacific), Samoa Observer (WS),
 *                           Vanuatu Daily Post (VU)
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── SE Asia depth ────────────────────────────────────────────────────────────
    {
      slug:            'rappler',
      name:            'Rappler',
      description:     'Philippine investigative digital news outlet — fact-checking, accountability, and Southeast Asian affairs',
      url:             'https://www.rappler.com',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'PH',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'security', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.rappler.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'coconuts-media',
      name:            'Coconuts Media',
      description:     'Digital media network covering Bangkok, Jakarta, Manila, and other SE Asian cities — local English-language news',
      url:             'https://coconuts.co',
      tier:            'regional',
      trust_score:     0.79,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'technology']),
      rss_feeds:       JSON.stringify(['https://coconuts.co/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'vietnam-news-vn',
      name:            'Vietnam News',
      description:     'Vietnam\'s state-run English-language daily — official coverage of politics, economy, and ASEAN affairs',
      url:             'https://vietnamnews.vn',
      tier:            'national',
      trust_score:     0.72,
      language:        'en',
      country:         'VN',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://vietnamnews.vn/rss/world.rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'tempo-en',
      name:            'Tempo.co English',
      description:     'Indonesia\'s leading investigative magazine in English — politics, business, and human rights',
      url:             'https://en.tempo.co',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'ID',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://en.tempo.co/rss/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'thai-pbs-world',
      name:            'Thai PBS World',
      description:     'Thailand\'s public broadcaster English-language international news service — ASEAN and Mekong focus',
      url:             'https://www.thaipbsworld.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'TH',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'politics', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.thaipbsworld.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'vietnam-insider',
      name:            'Vietnam Insider',
      description:     'Independent English-language portal covering Vietnam economy, investment, and regional business',
      url:             'https://vietnaminsider.vn',
      tier:            'regional',
      trust_score:     0.74,
      language:        'en',
      country:         'VN',
      categories:      JSON.stringify(['economy', 'markets', 'politics', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://vietnaminsider.vn/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'freemalaysia-today',
      name:            'Free Malaysia Today',
      description:     'Independent Malaysian English-language news portal covering politics, economy, and regional affairs',
      url:             'https://www.freemalaysiatoday.com',
      tier:            'national',
      trust_score:     0.81,
      language:        'en',
      country:         'MY',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.freemalaysiatoday.com/category/nation/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'irrawaddy-mag',
      name:            'The Irrawaddy',
      description:     'Exiled Myanmar news magazine covering the military junta, conflict zones, and humanitarian crisis in depth',
      url:             'https://www.irrawaddy.com',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'MM',
      categories:      JSON.stringify(['conflict', 'humanitarian', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.irrawaddy.com/feed']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Nordic / Scandinavia ─────────────────────────────────────────────────────
    {
      slug:            'cphpost',
      name:            'The Copenhagen Post',
      description:     'Denmark\'s English-language newspaper covering Danish politics, economy, and Nordic affairs',
      url:             'https://cphpost.dk',
      tier:            'national',
      trust_score:     0.78,
      language:        'en',
      country:         'DK',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://cphpost.dk/?format=feed&type=rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'norway-today',
      name:            'Norway Today',
      description:     'Norway\'s English-language news portal covering Norwegian politics, economy, and Arctic affairs',
      url:             'https://norwaytoday.info',
      tier:            'national',
      trust_score:     0.76,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'climate']),
      rss_feeds:       JSON.stringify(['https://norwaytoday.info/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'arctic-today',
      name:            'Arctic Today',
      description:     'Dedicated Arctic news outlet covering geopolitics, climate change, Indigenous rights, and resource extraction across the polar region',
      url:             'https://www.arctictoday.com',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['climate', 'geopolitics', 'humanitarian', 'energy']),
      rss_feeds:       JSON.stringify(['https://www.arctictoday.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'high-north-news',
      name:            'High North News',
      description:     'Norwegian Arctic-focused outlet covering Svalbard, High North geopolitics, and climate science in English',
      url:             'https://www.highnorthnews.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['geopolitics', 'climate', 'security', 'energy']),
      rss_feeds:       JSON.stringify(['https://www.highnorthnews.com/en/feed']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Eastern Europe ───────────────────────────────────────────────────────────
    {
      slug:            'radio-prague-en',
      name:            'Radio Prague International',
      description:     'Czech public broadcaster\'s English-language service — Central European politics, culture, and history',
      url:             'https://english.radio.cz',
      tier:            'national',
      trust_score:     0.84,
      language:        'en',
      country:         'CZ',
      categories:      JSON.stringify(['breaking', 'politics', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://english.radio.cz/export/rss-all.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'hungary-today',
      name:            'Hungary Today',
      description:     'English-language Hungarian news portal covering politics, economy, and Central European affairs',
      url:             'https://hungarytoday.hu',
      tier:            'national',
      trust_score:     0.74,
      language:        'en',
      country:         'HU',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://hungarytoday.hu/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'romania-insider',
      name:            'Romania Insider',
      description:     'English-language portal for Romania — business, investment, politics, and Romania-EU relations',
      url:             'https://www.romania-insider.com',
      tier:            'national',
      trust_score:     0.77,
      language:        'en',
      country:         'RO',
      categories:      JSON.stringify(['breaking', 'economy', 'politics', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.romania-insider.com/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'sofia-globe',
      name:            'The Sofia Globe',
      description:     'Bulgaria\'s English-language independent news outlet covering Balkan politics and EU affairs',
      url:             'https://sofiaglobe.com',
      tier:            'national',
      trust_score:     0.79,
      language:        'en',
      country:         'BG',
      categories:      JSON.stringify(['breaking', 'politics', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://sofiaglobe.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'croatia-week',
      name:            'Croatia Week',
      description:     'Croatia\'s English-language news portal — politics, Adriatic tourism, economy, and EU integration news',
      url:             'https://www.croatiaweek.com',
      tier:            'national',
      trust_score:     0.73,
      language:        'en',
      country:         'HR',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.croatiaweek.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'spectator-sk',
      name:            'The Slovak Spectator',
      description:     'Slovakia\'s oldest English-language newspaper covering Central European politics and business',
      url:             'https://spectator.sme.sk',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'SK',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://spectator.sme.sk/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'bne-intellinews',
      name:            'bne IntelliNews',
      description:     'Financial and political intelligence for Central & Eastern Europe, Russia, and CIS — authoritative business reporting',
      url:             'https://www.intellinews.com',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['economy', 'geopolitics', 'markets', 'security']),
      rss_feeds:       JSON.stringify(['https://www.intellinews.com/rss/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'moldova-now',
      name:            'Moldova Now (IPN)',
      description:     'Info-Prim Neo — Moldova\'s leading English-language news agency covering politics and Black Sea region',
      url:             'https://www.ipn.md/en',
      tier:            'national',
      trust_score:     0.75,
      language:        'en',
      country:         'MD',
      categories:      JSON.stringify(['breaking', 'politics', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.ipn.md/en/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Space Technology ──────────────────────────────────────────────────────────
    {
      slug:            'spaceflightnow',
      name:            'Spaceflight Now',
      description:     'Specialist rocket launch coverage and space mission reporting — real-time mission updates globally',
      url:             'https://spaceflightnow.com',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['space', 'science', 'technology']),
      rss_feeds:       JSON.stringify(['https://spaceflightnow.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'nasaspaceflight',
      name:            'NASASpaceflight.com',
      description:     'Community-driven space news covering launch vehicles, spacecraft, and industry developments in depth',
      url:             'https://www.nasaspaceflight.com',
      tier:            'specialised',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['space', 'science', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.nasaspaceflight.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'spacenews',
      name:            'SpaceNews',
      description:     'Authoritative trade publication for the global space industry — policy, business, and national security space',
      url:             'https://spacenews.com',
      tier:            'specialised',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['space', 'technology', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://spacenews.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Health / Pandemic Intelligence ────────────────────────────────────────────
    {
      slug:            'paho-news',
      name:            'PAHO News',
      description:     'Pan American Health Organization — official WHO/Americas health alerts, disease outbreaks, and epidemic updates',
      url:             'https://www.paho.org',
      tier:            'specialised',
      trust_score:     0.94,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['health', 'humanitarian', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.paho.org/en/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'global-health-now',
      name:            'Global Health Now',
      description:     'Johns Hopkins Bloomberg School of Public Health daily briefing — global health crises, outbreak intelligence',
      url:             'https://www.globalhealthnow.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'humanitarian', 'science']),
      rss_feeds:       JSON.stringify(['https://www.globalhealthnow.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'outbreak-news-today',
      name:            'Outbreak News Today',
      description:     'Specialist tracker for infectious disease outbreaks, epidemic warnings, and public health emergencies worldwide',
      url:             'https://outbreaknewstoday.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['health', 'humanitarian', 'breaking']),
      rss_feeds:       JSON.stringify(['https://outbreaknewstoday.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Francophone Africa / Africa depth ─────────────────────────────────────────
    {
      slug:            'africa-confidential',
      name:            'Africa Confidential',
      description:     'London-based fortnightly intelligence report on African politics, business, and security since 1960',
      url:             'https://www.africa-confidential.com',
      tier:            'specialised',
      trust_score:     0.93,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['geopolitics', 'security', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.africa-confidential.com/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'thecontinentafrica',
      name:            'The Continent',
      description:     'Pan-African English weekly distributed via WhatsApp — independent, high-quality journalism across the continent',
      url:             'https://thecontinentafrica.com',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'ZA',
      categories:      JSON.stringify(['geopolitics', 'politics', 'humanitarian', 'economy']),
      rss_feeds:       JSON.stringify(['https://thecontinentafrica.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'news-of-cameroon',
      name:            'News of Cameroon',
      description:     'English-language Cameroonian news outlet covering politics, Anglophone crisis, and Central Africa affairs',
      url:             'https://www.newsofcameroon.com',
      tier:            'national',
      trust_score:     0.74,
      language:        'en',
      country:         'CM',
      categories:      JSON.stringify(['breaking', 'conflict', 'politics', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.newsofcameroon.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'agence-ecofin-en',
      name:            'Agence Ecofin English',
      description:     'Specialised financial news agency covering Central and West African economies, mining, and agribusiness in English',
      url:             'https://www.agenceecofin.com/en',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'CI',
      categories:      JSON.stringify(['economy', 'markets', 'energy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.agenceecofin.com/articles/rss']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Maritime / Ocean Intelligence ─────────────────────────────────────────────
    {
      slug:            'maritime-executive',
      name:            'The Maritime Executive',
      description:     'Global maritime industry news covering shipping, naval affairs, piracy, and sea lane security',
      url:             'https://maritime-executive.com',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'economy', 'geopolitics', 'technology']),
      rss_feeds:       JSON.stringify(['https://maritime-executive.com/rss/news.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'splash247',
      name:            'Splash247',
      description:     'Global shipping and maritime news — freight markets, container shipping, and fleet intelligence',
      url:             'https://splash247.com',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['economy', 'markets', 'geopolitics', 'technology']),
      rss_feeds:       JSON.stringify(['https://splash247.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'gcaptain',
      name:            'gCaptain',
      description:     'Maritime and offshore industry news — vessel incidents, coast guard alerts, and port operations',
      url:             'https://gcaptain.com',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'economy', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://gcaptain.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Migration / Diaspora Intelligence ─────────────────────────────────────────
    {
      slug:            'mpi-news',
      name:            'Migration Policy Institute',
      description:     'Washington DC think-tank on migration — data-driven analysis of global migration, refugees, and asylum policy',
      url:             'https://www.migrationpolicy.org',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['humanitarian', 'geopolitics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://www.migrationpolicy.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'iom-news',
      name:            'IOM News',
      description:     'International Organization for Migration — official updates on displacement crises, smuggling routes, and migration flows',
      url:             'https://www.iom.int',
      tier:            'specialised',
      trust_score:     0.92,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['humanitarian', 'conflict', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.iom.int/rss']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── South Asia depth ──────────────────────────────────────────────────────────
    {
      slug:            'nepali-times',
      name:            'Nepali Times',
      description:     'Nepal\'s independent English weekly covering Himalayan politics, Sino-Indian competition, and disaster resilience',
      url:             'https://www.nepalitimes.com',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'NP',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'politics', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.nepalitimes.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'dhaka-tribune',
      name:            'Dhaka Tribune',
      description:     'Bangladesh\'s independent English-language daily — Bay of Bengal affairs, climate vulnerability, and South Asian politics',
      url:             'https://www.dhakatribune.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'BD',
      categories:      JSON.stringify(['breaking', 'climate', 'geopolitics', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.dhakatribune.com/rss']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Pacific depth ─────────────────────────────────────────────────────────────
    {
      slug:            'islands-business',
      name:            'Islands Business',
      description:     'Pacific Islands business and political magazine — Fiji, PNG, Solomons, Vanuatu, and Pacific Forum affairs',
      url:             'https://islandsbusiness.com',
      tier:            'regional',
      trust_score:     0.80,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'economy', 'climate', 'politics']),
      rss_feeds:       JSON.stringify(['https://islandsbusiness.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'samoa-observer',
      name:            'Samoa Observer',
      description:     'Samoa\'s independent English-language newspaper — Pacific small island state politics and climate change',
      url:             'https://www.samoaobserver.ws',
      tier:            'national',
      trust_score:     0.75,
      language:        'en',
      country:         'WS',
      categories:      JSON.stringify(['breaking', 'climate', 'politics', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.samoaobserver.ws/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'vanuatu-daily-post',
      name:            'Vanuatu Daily Post',
      description:     'Vanuatu\'s independent English-language newspaper covering Pacific Islands politics and climate vulnerability',
      url:             'https://www.dailypost.vu',
      tier:            'national',
      trust_score:     0.72,
      language:        'en',
      country:         'VU',
      categories:      JSON.stringify(['breaking', 'climate', 'politics', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.dailypost.vu/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    // SE Asia depth
    'rappler', 'coconuts-media', 'vietnam-news-vn', 'tempo-en',
    'thai-pbs-world', 'vietnam-insider', 'freemalaysia-today', 'irrawaddy-mag',
    // Nordic / Scandinavia
    'cphpost', 'norway-today', 'arctic-today', 'high-north-news',
    // Eastern Europe
    'radio-prague-en', 'hungary-today', 'romania-insider', 'sofia-globe',
    'croatia-week', 'spectator-sk', 'bne-intellinews', 'moldova-now',
    // Space Technology
    'spaceflightnow', 'nasaspaceflight', 'spacenews',
    // Health / Pandemic
    'paho-news', 'global-health-now', 'outbreak-news-today',
    // Francophone Africa
    'africa-confidential', 'thecontinentafrica', 'news-of-cameroon', 'agence-ecofin-en',
    // Maritime
    'maritime-executive', 'splash247', 'gcaptain',
    // Migration
    'mpi-news', 'iom-news',
    // South Asia depth
    'nepali-times', 'dhaka-tribune',
    // Pacific depth
    'islands-business', 'samoa-observer', 'vanuatu-daily-post',
  ]

  await knex('sources').whereIn('slug', slugs).delete()
}
