import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 120+ feeds
 *
 * Adds 40 new high-quality global RSS sources across:
 *   - SE Asia: Jakarta Post, Bangkok Post, Philippine Daily Inquirer, VnExpress, CNA
 *   - Africa (new): BusinessDay Nigeria, Africanews, Daily Monitor Uganda, News24 SA, Nation Africa
 *   - LatAm (new): Infobae, InSight Crime, La Nacion AR, El Colombiano, TeleSUR
 *   - Middle East / Central Asia: Rudaw, Jerusalem Post, Eurasianet, Hürriyet Daily
 *   - Europe (new): Balkan Insight/BIRN, Irish Times, SWI swissinfo, Novaya Gazeta EU, The Local
 *   - OSINT / Humanitarian: The New Humanitarian, ReliefWeb, Global Voices, ACLED Blog
 *   - Climate / Environment: Carbon Brief, Mongabay, Earth.Org
 *   - Health / Science: CIDRAP, Health Policy Watch, MIT Tech Review, New Scientist
 *   - Financial / Business: Caixin Global, Times of India Business
 *   - Asia-Pacific analysis: The Diplomat, PBS NewsHour
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── SE Asia ────────────────────────────────────────────────────────────────
    {
      slug:            'jakarta-post',
      name:            'The Jakarta Post',
      description:     'Indonesia's leading English-language daily newspaper',
      url:             'https://www.thejakartapost.com',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'ID',
      categories:      JSON.stringify(['geopolitics', 'economy', 'culture', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.thejakartapost.com/feed/en/news.rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'bangkok-post',
      name:            'Bangkok Post',
      description:     'Thailand's leading English-language newspaper',
      url:             'https://www.bangkokpost.com',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'TH',
      categories:      JSON.stringify(['geopolitics', 'economy', 'breaking', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.bangkokpost.com/rss/data/topstories.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'phil-daily-inquirer',
      name:            'Philippine Daily Inquirer',
      description:     'Philippines premier English-language broadsheet',
      url:             'https://newsinfo.inquirer.net',
      tier:            'national',
      trust_score:     0.86,
      language:        'en',
      country:         'PH',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://newsinfo.inquirer.net/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'vnexpress-en',
      name:            'VnExpress International',
      description:     'Vietnam's most-read online newspaper — English edition',
      url:             'https://e.vnexpress.net',
      tier:            'national',
      trust_score:     0.82,
      language:        'en',
      country:         'VN',
      categories:      JSON.stringify(['breaking', 'economy', 'culture', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://e.vnexpress.net/rss/news.rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'channel-news-asia',
      name:            'Channel NewsAsia (CNA)',
      description:     'Singapore-based pan-Asian English-language news network',
      url:             'https://www.channelnewsasia.com',
      tier:            'regional',
      trust_score:     0.91,
      language:        'en',
      country:         'SG',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'science', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416']),
      scrape_interval: 300,
      active:          true,
    },

    // ── Africa (new) ────────────────────────────────────────────────────────────
    {
      slug:            'businessday-ng',
      name:            'BusinessDay Nigeria',
      description:     'Nigeria's leading business and financial newspaper',
      url:             'https://businessday.ng',
      tier:            'national',
      trust_score:     0.85,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['economy', 'markets', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://businessday.ng/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'africanews',
      name:            'Africanews',
      description:     'Pan-African multilingual TV and online news — Euronews Africa bureau',
      url:             'https://www.africanews.com',
      tier:            'regional',
      trust_score:     0.86,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture', 'health']),
      rss_feeds:       JSON.stringify(['https://www.africanews.com/feed/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'daily-monitor-ug',
      name:            'Daily Monitor Uganda',
      description:     'Uganda's most-read independent daily newspaper',
      url:             'https://www.monitor.co.ug',
      tier:            'national',
      trust_score:     0.84,
      language:        'en',
      country:         'UG',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.monitor.co.ug/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'news24-za',
      name:            'News24 South Africa',
      description:     'South Africa's most-visited online news platform',
      url:             'https://www.news24.com',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'ZA',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'conflict', 'culture']),
      rss_feeds:       JSON.stringify(['https://feeds.news24.com/articles/news24/TopStories/rss']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'nation-africa',
      name:            'Nation Africa',
      description:     'Multi-country East African newspaper group (Kenya, Tanzania, Uganda, Rwanda)',
      url:             'https://nation.africa',
      tier:            'regional',
      trust_score:     0.88,
      language:        'en',
      country:         'KE',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'health', 'culture']),
      rss_feeds:       JSON.stringify(['https://nation.africa/kenya/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },

    // ── LatAm (new) ─────────────────────────────────────────────────────────────
    {
      slug:            'infobae-en',
      name:            'Infobae (English)',
      description:     'Argentina-based pan-LatAm digital news outlet — English edition',
      url:             'https://www.infobae.com/en',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'AR',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.infobae.com/feeds/rss/en/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'insight-crime',
      name:            'InSight Crime',
      description:     'Investigative analysis of organized crime and violence in LatAm',
      url:             'https://insightcrime.org',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['conflict', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://insightcrime.org/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'la-nacion-ar',
      name:            'La Nación Argentina',
      description:     'Argentina's second-largest newspaper with strong political coverage',
      url:             'https://www.lanacion.com.ar',
      tier:            'national',
      trust_score:     0.85,
      language:        'es',
      country:         'AR',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.lanacion.com.ar/arc/outboundfeeds/rss/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'el-colombiano',
      name:            'El Colombiano',
      description:     'Colombia's leading regional newspaper, based in Medellín',
      url:             'https://www.elcolombiano.com',
      tier:            'national',
      trust_score:     0.84,
      language:        'es',
      country:         'CO',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'conflict', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.elcolombiano.com/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'telesur-en',
      name:            'TeleSUR English',
      description:     'Pan-Latin American news network — regional perspective',
      url:             'https://www.telesurenglish.net',
      tier:            'regional',
      trust_score:     0.72,
      language:        'en',
      country:         'VE',
      categories:      JSON.stringify(['geopolitics', 'breaking', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.telesurenglish.net/rss/feed.xml']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Middle East / Central Asia (new) ────────────────────────────────────────
    {
      slug:            'rudaw-en',
      name:            'Rudaw English',
      description:     'Kurdistan Region-based news covering Iraq, Syria, and Greater Middle East',
      url:             'https://www.rudaw.net/english',
      tier:            'regional',
      trust_score:     0.85,
      language:        'en',
      country:         'IQ',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.rudaw.net/english/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'jerusalem-post',
      name:            'The Jerusalem Post',
      description:     'Israel's leading English-language newspaper',
      url:             'https://www.jpost.com',
      tier:            'national',
      trust_score:     0.82,
      language:        'en',
      country:         'IL',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.jpost.com/Rss/RssFeedsHeadlines.aspx']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'eurasianet',
      name:            'Eurasianet',
      description:     'Independent journalism covering Central Asia and the Caucasus',
      url:             'https://eurasianet.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://eurasianet.org/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'hurriyet-daily-news',
      name:            'Hürriyet Daily News',
      description:     'Turkey's oldest English-language daily newspaper',
      url:             'https://www.hurriyetdailynews.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'TR',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.hurriyetdailynews.com/rss']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Europe (new) ────────────────────────────────────────────────────────────
    {
      slug:            'balkan-insight',
      name:            'Balkan Insight (BIRN)',
      description:     'Balkan Investigative Reporting Network — independent Balkans journalism',
      url:             'https://balkaninsight.com',
      tier:            'specialised',
      trust_score:     0.92,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://balkaninsight.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'irish-times',
      name:            'The Irish Times',
      description:     'Ireland's newspaper of record — international & EU coverage',
      url:             'https://www.irishtimes.com',
      tier:            'national',
      trust_score:     0.91,
      language:        'en',
      country:         'IE',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.irishtimes.com/cmlink/the-irish-times-news-1.1319192']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'swissinfo-en',
      name:            'SWI swissinfo.ch',
      description:     'Swiss Broadcasting Corporation's international service — 10 languages',
      url:             'https://www.swissinfo.ch/eng',
      tier:            'national',
      trust_score:     0.92,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['geopolitics', 'economy', 'breaking', 'culture', 'science']),
      rss_feeds:       JSON.stringify(['https://www.swissinfo.ch/eng/rss/all_news_en.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'novaya-gazeta-eu',
      name:            'Novaya Gazeta Europe',
      description:     'Russian independent investigative journalism in exile',
      url:             'https://novayagazeta.eu/en',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'conflict', 'breaking']),
      rss_feeds:       JSON.stringify(['https://novayagazeta.eu/en/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-local-eu',
      name:            'The Local Europe',
      description:     'English-language news from 9 European countries for expats and internationals',
      url:             'https://www.thelocal.com',
      tier:            'regional',
      trust_score:     0.84,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['breaking', 'culture', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://feeds.thelocal.com/rss/eu']),
      scrape_interval: 900,
      active:          true,
    },

    // ── OSINT / Humanitarian ────────────────────────────────────────────────────
    {
      slug:            'new-humanitarian',
      name:            'The New Humanitarian',
      description:     'Independent humanitarian journalism — crises, displacement, aid',
      url:             'https://www.thenewhumanitarian.org',
      tier:            'specialised',
      trust_score:     0.93,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['conflict', 'health', 'geopolitics', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.thenewhumanitarian.org/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'reliefweb',
      name:            'ReliefWeb',
      description:     'UN OCHA humanitarian information service — disasters, crises, alerts',
      url:             'https://reliefweb.int',
      tier:            'specialised',
      trust_score:     0.95,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['conflict', 'health', 'climate', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://reliefweb.int/headlines/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'global-voices',
      name:            'Global Voices',
      description:     'International citizen journalism network — underreported stories',
      url:             'https://globalvoices.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['culture', 'geopolitics', 'breaking', 'health']),
      rss_feeds:       JSON.stringify(['https://globalvoices.org/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'acled-blog',
      name:            'ACLED Research Blog',
      description:     'Armed Conflict Location & Event Data Project — conflict analysis',
      url:             'https://acleddata.com/blog',
      tier:            'specialised',
      trust_score:     0.96,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['conflict', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://acleddata.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Climate / Environment ───────────────────────────────────────────────────
    {
      slug:            'carbon-brief',
      name:            'Carbon Brief',
      description:     'Specialist UK climate science and energy policy analysis',
      url:             'https://www.carbonbrief.org',
      tier:            'specialised',
      trust_score:     0.94,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['climate', 'science', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.carbonbrief.org/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'mongabay',
      name:            'Mongabay',
      description:     'Award-winning environmental journalism — forests, biodiversity, oceans',
      url:             'https://news.mongabay.com',
      tier:            'specialised',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['climate', 'science', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://news.mongabay.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'earth-org',
      name:            'Earth.Org',
      description:     'Environmental data journalism and climate policy analysis',
      url:             'https://earth.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['climate', 'science', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://earth.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Health / Science ────────────────────────────────────────────────────────
    {
      slug:            'cidrap',
      name:            'CIDRAP News',
      description:     'University of Minnesota Center for Infectious Disease Research and Policy',
      url:             'https://www.cidrap.umn.edu',
      tier:            'specialised',
      trust_score:     0.97,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'science', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.cidrap.umn.edu/news-perspective/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'health-policy-watch',
      name:            'Health Policy Watch',
      description:     'Independent global health and pharmaceutical policy reporting',
      url:             'https://healthpolicy-watch.news',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['health', 'geopolitics', 'science']),
      rss_feeds:       JSON.stringify(['https://healthpolicy-watch.news/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'mit-tech-review',
      name:            'MIT Technology Review',
      description:     'MIT's authoritative technology and science journalism since 1899',
      url:             'https://www.technologyreview.com',
      tier:            'specialised',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'science', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.technologyreview.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'new-scientist',
      name:            'New Scientist',
      description:     'UK weekly science and technology news magazine',
      url:             'https://www.newscientist.com',
      tier:            'specialised',
      trust_score:     0.92,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['science', 'health', 'technology', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.newscientist.com/feed/home/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Financial / Business ────────────────────────────────────────────────────
    {
      slug:            'caixin-global',
      name:            'Caixin Global',
      description:     'Independent Chinese financial media — China economy and markets in English',
      url:             'https://www.caixinglobal.com',
      tier:            'national',
      trust_score:     0.89,
      language:        'en',
      country:         'CN',
      categories:      JSON.stringify(['economy', 'markets', 'geopolitics', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.caixinglobal.com/rss/en.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'times-of-india',
      name:            'Times of India',
      description:     'India's highest-circulation English-language daily newspaper',
      url:             'https://timesofindia.indiatimes.com',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'technology', 'culture']),
      rss_feeds:       JSON.stringify(['https://timesofindia.indiatimes.com/rssfeedstopstories.cms']),
      scrape_interval: 300,
      active:          true,
    },

    // ── Asia-Pacific Analysis ───────────────────────────────────────────────────
    {
      slug:            'the-diplomat',
      name:            'The Diplomat',
      description:     'Authoritative Asia-Pacific news and analysis for foreign policy professionals',
      url:             'https://thediplomat.com',
      tier:            'specialised',
      trust_score:     0.93,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'economy', 'security', 'breaking']),
      rss_feeds:       JSON.stringify(['https://thediplomat.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'pbs-newshour',
      name:            'PBS NewsHour',
      description:     'PBS flagship news programme — US public broadcasting, authoritative global coverage',
      url:             'https://www.pbs.org/newshour',
      tier:            'national',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'health', 'science']),
      rss_feeds:       JSON.stringify(['https://www.pbs.org/newshour/feeds/rss/headlines']),
      scrape_interval: 600,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'jakarta-post', 'bangkok-post', 'phil-daily-inquirer', 'vnexpress-en', 'channel-news-asia',
    'businessday-ng', 'africanews', 'daily-monitor-ug', 'news24-za', 'nation-africa',
    'infobae-en', 'insight-crime', 'la-nacion-ar', 'el-colombiano', 'telesur-en',
    'rudaw-en', 'jerusalem-post', 'eurasianet', 'hurriyet-daily-news',
    'balkan-insight', 'irish-times', 'swissinfo-en', 'novaya-gazeta-eu', 'the-local-eu',
    'new-humanitarian', 'reliefweb', 'global-voices', 'acled-blog',
    'carbon-brief', 'mongabay', 'earth-org',
    'cidrap', 'health-policy-watch', 'mit-tech-review', 'new-scientist',
    'caixin-global', 'times-of-india',
    'the-diplomat', 'pbs-newshour',
  ]
  await knex('sources').whereIn('slug', slugs).delete()
}
