import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 300+ feeds
 *
 * Adds 50 new high-quality global RSS sources across underrepresented regions
 * and critical intelligence verticals:
 *
 *   - Pacific Islands:      Fiji Times (FJ), Samoa Observer (WS), Solomon Star (SB),
 *                           Vanuatu Daily Post (VU), Papua New Guinea Post-Courier (PG)
 *   - Caribbean:            Jamaica Gleaner (JM), Trinidad Guardian (TT),
 *                           Barbados Today (BB), Haiti Libre (HT), Dominica News (DM)
 *   - Balkans:              Kosovo Online (XK), North Macedonia MIA (MK),
 *                           Montenegro Daily (ME), Albania Daily News (AL)
 *   - Nordics (gaps):       Yle News (FI), The Local Sweden (SE),
 *                           Iceland Monitor (IS), Arctic Today (circumpolar)
 *   - East Europe (gaps):   Kyiv Post (UA — new outlet), Prague Morning (CZ),
 *                           Slovak Spectator (SK), Romania Insider (RO),
 *                           Hungary Today (HU), BNE IntelliNews (multi)
 *   - Francophone Africa:   RFI Afrique (pan-African FR), Le Monde Afrique (FR),
 *                           Abidjan.net (CI), Jeune Afrique (pan-African)
 *   - Space & Defence:      SpaceNews, Defense One, Jane's Defence (IISS),
 *                           The War Zone (US), Breaking Defense
 *   - Maritime & Trade:     Lloyd's List, The Maritime Executive, TradeWinds,
 *                           gCaptain, Splash 247
 *   - Global Think Tanks:   Brookings (US), Chatham House (UK), Carnegie Endowment,
 *                           RAND Commentary, IISS
 *   - Disinformation Watch: First Draft (now IREX Verified), Poynter Fact-Check,
 *                           Snopes, Full Fact (UK), AFP Fact Check
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Pacific Islands ───────────────────────────────────────────────────────
    {
      slug:            'fiji-times',
      name:            'Fiji Times',
      description:     'Fiji\'s oldest newspaper covering Pacific Island politics, climate, and regional affairs',
      url:             'https://www.fijitimes.com.fj',
      tier:            'regional',
      trust_score:     0.80,
      language:        'en',
      country:         'FJ',
      categories:      JSON.stringify(['climate', 'politics', 'pacific', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.fijitimes.com.fj/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'samoa-observer',
      name:            'Samoa Observer',
      description:     'Samoa\'s leading English-language newspaper covering Pacific affairs and climate',
      url:             'https://www.samoaobserver.ws',
      tier:            'regional',
      trust_score:     0.78,
      language:        'en',
      country:         'WS',
      categories:      JSON.stringify(['climate', 'politics', 'pacific']),
      rss_feeds:       JSON.stringify(['https://www.samoaobserver.ws/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'solomon-star',
      name:            'Solomon Star',
      description:     'Solomon Islands news covering regional security, logging, and Pacific geopolitics',
      url:             'https://www.solomonstarnews.com',
      tier:            'regional',
      trust_score:     0.75,
      language:        'en',
      country:         'SB',
      categories:      JSON.stringify(['security', 'politics', 'pacific', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.solomonstarnews.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'vanuatu-daily-post',
      name:            'Vanuatu Daily Post',
      description:     'Vanuatu news covering cyclones, Pacific diplomacy, and island affairs',
      url:             'https://www.dailypost.vu',
      tier:            'regional',
      trust_score:     0.76,
      language:        'en',
      country:         'VU',
      categories:      JSON.stringify(['climate', 'politics', 'pacific', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.dailypost.vu/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'png-post-courier',
      name:            'Post-Courier PNG',
      description:     'Papua New Guinea\'s main English newspaper covering mining, tribal affairs, and regional security',
      url:             'https://www.postcourier.com.pg',
      tier:            'regional',
      trust_score:     0.77,
      language:        'en',
      country:         'PG',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'pacific']),
      rss_feeds:       JSON.stringify(['https://www.postcourier.com.pg/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Caribbean ─────────────────────────────────────────────────────────────
    {
      slug:            'jamaica-gleaner',
      name:            'Jamaica Gleaner',
      description:     'Jamaica\'s oldest newspaper covering Caribbean politics, crime, and culture',
      url:             'https://jamaica-gleaner.com',
      tier:            'regional',
      trust_score:     0.84,
      language:        'en',
      country:         'JM',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://jamaica-gleaner.com/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'trinidad-guardian',
      name:            'Trinidad Guardian',
      description:     'Trinidad and Tobago\'s leading newspaper covering energy, regional trade, and Caribbean affairs',
      url:             'https://www.guardian.co.tt',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         'TT',
      categories:      JSON.stringify(['economy', 'energy', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.guardian.co.tt/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'barbados-today',
      name:            'Barbados Today',
      description:     'Barbados digital news covering Caribbean climate policy, tourism, and governance',
      url:             'https://barbadostoday.bb',
      tier:            'regional',
      trust_score:     0.79,
      language:        'en',
      country:         'BB',
      categories:      JSON.stringify(['climate', 'politics', 'economy']),
      rss_feeds:       JSON.stringify(['https://barbadostoday.bb/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'haiti-libre',
      name:            'Haiti Libre',
      description:     'Independent Haitian news in English/French covering security, politics, and humanitarian crises',
      url:             'https://www.haitilibre.com',
      tier:            'regional',
      trust_score:     0.74,
      language:        'en',
      country:         'HT',
      categories:      JSON.stringify(['security', 'humanitarian', 'politics', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.haitilibre.com/en/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'dominica-news-online',
      name:            'Dominica News Online',
      description:     'Dominica\'s digital newspaper covering hurricanes, climate, and Eastern Caribbean affairs',
      url:             'https://dominicanewsonline.com',
      tier:            'regional',
      trust_score:     0.73,
      language:        'en',
      country:         'DM',
      categories:      JSON.stringify(['climate', 'politics', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://dominicanewsonline.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Balkans ───────────────────────────────────────────────────────────────
    {
      slug:            'kosovo-online',
      name:            'Kosovo Online',
      description:     'English-language Kosovo news covering Serbia-Kosovo dialogue, EU accession, and Balkans security',
      url:             'https://www.kosovo-online.com',
      tier:            'regional',
      trust_score:     0.78,
      language:        'en',
      country:         'XK',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.kosovo-online.com/en/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'mia-north-macedonia',
      name:            'MIA North Macedonia',
      description:     'Macedonian Information Agency — English service covering EU accession and Balkans affairs',
      url:             'https://mia.mk/en',
      tier:            'regional',
      trust_score:     0.80,
      language:        'en',
      country:         'MK',
      categories:      JSON.stringify(['politics', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://mia.mk/en/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'cdm-montenegro',
      name:            'CDM Montenegro',
      description:     'Montenegrin news agency covering NATO integration, Balkans politics, and Adriatic affairs',
      url:             'https://www.cdm.me/en',
      tier:            'regional',
      trust_score:     0.77,
      language:        'en',
      country:         'ME',
      categories:      JSON.stringify(['politics', 'security', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.cdm.me/en/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'albania-daily-news',
      name:            'Albania Daily News',
      description:     'English-language Albanian news covering EU accession, politics, and regional affairs',
      url:             'https://albaniandailynews.com',
      tier:            'regional',
      trust_score:     0.76,
      language:        'en',
      country:         'AL',
      categories:      JSON.stringify(['politics', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://albaniandailynews.com/feed']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Nordics (gaps) ────────────────────────────────────────────────────────
    {
      slug:            'yle-news',
      name:            'Yle News',
      description:     'Finland\'s public broadcaster English service covering Nordic affairs, Russia border, and Arctic policy',
      url:             'https://yle.fi/news',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'FI',
      categories:      JSON.stringify(['geopolitics', 'security', 'climate', 'politics']),
      rss_feeds:       JSON.stringify(['https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'the-local-se',
      name:            'The Local Sweden',
      description:     'English-language Swedish news covering immigration, defence policy, and Nordic affairs',
      url:             'https://www.thelocal.se',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'SE',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.thelocal.se/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'iceland-monitor',
      name:            'Iceland Monitor',
      description:     'Icelandic English-language news covering volcanoes, Arctic, and Nordic geopolitics',
      url:             'https://icelandmonitor.mbl.is',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         'IS',
      categories:      JSON.stringify(['climate', 'science', 'politics', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://icelandmonitor.mbl.is/rss/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'arctic-today',
      name:            'Arctic Today',
      description:     'Circumpolar news covering Arctic shipping routes, climate, indigenous affairs, and military activity',
      url:             'https://www.arctictoday.com',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['climate', 'geopolitics', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://www.arctictoday.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },

    // ── East Europe (gaps) ────────────────────────────────────────────────────
    {
      slug:            'kyiv-post',
      name:            'Kyiv Post',
      description:     'Ukraine\'s English-language newspaper covering the war, reconstruction, and Eastern European security',
      url:             'https://www.kyivpost.com',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'UA',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'security', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.kyivpost.com/feed']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'prague-morning',
      name:            'Prague Morning',
      description:     'English-language Czech news covering Central European politics, economy, and EU affairs',
      url:             'https://praguemorning.cz',
      tier:            'regional',
      trust_score:     0.79,
      language:        'en',
      country:         'CZ',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://praguemorning.cz/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'slovak-spectator',
      name:            'Slovak Spectator',
      description:     'English-language Slovak news covering Visegrád politics, economy, and EU integration',
      url:             'https://spectator.sme.sk',
      tier:            'regional',
      trust_score:     0.83,
      language:        'en',
      country:         'SK',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://spectator.sme.sk/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'romania-insider',
      name:            'Romania Insider',
      description:     'English-language Romanian news covering Black Sea security, economy, and EU affairs',
      url:             'https://www.romania-insider.com',
      tier:            'regional',
      trust_score:     0.81,
      language:        'en',
      country:         'RO',
      categories:      JSON.stringify(['politics', 'economy', 'security', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.romania-insider.com/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'hungary-today',
      name:            'Hungary Today',
      description:     'English-language Hungarian news covering Visegrád politics, EU relations, and regional affairs',
      url:             'https://hungarytoday.hu',
      tier:            'regional',
      trust_score:     0.78,
      language:        'en',
      country:         'HU',
      categories:      JSON.stringify(['politics', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://hungarytoday.hu/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'bne-intellinews',
      name:            'bne IntelliNews',
      description:     'Business intelligence news covering Central/Eastern Europe, Russia, Turkey, and emerging markets',
      url:             'https://www.intellinews.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'UK',
      categories:      JSON.stringify(['economy', 'geopolitics', 'politics', 'markets']),
      rss_feeds:       JSON.stringify(['https://www.intellinews.com/rss']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Francophone Africa ────────────────────────────────────────────────────
    {
      slug:            'rfi-afrique',
      name:            'RFI Afrique',
      description:     'Radio France Internationale Africa coverage — coups, Sahel security, and Francophone politics',
      url:             'https://www.rfi.fr/en/africa',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.rfi.fr/en/africa/rss']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'le-monde-afrique',
      name:            'Le Monde Afrique',
      description:     'Le Monde\'s Africa desk covering Sahel, Great Lakes, and Francophone politics',
      url:             'https://www.lemonde.fr/en/africa/',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'politics', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.lemonde.fr/en/africa/rss_full.xml']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'abidjan-net',
      name:            'Abidjan.net',
      description:     'Côte d\'Ivoire\'s main news portal covering West African economy, politics, and cocoa markets',
      url:             'https://news.abidjan.net',
      tier:            'regional',
      trust_score:     0.74,
      language:        'fr',
      country:         'CI',
      categories:      JSON.stringify(['economy', 'politics', 'markets']),
      rss_feeds:       JSON.stringify(['https://news.abidjan.net/rss/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'jeune-afrique',
      name:            'Jeune Afrique',
      description:     'Pan-African magazine covering politics, business, and culture across Francophone Africa',
      url:             'https://www.jeuneafrique.com',
      tier:            'premium',
      trust_score:     0.87,
      language:        'fr',
      country:         'FR',
      categories:      JSON.stringify(['geopolitics', 'politics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.jeuneafrique.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Space & Defence ───────────────────────────────────────────────────────
    {
      slug:            'spacenews',
      name:            'SpaceNews',
      description:     'Leading space industry publication covering launches, satellites, and space policy',
      url:             'https://spacenews.com',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology', 'security', 'politics']),
      rss_feeds:       JSON.stringify(['https://spacenews.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'defense-one',
      name:            'Defense One',
      description:     'US defence news covering military technology, policy, and global security',
      url:             'https://www.defenseone.com',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'technology', 'geopolitics', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.defenseone.com/rss/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'the-war-zone',
      name:            'The War Zone',
      description:     'Defence and aviation news covering military operations, weapons systems, and OSINT analysis',
      url:             'https://www.thedrive.com/the-war-zone',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['conflict', 'security', 'technology', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.thedrive.com/the-war-zone/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'breaking-defense',
      name:            'Breaking Defense',
      description:     'Defence industry news covering procurement, policy, and military technology worldwide',
      url:             'https://breakingdefense.com',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'technology', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://breakingdefense.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'janes-defence',
      name:            'Janes',
      description:     'Global defence and security intelligence from IISS — the gold standard for military analysis',
      url:             'https://www.janes.com',
      tier:            'premium',
      trust_score:     0.94,
      language:        'en',
      country:         'UK',
      categories:      JSON.stringify(['security', 'geopolitics', 'conflict', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.janes.com/feeds/news']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Maritime & Trade ──────────────────────────────────────────────────────
    {
      slug:            'maritime-executive',
      name:            'The Maritime Executive',
      description:     'Shipping and maritime industry news covering trade routes, sanctions evasion, and port security',
      url:             'https://maritime-executive.com',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'security', 'geopolitics', 'markets']),
      rss_feeds:       JSON.stringify(['https://maritime-executive.com/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'gcaptain',
      name:            'gCaptain',
      description:     'Maritime news covering shipping, offshore energy, naval operations, and ocean policy',
      url:             'https://gcaptain.com',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'energy', 'security', 'climate']),
      rss_feeds:       JSON.stringify(['https://gcaptain.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'splash-247',
      name:            'Splash 247',
      description:     'Asian maritime shipping news covering trade, ports, and supply chain disruptions',
      url:             'https://splash247.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'SG',
      categories:      JSON.stringify(['economy', 'geopolitics', 'markets']),
      rss_feeds:       JSON.stringify(['https://splash247.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'tradewinds-news',
      name:            'TradeWinds',
      description:     'Global shipping news covering tanker markets, LNG, and maritime trade',
      url:             'https://www.tradewindsnews.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['economy', 'energy', 'markets']),
      rss_feeds:       JSON.stringify(['https://www.tradewindsnews.com/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'lloyds-list',
      name:            'Lloyd\'s List',
      description:     'World\'s oldest shipping publication — maritime trade intelligence since 1734',
      url:             'https://lloydslist.com',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'UK',
      categories:      JSON.stringify(['economy', 'geopolitics', 'security', 'markets']),
      rss_feeds:       JSON.stringify(['https://lloydslist.com/rss']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Global Think Tanks ────────────────────────────────────────────────────
    {
      slug:            'brookings',
      name:            'Brookings Institution',
      description:     'Leading US think tank covering foreign policy, economics, governance, and global development',
      url:             'https://www.brookings.edu',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'economy', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.brookings.edu/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'chatham-house',
      name:            'Chatham House',
      description:     'Royal Institute of International Affairs — UK\'s foremost think tank on global security and trade',
      url:             'https://www.chathamhouse.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'UK',
      categories:      JSON.stringify(['geopolitics', 'security', 'economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.chathamhouse.org/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'carnegie-endowment',
      name:            'Carnegie Endowment',
      description:     'Carnegie Endowment for International Peace — global policy research on conflict, democracy, and technology',
      url:             'https://carnegieendowment.org',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'security', 'politics', 'technology']),
      rss_feeds:       JSON.stringify(['https://carnegieendowment.org/rss/solr']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'rand-commentary',
      name:            'RAND Corporation',
      description:     'US defence and policy research covering military strategy, cybersecurity, and public health',
      url:             'https://www.rand.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'geopolitics', 'health', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.rand.org/pubs/feed.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'iiss-analysis',
      name:            'IISS',
      description:     'International Institute for Strategic Studies — premier defence and security analysis',
      url:             'https://www.iiss.org',
      tier:            'premium',
      trust_score:     0.94,
      language:        'en',
      country:         'UK',
      categories:      JSON.stringify(['security', 'conflict', 'geopolitics', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.iiss.org/rss']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Disinformation / Fact-Check ───────────────────────────────────────────
    {
      slug:            'poynter-factcheck',
      name:            'Poynter Fact-Check',
      description:     'Poynter Institute\'s fact-checking network covering claims verification and media literacy',
      url:             'https://www.poynter.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'technology', 'health', 'science']),
      rss_feeds:       JSON.stringify(['https://www.poynter.org/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'snopes',
      name:            'Snopes',
      description:     'Oldest fact-checking website covering viral claims, hoaxes, urban legends, and political misinfo',
      url:             'https://www.snopes.com',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'health', 'science', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.snopes.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'full-fact',
      name:            'Full Fact',
      description:     'UK\'s independent fact-checking charity covering political claims and statistical accuracy',
      url:             'https://fullfact.org',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         'UK',
      categories:      JSON.stringify(['politics', 'health', 'economy']),
      rss_feeds:       JSON.stringify(['https://fullfact.org/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'afp-factcheck',
      name:            'AFP Fact Check',
      description:     'Agence France-Presse\'s global fact-checking desk covering 80+ countries in multiple languages',
      url:             'https://factcheck.afp.com',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['politics', 'health', 'science', 'security']),
      rss_feeds:       JSON.stringify(['https://factcheck.afp.com/rss.xml']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'irex-verified',
      name:            'IREX Verified',
      description:     'Media literacy and disinformation research (formerly First Draft) covering information integrity',
      url:             'https://www.irex.org/project/verified',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.irex.org/feed']),
      scrape_interval: 900,
      active:          true,
    },
  ]

  // Idempotent: ON CONFLICT DO NOTHING — safe to re-run without duplicates
  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'fiji-times', 'samoa-observer', 'solomon-star', 'vanuatu-daily-post', 'png-post-courier',
    'jamaica-gleaner', 'trinidad-guardian', 'barbados-today', 'haiti-libre', 'dominica-news-online',
    'kosovo-online', 'mia-north-macedonia', 'cdm-montenegro', 'albania-daily-news',
    'yle-news', 'the-local-se', 'iceland-monitor', 'arctic-today',
    'kyiv-post', 'prague-morning', 'slovak-spectator', 'romania-insider', 'hungary-today', 'bne-intellinews',
    'rfi-afrique', 'le-monde-afrique', 'abidjan-net', 'jeune-afrique',
    'spacenews', 'defense-one', 'the-war-zone', 'breaking-defense', 'janes-defence',
    'maritime-executive', 'gcaptain', 'splash-247', 'tradewinds-news', 'lloyds-list',
    'brookings', 'chatham-house', 'carnegie-endowment', 'rand-commentary', 'iiss-analysis',
    'poynter-factcheck', 'snopes', 'full-fact', 'afp-factcheck', 'irex-verified',
  ]
  await knex('sources').whereIn('slug', slugs).del()
}
