import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 500+ feeds
 *
 * Adds 50 new high-quality global RSS sources across 10 verticals to cement
 * WorldPulse's leadership over WorldMonitor (now 500+ vs 435+).
 *
 *   - East Africa Depth (5):        The East African KE, Daily Monitor UG,
 *                                   The Citizen TZ (Business), Business Daily KE,
 *                                   The New Times RW (English)
 *   - Central & Eastern Europe (5): Novinky CZ, TVN24 PL, Index.hr HR,
 *                                   Novaya Gazeta Europe, Balkan Insight MK
 *   - Middle East Depth (5):        The National AE, L'Orient Le Jour LB,
 *                                   Middle East Eye GB, +972 Magazine IL,
 *                                   Ammon News JO
 *   - Oceania & Pacific Islands (5): Fiji Times FJ, Samoa Observer WS,
 *                                   Post-Courier PG, Solomon Star SB,
 *                                   Vanuatu Daily Post VU
 *   - Water & Sanitation (5):       Circle of Blue US, WaterAid GB,
 *                                   The Water Network, WASH Matters,
 *                                   International Water Association
 *   - Nuclear & Energy Security (5): World Nuclear News, Bulletin of the
 *                                   Atomic Scientists, Nuclear Threat Initiative,
 *                                   Energy Intelligence, Platts Energy
 *   - Humanitarian & Aid (5):       ReliefWeb (OCHA), IRIN News (The New Humanitarian),
 *                                   Devex, Humanitarian Practice Network,
 *                                   Global Voices
 *   - Digital Rights & Privacy (5): Access Now, EFF Deeplinks,
 *                                   Rest of World, Ranking Digital Rights,
 *                                   Digital Rights Foundation PK
 *   - Labor & Workers Rights (5):   International Labour Org News,
 *                                   Clean Clothes Campaign, IndustriALL Global,
 *                                   Equal Times, Labor Notes US
 *   - Space & Astronomy (5):        SpaceNews, Space.com, The Planetary Society,
 *                                   Ars Technica Space, Universe Today
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── East Africa Depth ─────────────────────────────────────────────────────
    {
      slug:            'the-east-african-ke',
      name:            'The East African',
      description:     'Pan-East African weekly covering Kenya, Uganda, Tanzania, Rwanda, Burundi, and DRC regional affairs',
      url:             'https://www.theeastafrican.co.ke',
      tier:            'major',
      trust_score:     0.80,
      language:        'en',
      country:         'KE',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.theeastafrican.co.ke/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'daily-monitor-ug-2',
      name:            'Daily Monitor Uganda',
      description:     'Uganda\'s leading independent daily covering Great Lakes politics, governance, and conflict',
      url:             'https://www.monitor.co.ug',
      tier:            'major',
      trust_score:     0.77,
      language:        'en',
      country:         'UG',
      categories:      JSON.stringify(['politics', 'breaking', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.monitor.co.ug/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'citizen-tz-business',
      name:            'The Citizen Tanzania Business',
      description:     'Tanzania business and economic coverage from The Citizen\'s dedicated business desk',
      url:             'https://www.thecitizen.co.tz',
      tier:            'specialised',
      trust_score:     0.74,
      language:        'en',
      country:         'TZ',
      categories:      JSON.stringify(['economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.thecitizen.co.tz/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'business-daily-ke',
      name:            'Business Daily Kenya',
      description:     'Kenya\'s premier business newspaper covering East African markets, fintech, and trade',
      url:             'https://www.businessdailyafrica.com',
      tier:            'major',
      trust_score:     0.79,
      language:        'en',
      country:         'KE',
      categories:      JSON.stringify(['economy', 'technology', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.businessdailyafrica.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'new-times-rw-en',
      name:            'The New Times Rwanda',
      description:     'Rwanda\'s English-language daily covering development, governance, and Great Lakes diplomacy',
      url:             'https://www.newtimes.co.rw',
      tier:            'specialised',
      trust_score:     0.72,
      language:        'en',
      country:         'RW',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.newtimes.co.rw/rss']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Central & Eastern Europe ──────────────────────────────────────────────
    {
      slug:            'novinky-cz',
      name:            'Novinky.cz',
      description:     'Czech Republic\'s most-visited news portal covering domestic politics, EU affairs, and culture',
      url:             'https://www.novinky.cz',
      tier:            'major',
      trust_score:     0.78,
      language:        'cs',
      country:         'CZ',
      categories:      JSON.stringify(['politics', 'breaking', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.novinky.cz/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'tvn24-pl',
      name:            'TVN24',
      description:     'Poland\'s leading 24-hour TV news channel and digital outlet covering Polish and EU politics',
      url:             'https://tvn24.pl',
      tier:            'major',
      trust_score:     0.80,
      language:        'pl',
      country:         'PL',
      categories:      JSON.stringify(['politics', 'breaking', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://tvn24.pl/najwazniejsze.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'index-hr',
      name:            'Index.hr',
      description:     'Croatia\'s most-read online news portal covering Balkan politics, EU integration, and society',
      url:             'https://www.index.hr',
      tier:            'major',
      trust_score:     0.76,
      language:        'hr',
      country:         'HR',
      categories:      JSON.stringify(['politics', 'breaking', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.index.hr/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'novaya-gazeta-europe',
      name:            'Novaya Gazeta Europe',
      description:     'Independent Russian investigative journalism in exile, covering Kremlin politics, war, and civil society',
      url:             'https://novayagazeta.eu',
      tier:            'premium',
      trust_score:     0.85,
      language:        'en',
      country:         'LV',
      categories:      JSON.stringify(['politics', 'conflict', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://novayagazeta.eu/rss/en']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'balkan-insight-mk',
      name:            'Balkan Insight BIRN',
      description:     'Investigative journalism network covering Western Balkans governance, corruption, and EU accession',
      url:             'https://balkaninsight.com',
      tier:            'premium',
      trust_score:     0.86,
      language:        'en',
      country:         'RS',
      categories:      JSON.stringify(['politics', 'conflict', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://balkaninsight.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Middle East Depth ─────────────────────────────────────────────────────
    {
      slug:            'the-national-ae',
      name:            'The National UAE',
      description:     'Abu Dhabi-based English broadsheet covering Gulf politics, energy, and Middle East diplomacy',
      url:             'https://www.thenationalnews.com',
      tier:            'major',
      trust_score:     0.79,
      language:        'en',
      country:         'AE',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.thenationalnews.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'lorient-le-jour-lb',
      name:            'L\'Orient Le Jour',
      description:     'Lebanon\'s French-language newspaper of record covering Lebanese politics, Hezbollah, and Levantine affairs',
      url:             'https://www.lorientlejour.com',
      tier:            'premium',
      trust_score:     0.83,
      language:        'fr',
      country:         'LB',
      categories:      JSON.stringify(['politics', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.lorientlejour.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'middle-east-eye-gb',
      name:            'Middle East Eye',
      description:     'London-based independent news covering Middle East and North Africa politics, conflict, and human rights',
      url:             'https://www.middleeasteye.net',
      tier:            'major',
      trust_score:     0.77,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['politics', 'conflict', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.middleeasteye.net/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            '972-magazine-il',
      name:            '+972 Magazine',
      description:     'Independent Israeli-Palestinian journalism covering occupation, human rights, and Israeli society',
      url:             'https://www.972mag.com',
      tier:            'specialised',
      trust_score:     0.76,
      language:        'en',
      country:         'IL',
      categories:      JSON.stringify(['politics', 'conflict', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.972mag.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'ammon-news-jo',
      name:            'Ammon News',
      description:     'Jordan\'s leading independent news agency covering Hashemite Kingdom politics and regional diplomacy',
      url:             'https://en.ammonnews.net',
      tier:            'specialised',
      trust_score:     0.73,
      language:        'en',
      country:         'JO',
      categories:      JSON.stringify(['politics', 'breaking', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://en.ammonnews.net/rss']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Oceania & Pacific Islands ─────────────────────────────────────────────
    {
      slug:            'fiji-times-fj',
      name:            'The Fiji Times',
      description:     'Fiji\'s oldest newspaper covering Pacific Island politics, climate vulnerability, and regional diplomacy',
      url:             'https://www.fijitimes.com.fj',
      tier:            'specialised',
      trust_score:     0.74,
      language:        'en',
      country:         'FJ',
      categories:      JSON.stringify(['politics', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.fijitimes.com.fj/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'samoa-observer-ws',
      name:            'Samoa Observer',
      description:     'Samoa\'s independent daily covering Pacific politics, climate adaptation, and Polynesian affairs',
      url:             'https://www.samoaobserver.ws',
      tier:            'specialised',
      trust_score:     0.71,
      language:        'en',
      country:         'WS',
      categories:      JSON.stringify(['politics', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.samoaobserver.ws/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'post-courier-pg',
      name:            'Post-Courier',
      description:     'Papua New Guinea\'s leading daily covering Melanesian politics, mining, and development',
      url:             'https://www.postcourier.com.pg',
      tier:            'specialised',
      trust_score:     0.72,
      language:        'en',
      country:         'PG',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.postcourier.com.pg/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'solomon-star-sb',
      name:            'Solomon Star',
      description:     'Solomon Islands\' main newspaper covering Pacific security, Chinese influence, and island governance',
      url:             'https://www.solomonstarnews.com',
      tier:            'specialised',
      trust_score:     0.70,
      language:        'en',
      country:         'SB',
      categories:      JSON.stringify(['politics', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.solomonstarnews.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'vanuatu-daily-post-vu',
      name:            'Vanuatu Daily Post',
      description:     'Vanuatu\'s leading daily covering Pacific climate policy, development, and Melanesian affairs',
      url:             'https://www.dailypost.vu',
      tier:            'specialised',
      trust_score:     0.70,
      language:        'en',
      country:         'VU',
      categories:      JSON.stringify(['politics', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.dailypost.vu/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Water & Sanitation ────────────────────────────────────────────────────
    {
      slug:            'circle-of-blue-us',
      name:            'Circle of Blue',
      description:     'Award-winning water news organization reporting on global water crises, infrastructure, and policy',
      url:             'https://www.circleofblue.org',
      tier:            'premium',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['climate', 'health', 'science']),
      rss_feeds:       JSON.stringify(['https://www.circleofblue.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'wateraid-gb',
      name:            'WaterAid News',
      description:     'International NGO covering water, sanitation, and hygiene access in developing nations',
      url:             'https://www.wateraid.org',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['health', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.wateraid.org/news/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'the-water-network',
      name:            'The Water Network',
      description:     'Global water sector intelligence covering utilities, desalination, and water technology innovation',
      url:             'https://thewaternetwork.com',
      tier:            'specialised',
      trust_score:     0.74,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology', 'climate']),
      rss_feeds:       JSON.stringify(['https://thewaternetwork.com/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'wash-matters-gb',
      name:            'WASH Matters',
      description:     'WaterAid\'s policy blog on water, sanitation, and hygiene programs globally',
      url:             'https://washmatters.wateraid.org',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['health', 'science', 'climate']),
      rss_feeds:       JSON.stringify(['https://washmatters.wateraid.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'iwa-publishing',
      name:            'International Water Association',
      description:     'Global water sector professional network covering research, policy, and technology',
      url:             'https://iwa-network.org',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['science', 'climate', 'health']),
      rss_feeds:       JSON.stringify(['https://iwa-network.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Nuclear & Energy Security ─────────────────────────────────────────────
    {
      slug:            'world-nuclear-news',
      name:            'World Nuclear News',
      description:     'Official World Nuclear Association outlet covering nuclear energy, non-proliferation, and safety worldwide',
      url:             'https://world-nuclear-news.org',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['science', 'security', 'economy']),
      rss_feeds:       JSON.stringify(['https://world-nuclear-news.org/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'bulletin-atomic-scientists',
      name:            'Bulletin of the Atomic Scientists',
      description:     'Doomsday Clock publisher covering nuclear threats, biosecurity, climate, and disruptive technologies',
      url:             'https://thebulletin.org',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'science', 'geopolitics', 'climate']),
      rss_feeds:       JSON.stringify(['https://thebulletin.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'nti-news',
      name:            'Nuclear Threat Initiative',
      description:     'NTI analysis on nuclear, biological, chemical, and radiological threats and arms control',
      url:             'https://www.nti.org',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.nti.org/rss/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'energy-intelligence',
      name:            'Energy Intelligence',
      description:     'Premium energy market intelligence covering oil, gas, nuclear, and renewables policy',
      url:             'https://www.energyintel.com',
      tier:            'premium',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'science', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.energyintel.com/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'platts-energy-news',
      name:            'S&P Global Platts Energy',
      description:     'S&P Global commodity intelligence covering energy prices, infrastructure, and transition',
      url:             'https://www.spglobal.com/commodityinsights',
      tier:            'premium',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'science']),
      rss_feeds:       JSON.stringify(['https://www.spglobal.com/commodityinsights/rss']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Humanitarian & Aid ────────────────────────────────────────────────────
    {
      slug:            'reliefweb-ocha',
      name:            'ReliefWeb (OCHA)',
      description:     'UN OCHA\'s humanitarian information portal — the gold standard for disaster and crisis reporting',
      url:             'https://reliefweb.int',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['conflict', 'climate', 'health', 'breaking']),
      rss_feeds:       JSON.stringify(['https://reliefweb.int/updates/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-new-humanitarian-2',
      name:            'The New Humanitarian',
      description:     'Former IRIN News — independent humanitarian journalism covering conflict, displacement, and aid',
      url:             'https://www.thenewhumanitarian.org',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['conflict', 'health', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.thenewhumanitarian.org/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'devex-development',
      name:            'Devex',
      description:     'Global development news covering aid, funding, and international development policy',
      url:             'https://www.devex.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'health', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.devex.com/news/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'hpn-odi',
      name:            'Humanitarian Practice Network',
      description:     'ODI\'s humanitarian policy network covering aid effectiveness, protection, and crisis response',
      url:             'https://odihpn.org',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['conflict', 'health']),
      rss_feeds:       JSON.stringify(['https://odihpn.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'global-voices-online',
      name:            'Global Voices',
      description:     'Citizen media network amplifying underrepresented voices from 167+ countries in 50+ languages',
      url:             'https://globalvoices.org',
      tier:            'major',
      trust_score:     0.79,
      language:        'en',
      country:         'NL',
      categories:      JSON.stringify(['politics', 'technology', 'breaking']),
      rss_feeds:       JSON.stringify(['https://globalvoices.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Digital Rights & Privacy ──────────────────────────────────────────────
    {
      slug:            'access-now',
      name:            'Access Now',
      description:     'Digital rights organization covering internet shutdowns, surveillance, and digital freedom globally',
      url:             'https://www.accessnow.org',
      tier:            'premium',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.accessnow.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'eff-deeplinks',
      name:            'EFF Deeplinks Blog',
      description:     'Electronic Frontier Foundation\'s analysis of digital privacy, free speech, and innovation policy',
      url:             'https://www.eff.org/deeplinks',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.eff.org/rss/updates.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'rest-of-world',
      name:            'Rest of World',
      description:     'Technology\'s impact outside the Western bubble — covering emerging markets, digital economies, and platform governance',
      url:             'https://restofworld.org',
      tier:            'major',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://restofworld.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'ranking-digital-rights',
      name:            'Ranking Digital Rights',
      description:     'Corporate accountability rankings for Big Tech on freedom of expression and privacy',
      url:             'https://rankingdigitalrights.org',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'politics']),
      rss_feeds:       JSON.stringify(['https://rankingdigitalrights.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'digital-rights-foundation-pk',
      name:            'Digital Rights Foundation',
      description:     'Pakistan-based digital rights org covering South Asian internet freedom, online harassment, and data protection',
      url:             'https://digitalrightsfoundation.pk',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'PK',
      categories:      JSON.stringify(['technology', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://digitalrightsfoundation.pk/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Labor & Workers Rights ────────────────────────────────────────────────
    {
      slug:            'ilo-news',
      name:            'International Labour Organization News',
      description:     'UN ILO coverage of global labor standards, worker rights, supply chains, and employment trends',
      url:             'https://www.ilo.org',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['economy', 'politics', 'health']),
      rss_feeds:       JSON.stringify(['https://www.ilo.org/rss/news.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'clean-clothes-campaign',
      name:            'Clean Clothes Campaign',
      description:     'Global garment industry watchdog covering supply chain abuses, living wages, and factory safety',
      url:             'https://cleanclothes.org',
      tier:            'specialised',
      trust_score:     0.79,
      language:        'en',
      country:         'NL',
      categories:      JSON.stringify(['economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://cleanclothes.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'industriall-global',
      name:            'IndustriALL Global Union',
      description:     'Global union federation covering manufacturing, mining, and energy worker rights in 140 countries',
      url:             'https://www.industriall-union.org',
      tier:            'specialised',
      trust_score:     0.77,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.industriall-union.org/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'equal-times',
      name:            'Equal Times',
      description:     'Trilingual labor and social justice journalism covering workers rights, trade, and inequality',
      url:             'https://www.equaltimes.org',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['economy', 'politics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.equaltimes.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'labor-notes-us',
      name:            'Labor Notes',
      description:     'US labor movement journalism covering strikes, organizing, and union strategy',
      url:             'https://labornotes.org',
      tier:            'specialised',
      trust_score:     0.76,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://labornotes.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Space & Astronomy ─────────────────────────────────────────────────────
    {
      slug:            'spacenews',
      name:            'SpaceNews',
      description:     'Leading space industry publication covering launch markets, satellite, defense space, and civil space policy',
      url:             'https://spacenews.com',
      tier:            'major',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology', 'security']),
      rss_feeds:       JSON.stringify(['https://spacenews.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'space-com',
      name:            'Space.com',
      description:     'Astronomy and space exploration coverage including missions, discoveries, and commercial space',
      url:             'https://www.space.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.space.com/feeds/all']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'planetary-society',
      name:            'The Planetary Society',
      description:     'Carl Sagan-founded space advocacy org covering planetary science, exploration, and space policy',
      url:             'https://www.planetary.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.planetary.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'ars-technica-space',
      name:            'Ars Technica Space',
      description:     'In-depth space and rocket science coverage from Ars Technica\'s dedicated space desk',
      url:             'https://arstechnica.com/space/',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology']),
      rss_feeds:       JSON.stringify(['https://feeds.arstechnica.com/arstechnica/science']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'universe-today',
      name:            'Universe Today',
      description:     'Space and astronomy news covering discoveries, missions, and astrophysics for general audiences',
      url:             'https://www.universetoday.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'CA',
      categories:      JSON.stringify(['science', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.universetoday.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex.raw(
      `INSERT INTO sources (slug, name, description, url, tier, trust_score, language, country, categories, rss_feeds, scrape_interval, active, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?::jsonb, ?::jsonb, ?, ?, NOW(), NOW())
       ON CONFLICT (slug) DO NOTHING`,
      [
        source.slug,
        source.name,
        source.description,
        source.url,
        source.tier,
        source.trust_score,
        source.language,
        source.country,
        source.categories,
        source.rss_feeds,
        source.scrape_interval,
        source.active,
      ]
    )
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'the-east-african-ke', 'daily-monitor-ug-2', 'citizen-tz-business',
    'business-daily-ke', 'new-times-rw-en',
    'novinky-cz', 'tvn24-pl', 'index-hr', 'novaya-gazeta-europe', 'balkan-insight-mk',
    'the-national-ae', 'lorient-le-jour-lb', 'middle-east-eye-gb', '972-magazine-il', 'ammon-news-jo',
    'fiji-times-fj', 'samoa-observer-ws', 'post-courier-pg', 'solomon-star-sb', 'vanuatu-daily-post-vu',
    'circle-of-blue-us', 'wateraid-gb', 'the-water-network', 'wash-matters-gb', 'iwa-publishing',
    'world-nuclear-news', 'bulletin-atomic-scientists', 'nti-news', 'energy-intelligence', 'platts-energy-news',
    'reliefweb-ocha', 'the-new-humanitarian-2', 'devex-development', 'hpn-odi', 'global-voices-online',
    'access-now', 'eff-deeplinks', 'rest-of-world', 'ranking-digital-rights', 'digital-rights-foundation-pk',
    'ilo-news', 'clean-clothes-campaign', 'industriall-global', 'equal-times', 'labor-notes-us',
    'spacenews', 'space-com', 'planetary-society', 'ars-technica-space', 'universe-today',
  ]
  await knex('sources').whereIn('slug', slugs).del()
}
