import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  // Only seed if no sources exist
  const existing = await knex('sources').count('id as count').first()
  if (Number(existing?.count ?? 0) > 0) return

  await knex('sources').insert([
    {
      slug: 'ap-news',
      name: 'AP News',
      description: 'The Associated Press — global wire service',
      url: 'https://apnews.com',
      tier: 'wire',
      trust_score: 0.97,
      language: 'en',
      country: 'US',
      categories: ['breaking', 'geopolitics', 'economy', 'health', 'science'],
      rss_feeds: ['https://feeds.apnews.com/rss/apf-topnews', 'https://feeds.apnews.com/rss/apf-intlnews', 'https://feeds.apnews.com/rss/apf-WorldNews'],
      scrape_interval: 300,
      active: true,
    },
    {
      slug: 'reuters',
      name: 'Reuters',
      description: 'Reuters — international wire service',
      url: 'https://reuters.com',
      tier: 'wire',
      trust_score: 0.96,
      language: 'en',
      country: 'GB',
      categories: ['breaking', 'economy', 'geopolitics', 'technology'],
      rss_feeds: ['https://feeds.reuters.com/reuters/topNews', 'https://feeds.reuters.com/Reuters/worldNews', 'https://feeds.reuters.com/reuters/businessNews'],
      scrape_interval: 300,
      active: true,
    },
    {
      slug: 'bbc-world',
      name: 'BBC World',
      description: 'BBC World Service — global news',
      url: 'https://www.bbc.com/news/world',
      tier: 'wire',
      trust_score: 0.95,
      language: 'en',
      country: 'GB',
      categories: ['breaking', 'geopolitics', 'culture', 'science', 'health'],
      rss_feeds: ['https://feeds.bbci.co.uk/news/world/rss.xml', 'https://feeds.bbci.co.uk/news/rss.xml', 'https://feeds.bbci.co.uk/news/world/rss.xml'],
      scrape_interval: 300,
      active: true,
    },
    {
      slug: 'al-jazeera',
      name: 'Al Jazeera',
      description: 'Al Jazeera — Middle East and global news',
      url: 'https://aljazeera.com',
      tier: 'national',
      trust_score: 0.88,
      language: 'en',
      country: 'QA',
      categories: ['geopolitics', 'conflict', 'culture', 'economy'],
      rss_feeds: ['https://www.aljazeera.com/xml/rss/all.xml'],
      scrape_interval: 600,
      active: true,
    },
    {
      slug: 'guardian',
      name: 'The Guardian',
      description: 'The Guardian — UK national newspaper',
      url: 'https://theguardian.com',
      tier: 'national',
      trust_score: 0.87,
      language: 'en',
      country: 'GB',
      categories: ['climate', 'science', 'geopolitics', 'culture', 'technology'],
      rss_feeds: ['https://www.theguardian.com/world/rss', 'https://www.theguardian.com/environment/climate-crisis/rss', 'https://www.theguardian.com/technology/rss'],
      scrape_interval: 600,
      active: true,
    },
    {
      slug: 'who',
      name: 'WHO',
      description: 'World Health Organization — official health alerts',
      url: 'https://who.int',
      tier: 'wire',
      trust_score: 0.98,
      language: 'en',
      country: null,
      categories: ['health'],
      rss_feeds: ['https://www.who.int/rss-feeds/news-english.xml'],
      scrape_interval: 900,
      active: true,
    },
    {
      slug: 'usgs-earthquakes',
      name: 'USGS Earthquakes',
      description: 'United States Geological Survey — seismic events',
      url: 'https://earthquake.usgs.gov',
      tier: 'wire',
      trust_score: 0.99,
      language: 'en',
      country: 'US',
      categories: ['disaster'],
      rss_feeds: ['https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_hour.atom', 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.atom'],
      scrape_interval: 300,
      active: true,
    },
    {
      slug: 'france24',
      name: 'France 24',
      description: 'France 24 — international news channel',
      url: 'https://france24.com',
      tier: 'national',
      trust_score: 0.89,
      language: 'en',
      country: 'FR',
      categories: ['geopolitics', 'breaking', 'economy', 'culture'],
      rss_feeds: ['https://www.france24.com/en/rss'],
      scrape_interval: 600,
      active: true,
    },
    {
      slug: 'dw-world',
      name: 'Deutsche Welle',
      description: 'DW — German international broadcaster',
      url: 'https://dw.com',
      tier: 'national',
      trust_score: 0.90,
      language: 'en',
      country: 'DE',
      categories: ['geopolitics', 'economy', 'science', 'culture'],
      rss_feeds: ['https://rss.dw.com/rdf/rss-en-all'],
      scrape_interval: 600,
      active: true,
    },
    {
      slug: 'nasa',
      name: 'NASA',
      description: 'NASA — space and science news',
      url: 'https://nasa.gov',
      tier: 'wire',
      trust_score: 0.98,
      language: 'en',
      country: 'US',
      categories: ['space', 'science'],
      rss_feeds: ['https://www.nasa.gov/news-release/feed/'],
      scrape_interval: 1800,
      active: true,
    },
  ])
}

export async function down(knex: Knex): Promise<void> {
  await knex('sources').whereIn('slug', [
    'ap-news', 'reuters', 'bbc-world', 'al-jazeera', 'guardian',
    'who', 'usgs-earthquakes', 'france24', 'dw-world', 'nasa',
  ]).delete()
}
