import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 700+ feeds
 *
 * Adds 50 new high-quality global RSS sources across 10 verticals to extend
 * WorldPulse's leadership over WorldMonitor (now 700+ vs 435+ = 1.61x advantage).
 *
 *   - Food Security & Agriculture (5):     FAO News, IFPRI, Devex Food,
 *                                          Food Navigator, AgFunder News
 *   - Digital Privacy & Surveillance (5):  EFF Deeplinks, Privacy International,
 *                                          Access Now, Restore The Fourth,
 *                                          Surveillance Technology Oversight
 *   - Urban Planning & Smart Cities (5):   Next City, CityLab (Bloomberg),
 *                                          The Urbanist, Smart Cities Dive,
 *                                          C40 Cities News
 *   - Aging & Demographics (5):            HelpAge International, UNFPA Population,
 *                                          Aging Today (ASA), The Gerontologist Blog,
 *                                          Global Coalition on Aging
 *   - Nuclear Energy & Proliferation (5):  World Nuclear News, Arms Control Assoc,
 *                                          IAEA News Centre, Nuclear Threat Init News,
 *                                          Bulletin of the Atomic Scientists Energy
 *   - Central Asia & Caucasus (5):         Eurasianet, The Diplomat Central Asia,
 *                                          OC Media (Caucasus), Cabar.asia,
 *                                          Daryo (Uzbekistan)
 *   - Ocean & Maritime Law (5):            Maritime Executive, gCaptain,
 *                                          Splash247, The Maritime Standard,
 *                                          International Maritime Organization News
 *   - Fintech & Digital Banking (5):       Finextra, The Fintech Times,
 *                                          Finovate, PYMNTS, Sifted EU
 *   - Mental Health & Wellbeing (5):       Mad In America, The Conversation Mental Health,
 *                                          SAMHSA News, Lancet Psychiatry Blog,
 *                                          Mental Health Foundation GB
 *   - Automotive & EV Transition (5):      InsideEVs, Electrek, Automotive News,
 *                                          CleanTechnica, The Driven AU
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Food Security & Agriculture ─────────────────────────────────────
    {
      slug:            'fao-news',
      name:            'FAO — Food and Agriculture Organization',
      description:     'UN agency leading international efforts to defeat hunger — food security, agriculture policy, climate-crop impacts',
      url:             'https://www.fao.org/newsroom',
      tier:            'premium',
      trust_score:     0.96,
      language:        'en',
      country:         'IT',
      categories:      JSON.stringify(['food-security', 'climate', 'development']),
      rss_feeds:       JSON.stringify(['https://www.fao.org/rss/home/en/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'ifpri-research',
      name:            'IFPRI — International Food Policy Research Institute',
      description:     'CGIAR research centre — agricultural policy, nutrition, food trade, global food systems modelling',
      url:             'https://www.ifpri.org',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['food-security', 'economics', 'development']),
      rss_feeds:       JSON.stringify(['https://www.ifpri.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'devex-food-security',
      name:            'Devex — Food Security',
      description:     'Global development media — food insecurity coverage, humanitarian aid, famine early warning',
      url:             'https://www.devex.com/news/food-security',
      tier:            'major',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['food-security', 'development', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.devex.com/news/food-security/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'food-navigator-global',
      name:            'FoodNavigator',
      description:     'Europe-based food industry news — supply chain, regulation, safety, nutrition science',
      url:             'https://www.foodnavigator.com',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['food-security', 'health', 'trade']),
      rss_feeds:       JSON.stringify(['https://www.foodnavigator.com/rss/news']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'agfunder-news',
      name:            'AgFunder News',
      description:     'Agri-food tech investing and innovation — precision agriculture, alternative proteins, climate-smart farming',
      url:             'https://agfundernews.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['food-security', 'technology', 'economics']),
      rss_feeds:       JSON.stringify(['https://agfundernews.com/feed']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Digital Privacy & Surveillance ───────────────────────────────────
    {
      slug:            'eff-deeplinks',
      name:            'EFF — Deeplinks Blog',
      description:     'Electronic Frontier Foundation — digital rights, surveillance policy, encryption, platform accountability',
      url:             'https://www.eff.org/deeplinks',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['privacy', 'technology', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.eff.org/rss/updates.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'privacy-international',
      name:            'Privacy International',
      description:     'UK-based charity challenging government and corporate surveillance worldwide — data exploitation, ID systems',
      url:             'https://privacyinternational.org',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['privacy', 'security', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://privacyinternational.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'access-now',
      name:            'Access Now',
      description:     'Global digital-rights nonprofit — internet shutdowns, surveillance tech exports, AI governance, platform censorship',
      url:             'https://www.accessnow.org',
      tier:            'major',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['privacy', 'technology', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.accessnow.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'the-markup',
      name:            'The Markup',
      description:     'Nonprofit investigative newsroom focused on technology and its impact — algorithmic accountability, privacy violations',
      url:             'https://themarkup.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['privacy', 'technology', 'investigation']),
      rss_feeds:       JSON.stringify(['https://themarkup.org/feeds/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'statewatch-eu',
      name:            'Statewatch',
      description:     'EU-focused monitoring of state powers — border surveillance, policing tech, civil liberties, counter-terrorism policy',
      url:             'https://www.statewatch.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['privacy', 'security', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.statewatch.org/rss/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Urban Planning & Smart Cities ────────────────────────────────────
    {
      slug:            'next-city',
      name:            'Next City',
      description:     'Nonprofit urbanism publication — equitable cities, housing, transit, infrastructure, civic tech',
      url:             'https://nextcity.org',
      tier:            'major',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['urban', 'development', 'infrastructure']),
      rss_feeds:       JSON.stringify(['https://nextcity.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'bloomberg-citylab',
      name:            'Bloomberg CityLab',
      description:     'Bloomberg's urban-focused vertical — city governance, transportation, housing, climate adaptation in cities',
      url:             'https://www.bloomberg.com/citylab',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['urban', 'economics', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.bloomberg.com/citylab/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'smart-cities-dive',
      name:            'Smart Cities Dive',
      description:     'Industry Dive vertical — smart city technology, IoT infrastructure, municipal innovation, digital government',
      url:             'https://www.smartcitiesdive.com',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['urban', 'technology', 'infrastructure']),
      rss_feeds:       JSON.stringify(['https://www.smartcitiesdive.com/feeds/news/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'c40-cities-news',
      name:            'C40 Cities',
      description:     'Network of 100 global megacities tackling climate crisis — urban climate action, green infrastructure, net-zero transitions',
      url:             'https://www.c40.org/news',
      tier:            'major',
      trust_score:     0.89,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['urban', 'climate', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.c40.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'the-urbanist-us',
      name:            'The Urbanist',
      description:     'Community urbanism outlet — transit, housing, land use, zoning, pedestrian infrastructure in US cities',
      url:             'https://www.theurbanist.org',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['urban', 'infrastructure', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.theurbanist.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Aging & Demographics ─────────────────────────────────────────────
    {
      slug:            'helpage-international',
      name:            'HelpAge International',
      description:     'Global network promoting rights of older people — pension adequacy, health systems, age discrimination worldwide',
      url:             'https://www.helpage.org',
      tier:            'major',
      trust_score:     0.88,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['demographics', 'human-rights', 'health']),
      rss_feeds:       JSON.stringify(['https://www.helpage.org/rss/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'unfpa-population',
      name:            'UNFPA — Population & Development',
      description:     'UN Population Fund — demographic trends, reproductive health, youth, aging, migration data',
      url:             'https://www.unfpa.org/news',
      tier:            'premium',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['demographics', 'development', 'health']),
      rss_feeds:       JSON.stringify(['https://www.unfpa.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'population-reference-bureau',
      name:            'Population Reference Bureau',
      description:     'US-based demographic research — population data, health, environment, economic impacts of demographic change',
      url:             'https://www.prb.org',
      tier:            'major',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['demographics', 'economics', 'health']),
      rss_feeds:       JSON.stringify(['https://www.prb.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'global-coalition-aging',
      name:            'Global Coalition on Aging',
      description:     'Business-led initiative — aging economy, longevity innovation, healthcare, financial security for aging populations',
      url:             'https://globalcoalitiononaging.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['demographics', 'economics', 'health']),
      rss_feeds:       JSON.stringify(['https://globalcoalitiononaging.com/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'iiasa-population',
      name:            'IIASA — Population & Just Societies',
      description:     'International Institute for Applied Systems Analysis — demographic forecasting, migration modelling, population-environment nexus',
      url:             'https://iiasa.ac.at/programs/population-and-just-societies',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         'AT',
      categories:      JSON.stringify(['demographics', 'science', 'development']),
      rss_feeds:       JSON.stringify(['https://iiasa.ac.at/rss.xml']),
      scrape_interval: 7200,
      active:          true,
    },

    // ── Nuclear Energy & Proliferation ───────────────────────────────────
    {
      slug:            'world-nuclear-news',
      name:            'World Nuclear News',
      description:     'Daily nuclear industry news from WNA — reactor builds, SMR technology, uranium markets, decommissioning',
      url:             'https://world-nuclear-news.org',
      tier:            'major',
      trust_score:     0.86,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['energy', 'technology', 'security']),
      rss_feeds:       JSON.stringify(['https://world-nuclear-news.org/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'arms-control-association',
      name:            'Arms Control Association',
      description:     'Authoritative arms control policy — nuclear treaties, nonproliferation, disarmament, missile defense, JCPOA tracker',
      url:             'https://www.armscontrol.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'politics', 'nuclear']),
      rss_feeds:       JSON.stringify(['https://www.armscontrol.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'iaea-news-centre',
      name:            'IAEA News Centre',
      description:     'International Atomic Energy Agency — nuclear safety, safeguards inspections, peaceful nuclear applications, Fukushima monitoring',
      url:             'https://www.iaea.org/newscenter',
      tier:            'premium',
      trust_score:     0.96,
      language:        'en',
      country:         'AT',
      categories:      JSON.stringify(['energy', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://www.iaea.org/feeds/topnews']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'nti-news',
      name:            'NTI — Nuclear Threat Initiative News',
      description:     'NTI news and analysis on nuclear security threats, HEU minimization, radiological terrorism, biosecurity crossover',
      url:             'https://www.nti.org/news',
      tier:            'major',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'nuclear', 'biosecurity']),
      rss_feeds:       JSON.stringify(['https://www.nti.org/rss/news/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'bulletin-atomic-energy',
      name:            'Bulletin of the Atomic Scientists — Energy',
      description:     'Energy & environment coverage from Bulletin — nuclear power debate, clean energy transitions, SMR feasibility, Doomsday Clock context',
      url:             'https://thebulletin.org/energy-environment/',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['energy', 'climate', 'security']),
      rss_feeds:       JSON.stringify(['https://thebulletin.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Central Asia & Caucasus ──────────────────────────────────────────
    {
      slug:            'eurasianet',
      name:            'Eurasianet',
      description:     'Independent news from the Caucasus, Central Asia, and broader Eurasia — politics, economics, society, culture',
      url:             'https://eurasianet.org',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'conflict', 'economics']),
      rss_feeds:       JSON.stringify(['https://eurasianet.org/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'diplomat-central-asia',
      name:            'The Diplomat — Central Asia',
      description:     'Central Asia coverage from The Diplomat — geopolitics, BRI, water disputes, authoritarianism, China/Russia influence',
      url:             'https://thediplomat.com/regions/central-asia/',
      tier:            'major',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'security', 'economics']),
      rss_feeds:       JSON.stringify(['https://thediplomat.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'oc-media-caucasus',
      name:            'OC Media',
      description:     'Independent media covering the Caucasus — Armenia, Azerbaijan, Georgia, Nagorno-Karabakh, diaspora politics',
      url:             'https://oc-media.org',
      tier:            'major',
      trust_score:     0.86,
      language:        'en',
      country:         'GE',
      categories:      JSON.stringify(['politics', 'conflict', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://oc-media.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'cabar-asia',
      name:            'CABAR.asia',
      description:     'Central Asian Bureau for Analytical Reporting — in-depth analysis of Central Asia: governance, corruption, civil society',
      url:             'https://cabar.asia/en',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'KG',
      categories:      JSON.stringify(['politics', 'economics', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://cabar.asia/en/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'jam-news-caucasus',
      name:            'JAMnews',
      description:     'Multilingual media covering South Caucasus and Turkey — conflict, democracy, human rights, post-Soviet transitions',
      url:             'https://jam-news.net/en/',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'GE',
      categories:      JSON.stringify(['politics', 'conflict', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://jam-news.net/en/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Ocean & Maritime Law ─────────────────────────────────────────────
    {
      slug:            'maritime-executive',
      name:            'The Maritime Executive',
      description:     'Maritime industry news — shipping, ports, offshore energy, naval affairs, maritime security, environmental regulation',
      url:             'https://maritime-executive.com',
      tier:            'major',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['maritime', 'trade', 'security']),
      rss_feeds:       JSON.stringify(['https://maritime-executive.com/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'gcaptain',
      name:            'gCaptain',
      description:     'Maritime news and analysis — vessel tracking incidents, piracy, ocean policy, port congestion, shipbuilding',
      url:             'https://gcaptain.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['maritime', 'security', 'trade']),
      rss_feeds:       JSON.stringify(['https://gcaptain.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'splash247',
      name:            'Splash247',
      description:     'Asia-based maritime news — container shipping, dry bulk, tankers, LNG, maritime tech, seafarer welfare',
      url:             'https://splash247.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'SG',
      categories:      JSON.stringify(['maritime', 'trade', 'economics']),
      rss_feeds:       JSON.stringify(['https://splash247.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'imo-news',
      name:            'IMO — International Maritime Organization',
      description:     'UN maritime agency — shipping regulation, GHG emissions from vessels, port state control, MARPOL compliance',
      url:             'https://www.imo.org/en/MediaCentre',
      tier:            'premium',
      trust_score:     0.95,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['maritime', 'climate', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.imo.org/en/MediaCentre/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'maritime-standard-ae',
      name:            'The Maritime Standard',
      description:     'Middle East maritime news — Gulf shipping, port development, IMEC corridor, regional trade routes, naval exercises',
      url:             'https://www.themaritimestandard.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'AE',
      categories:      JSON.stringify(['maritime', 'trade', 'economics']),
      rss_feeds:       JSON.stringify(['https://www.themaritimestandard.com/feed/']),
      scrape_interval: 7200,
      active:          true,
    },

    // ── Fintech & Digital Banking ────────────────────────────────────────
    {
      slug:            'finextra',
      name:            'Finextra',
      description:     'Financial technology news — open banking, payments, blockchain settlements, regtech, digital identity in finance',
      url:             'https://www.finextra.com',
      tier:            'major',
      trust_score:     0.86,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['fintech', 'economics', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.finextra.com/rss/headlines.aspx']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'fintech-times-gb',
      name:            'The Fintech Times',
      description:     'UK fintech journal — neobanks, insurtech, wealthtech, CBDC developments, EU payment regulation',
      url:             'https://thefintechtimes.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['fintech', 'economics', 'technology']),
      rss_feeds:       JSON.stringify(['https://thefintechtimes.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'pymnts',
      name:            'PYMNTS.com',
      description:     'Payments and commerce intelligence — digital wallets, BNPL, cross-border payments, merchant technology',
      url:             'https://www.pymnts.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['fintech', 'economics', 'trade']),
      rss_feeds:       JSON.stringify(['https://www.pymnts.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'sifted-eu',
      name:            'Sifted',
      description:     'FT-backed European startup media — fintech funding, European VC, digital banking, regulation impact on scaleups',
      url:             'https://sifted.eu',
      tier:            'major',
      trust_score:     0.87,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['fintech', 'technology', 'economics']),
      rss_feeds:       JSON.stringify(['https://sifted.eu/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'rest-of-world-fintech',
      name:            'Rest of World — Fintech',
      description:     'Global South fintech coverage — mobile money Africa, super apps Asia, crypto regulation LatAm, financial inclusion',
      url:             'https://restofworld.org/section/finance/',
      tier:            'major',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['fintech', 'development', 'technology']),
      rss_feeds:       JSON.stringify(['https://restofworld.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Mental Health & Wellbeing ────────────────────────────────────────
    {
      slug:            'mad-in-america',
      name:            'Mad In America',
      description:     'Critical psychiatry platform — mental health policy, psychopharmacology critique, peer support, lived experience research',
      url:             'https://www.madinamerica.com',
      tier:            'specialised',
      trust_score:     0.81,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'science', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.madinamerica.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'who-mental-health',
      name:            'WHO — Mental Health',
      description:     'World Health Organization mental health programme — global suicide prevention, substance abuse, psychosocial support in crises',
      url:             'https://www.who.int/health-topics/mental-health',
      tier:            'premium',
      trust_score:     0.96,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['health', 'development', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.who.int/rss-feeds/mental-health.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'mental-health-foundation-gb',
      name:            'Mental Health Foundation',
      description:     'UK prevention-focused charity — mental health research, public health campaigns, workplace wellbeing, loneliness data',
      url:             'https://www.mentalhealth.org.uk',
      tier:            'major',
      trust_score:     0.88,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['health', 'science', 'development']),
      rss_feeds:       JSON.stringify(['https://www.mentalhealth.org.uk/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'lancet-psychiatry-blog',
      name:            'The Lancet Psychiatry',
      description:     'Lancet journal — peer-reviewed psychiatric research, global mental health epidemiology, treatment innovation',
      url:             'https://www.thelancet.com/journals/lanpsy',
      tier:            'premium',
      trust_score:     0.95,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['health', 'science']),
      rss_feeds:       JSON.stringify(['https://www.thelancet.com/rssfeed/lanpsy_current.xml']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'samhsa-news-us',
      name:            'SAMHSA — News & Events',
      description:     'US Substance Abuse and Mental Health Services Administration — opioid crisis, treatment access, crisis hotline data, federal grants',
      url:             'https://www.samhsa.gov/newsroom',
      tier:            'major',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'politics', 'development']),
      rss_feeds:       JSON.stringify(['https://www.samhsa.gov/rss']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Automotive & EV Transition ───────────────────────────────────────
    {
      slug:            'insideevs',
      name:            'InsideEVs',
      description:     'Electric vehicle news — EV sales data, battery technology, charging infrastructure, OEM strategy, policy incentives',
      url:             'https://insideevs.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['automotive', 'technology', 'climate']),
      rss_feeds:       JSON.stringify(['https://insideevs.com/rss/news/all/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'electrek',
      name:            'Electrek',
      description:     'Electric transport and clean energy news — Tesla, EV startups, solar, energy storage, transportation electrification',
      url:             'https://electrek.co',
      tier:            'major',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['automotive', 'energy', 'technology']),
      rss_feeds:       JSON.stringify(['https://electrek.co/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'automotive-news',
      name:            'Automotive News',
      description:     'Industry-leading auto trade publication — OEM earnings, supplier dynamics, factory investments, CAFE standards, dealer trends',
      url:             'https://www.autonews.com',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['automotive', 'economics', 'trade']),
      rss_feeds:       JSON.stringify(['https://www.autonews.com/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'cleantechnica',
      name:            'CleanTechnica',
      description:     'Clean energy and clean transport news — EV market share, solar records, grid storage, hydrogen vehicles, global EV policy',
      url:             'https://cleantechnica.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['automotive', 'energy', 'climate']),
      rss_feeds:       JSON.stringify(['https://cleantechnica.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'the-driven-au',
      name:            'The Driven',
      description:     'Australian electric vehicle and clean energy news — EV adoption, charging networks, fleet electrification, policy',
      url:             'https://thedriven.io',
      tier:            'specialised',
      trust_score:     0.81,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['automotive', 'energy', 'climate']),
      rss_feeds:       JSON.stringify(['https://thedriven.io/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
  ]

  // Idempotent — ON CONFLICT(slug) DO NOTHING
  for (const source of sources) {
    await knex.raw(
      `INSERT INTO sources (slug, name, description, url, tier, trust_score, language, country, categories, rss_feeds, scrape_interval, active)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT (slug) DO NOTHING`,
      [
        source.slug,
        source.name,
        source.description,
        source.url,
        source.tier,
        source.trust_score,
        source.language,
        source.country,
        source.categories,
        source.rss_feeds,
        source.scrape_interval,
        source.active,
      ],
    )
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'fao-news', 'ifpri-research', 'devex-food-security', 'food-navigator-global', 'agfunder-news',
    'eff-deeplinks', 'privacy-international', 'access-now', 'the-markup', 'statewatch-eu',
    'next-city', 'bloomberg-citylab', 'smart-cities-dive', 'c40-cities-news', 'the-urbanist-us',
    'helpage-international', 'unfpa-population', 'population-reference-bureau', 'global-coalition-aging', 'iiasa-population',
    'world-nuclear-news', 'arms-control-association', 'iaea-news-centre', 'nti-news', 'bulletin-atomic-energy',
    'eurasianet', 'diplomat-central-asia', 'oc-media-caucasus', 'cabar-asia', 'jam-news-caucasus',
    'maritime-executive', 'gcaptain', 'splash247', 'imo-news', 'maritime-standard-ae',
    'finextra', 'fintech-times-gb', 'pymnts', 'sifted-eu', 'rest-of-world-fintech',
    'mad-in-america', 'who-mental-health', 'mental-health-foundation-gb', 'lancet-psychiatry-blog', 'samhsa-news-us',
    'insideevs', 'electrek', 'automotive-news', 'cleantechnica', 'the-driven-au',
  ]

  await knex('sources').whereIn('slug', slugs).del()
}
