import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 600+ feeds
 *
 * Adds 50 new high-quality global RSS sources across 10 verticals to extend
 * WorldPulse's leadership over WorldMonitor (now 600+ vs 435+ = 1.38x advantage).
 *
 *   - Investigative Journalism (5):     ICIJ, Bellingcat, The Bureau of
 *                                       Investigative Journalism, ProPublica,
 *                                       IRPI Media IT
 *   - Polar & Climate Science (5):      Arctic Today US, Cryosphere Journal,
 *                                       Antarctic Sun US, Polar Journal CH,
 *                                       Carbon Brief GB
 *   - Southeast Asia Depth (5):         Benar News PH, Coconuts Media TH,
 *                                       This Week in Asia HK, New Naratif SG,
 *                                       Frontier Myanmar MM
 *   - Disinformation Research (5):      DFRLab (Atlantic Council), First Draft,
 *                                       EU DisinfoLab BE, Media Defence GB,
 *                                       Credibility Coalition US
 *   - Gender & Equality (5):            UN Women News, Girls Not Brides GB,
 *                                       Women Deliver US, Equality Now US,
 *                                       OpenDemocracy 50.50
 *   - Pandemic Preparedness (5):        CEPI NO, GAVI Alliance CH,
 *                                       Epidemic Preparedness Innovations,
 *                                       Global Health Security Agenda,
 *                                       International Society for Infectious Diseases
 *   - Election Monitoring (5):          IFES US, Carter Center US, EU Election
 *                                       Observation, NDI US, International IDEA SE
 *   - South America Depth (5):          Folha de S.Paulo BR, La Diaria UY,
 *                                       El Espectador CO, Perfil AR,
 *                                       CIPER Chile CL
 *   - Telecommunications & Cyber (5):   Light Reading US, Telecoms.com GB,
 *                                       Fierce Telecom US, Capacity Media GB,
 *                                       TeleGeography US
 *   - Disaster Response & Resilience (5): PreventionWeb UN, Reliefweb Disasters,
 *                                       IFRC News CH, Floodlist EU,
 *                                       Asian Disaster Preparedness Center TH
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Investigative Journalism ─────────────────────────────────────────────
    {
      slug:            'icij-global',
      name:            'ICIJ — International Consortium of Investigative Journalists',
      description:     'Cross-border investigative journalism network — Panama Papers, Pandora Papers, FinCEN Files',
      url:             'https://www.icij.org',
      tier:            'premium',
      trust_score:     0.96,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'economy', 'corruption']),
      rss_feeds:       JSON.stringify(['https://www.icij.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'bellingcat-gb',
      name:            'Bellingcat',
      description:     'Open-source investigative journalism — conflict verification, geolocation, digital forensics',
      url:             'https://www.bellingcat.com',
      tier:            'premium',
      trust_score:     0.95,
      language:        'en',
      country:         'NL',
      categories:      JSON.stringify(['conflict', 'security', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.bellingcat.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'tbij-gb',
      name:            'The Bureau of Investigative Journalism',
      description:     'UK-based investigative newsroom covering accountability, health, welfare, environment',
      url:             'https://www.thebureauinvestigates.com',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['politics', 'health', 'environment']),
      rss_feeds:       JSON.stringify(['https://www.thebureauinvestigates.com/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'propublica-us',
      name:            'ProPublica',
      description:     'Independent investigative journalism in the public interest — government accountability, justice',
      url:             'https://www.propublica.org',
      tier:            'premium',
      trust_score:     0.95,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'justice', 'economy']),
      rss_feeds:       JSON.stringify(['https://feeds.propublica.org/propublica/main']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'irpi-media-it',
      name:            'IRPI Media',
      description:     'Italian investigative journalism centre — organized crime, corruption, cross-border investigations',
      url:             'https://irpimedia.irpi.eu',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'IT',
      categories:      JSON.stringify(['politics', 'corruption', 'security']),
      rss_feeds:       JSON.stringify(['https://irpimedia.irpi.eu/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Polar & Climate Science ──────────────────────────────────────────────
    {
      slug:            'arctic-today-us',
      name:            'Arctic Today',
      description:     'News and analysis about the Arctic region — climate, geopolitics, indigenous communities, shipping',
      url:             'https://www.arctictoday.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['climate', 'geopolitics', 'environment']),
      rss_feeds:       JSON.stringify(['https://www.arctictoday.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'cryosphere-journal',
      name:            'The Cryosphere Journal',
      description:     'Open-access scientific journal covering frozen components of the Earth system',
      url:             'https://tc.copernicus.org',
      tier:            'specialised',
      trust_score:     0.92,
      language:        'en',
      country:         'DE',
      categories:      JSON.stringify(['climate', 'science', 'environment']),
      rss_feeds:       JSON.stringify(['https://tc.copernicus.org/xml/rss2_0.xml']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'antarctic-sun-us',
      name:            'The Antarctic Sun',
      description:     'Online news from the US Antarctic Program — research, logistics, environment',
      url:             'https://antarcticsun.usap.gov',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'environment', 'climate']),
      rss_feeds:       JSON.stringify(['https://antarcticsun.usap.gov/feed']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'polar-journal-ch',
      name:            'Polar Journal',
      description:     'Swiss-based polar news covering Arctic and Antarctic research, geopolitics, environment',
      url:             'https://polarjournal.ch',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['climate', 'science', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://polarjournal.ch/en/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'carbon-brief-gb-2',
      name:            'Carbon Brief — Data & Science',
      description:     'UK-based climate science and policy data journalism — IPCC analysis, emissions tracking',
      url:             'https://www.carbonbrief.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['climate', 'science', 'energy']),
      rss_feeds:       JSON.stringify(['https://www.carbonbrief.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Southeast Asia Depth ─────────────────────────────────────────────────
    {
      slug:            'benarnews-ph',
      name:            'BenarNews',
      description:     'Multilingual news service covering Southeast Asia and the Pacific — conflict, human rights, politics',
      url:             'https://www.benarnews.org',
      tier:            'major',
      trust_score:     0.86,
      language:        'en',
      country:         'PH',
      categories:      JSON.stringify(['conflict', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.benarnews.org/english/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'coconuts-media-th',
      name:            'Coconuts Media',
      description:     'Digital media covering lifestyle, politics, and news across Southeast Asian cities',
      url:             'https://coconuts.co',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'TH',
      categories:      JSON.stringify(['politics', 'culture', 'technology']),
      rss_feeds:       JSON.stringify(['https://coconuts.co/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'this-week-in-asia-hk',
      name:            'This Week in Asia (SCMP)',
      description:     'SCMP regional coverage of politics, economics, and society across Asia',
      url:             'https://www.scmp.com/week-asia',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'HK',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.scmp.com/rss/5/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'new-naratif-sg',
      name:            'New Naratif',
      description:     'Independent journalism platform for Southeast Asia — democracy, human rights, social justice',
      url:             'https://newnaratif.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'SG',
      categories:      JSON.stringify(['politics', 'justice', 'culture']),
      rss_feeds:       JSON.stringify(['https://newnaratif.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'frontier-myanmar-mm',
      name:            'Frontier Myanmar',
      description:     'Independent English-language news covering Myanmar — politics, conflict, economy, society',
      url:             'https://www.frontiermyanmar.net',
      tier:            'major',
      trust_score:     0.87,
      language:        'en',
      country:         'MM',
      categories:      JSON.stringify(['conflict', 'politics', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.frontiermyanmar.net/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Disinformation Research ──────────────────────────────────────────────
    {
      slug:            'dfrlab-atlantic-council',
      name:            'DFRLab — Atlantic Council Digital Forensic Research Lab',
      description:     'Identifying, exposing, and explaining disinformation worldwide — media manipulation research',
      url:             'https://www.atlanticcouncil.org/programs/digital-forensic-research-lab/',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'technology', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.atlanticcouncil.org/programs/digital-forensic-research-lab/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'first-draft-news',
      name:            'First Draft (Information Futures Lab)',
      description:     'Research and practice of information disorder — verification, media literacy, trust',
      url:             'https://firstdraftnews.org',
      tier:            'specialised',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://firstdraftnews.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'eu-disinfo-lab-be',
      name:            'EU DisinfoLab',
      description:     'Brussels-based NGO tackling sophisticated disinformation campaigns in the EU',
      url:             'https://www.disinfo.eu',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['security', 'politics', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.disinfo.eu/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'media-defence-gb',
      name:            'Media Defence',
      description:     'International human rights NGO providing legal defence for journalists and independent media worldwide',
      url:             'https://www.mediadefence.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['justice', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.mediadefence.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'credibility-coalition-us',
      name:            'Credibility Coalition',
      description:     'Research initiative developing standards and practices for content credibility on the web',
      url:             'https://credibilitycoalition.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'science', 'politics']),
      rss_feeds:       JSON.stringify(['https://credibilitycoalition.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },

    // ── Gender & Equality ────────────────────────────────────────────────────
    {
      slug:            'un-women-news',
      name:            'UN Women News',
      description:     'United Nations entity for gender equality and women empowerment — global policy and programs',
      url:             'https://www.unwomen.org',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'justice', 'health']),
      rss_feeds:       JSON.stringify(['https://www.unwomen.org/en/rss/news']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'girls-not-brides-gb',
      name:            'Girls Not Brides',
      description:     'Global partnership to end child marriage — research, advocacy, news from 100+ countries',
      url:             'https://www.girlsnotbrides.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['justice', 'health', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.girlsnotbrides.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'women-deliver-us',
      name:            'Women Deliver',
      description:     'Global advocacy organization for gender equality, health, rights, and well-being of girls and women',
      url:             'https://womendeliver.org',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'justice', 'politics']),
      rss_feeds:       JSON.stringify(['https://womendeliver.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'equality-now-us',
      name:            'Equality Now',
      description:     'International human rights organization working to protect women and girls — law reform advocacy',
      url:             'https://www.equalitynow.org',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['justice', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.equalitynow.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'opendemocracy-5050',
      name:            'openDemocracy 50.50',
      description:     'Gender, sexuality, and social justice journalism — investigating power, tracking feminist movements',
      url:             'https://www.opendemocracy.net/en/5050/',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['justice', 'politics', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.opendemocracy.net/en/5050/rss/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Pandemic Preparedness ────────────────────────────────────────────────
    {
      slug:            'cepi-no',
      name:            'CEPI — Coalition for Epidemic Preparedness Innovations',
      description:     'Global partnership funding vaccine development against epidemic and pandemic threats',
      url:             'https://cepi.net',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['health', 'science', 'politics']),
      rss_feeds:       JSON.stringify(['https://cepi.net/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'gavi-alliance-ch',
      name:            'Gavi, the Vaccine Alliance',
      description:     'International organisation providing access to vaccines for children in lower-income countries',
      url:             'https://www.gavi.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['health', 'science', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.gavi.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'epi-innovations',
      name:            'Epidemic Preparedness Innovations',
      description:     'Latest developments in outbreak response technology, surveillance systems, and rapid diagnostics',
      url:             'https://www.who.int/emergencies',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['health', 'science']),
      rss_feeds:       JSON.stringify(['https://www.who.int/feeds/entity/emergencies/en/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'ghsa-global',
      name:            'Global Health Security Agenda',
      description:     'Multi-country partnership advancing global health security — AMR, zoonotic disease, biosafety',
      url:             'https://ghsagenda.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'science', 'security']),
      rss_feeds:       JSON.stringify(['https://ghsagenda.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'isid-global',
      name:            'ISID — International Society for Infectious Diseases',
      description:     'Global infectious disease surveillance network — ProMED reports, outbreak alerts',
      url:             'https://isid.org',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'science']),
      rss_feeds:       JSON.stringify(['https://isid.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Election Monitoring ──────────────────────────────────────────────────
    {
      slug:            'ifes-us',
      name:            'IFES — International Foundation for Electoral Systems',
      description:     'Building democracies that deliver for all — election support, anti-corruption, inclusion programs',
      url:             'https://www.ifes.org',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['elections', 'politics', 'justice']),
      rss_feeds:       JSON.stringify(['https://www.ifes.org/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'carter-center-us',
      name:            'The Carter Center — Peace & Elections',
      description:     'Waging peace through election observation, conflict resolution, human rights, and disease prevention',
      url:             'https://www.cartercenter.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['elections', 'politics', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.cartercenter.org/rss/index.html']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'eu-eom',
      name:            'EU Election Observation Missions',
      description:     'European Union election observation — deployed to democracies worldwide, independent assessment reports',
      url:             'https://www.eeas.europa.eu/eeas/election-observation-missions-and-exploratory-missions_en',
      tier:            'major',
      trust_score:     0.91,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['elections', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.eeas.europa.eu/eeas/rss/feed_en']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'ndi-us',
      name:            'NDI — National Democratic Institute',
      description:     'Supporting democratic institutions and practices worldwide — elections, political parties, citizen participation',
      url:             'https://www.ndi.org',
      tier:            'major',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['elections', 'politics', 'justice']),
      rss_feeds:       JSON.stringify(['https://www.ndi.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'idea-se-elections',
      name:            'International IDEA — Elections',
      description:     'Intergovernmental organisation supporting sustainable democracy — voter turnout data, electoral systems',
      url:             'https://www.idea.int',
      tier:            'major',
      trust_score:     0.90,
      language:        'en',
      country:         'SE',
      categories:      JSON.stringify(['elections', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.idea.int/feed']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── South America Depth ──────────────────────────────────────────────────
    {
      slug:            'folha-br-depth',
      name:            'Folha de S.Paulo — Internacional',
      description:     'Largest Brazilian daily newspaper — international section covering Latin America and the world',
      url:             'https://www1.folha.uol.com.br/internacional/',
      tier:            'premium',
      trust_score:     0.87,
      language:        'pt',
      country:         'BR',
      categories:      JSON.stringify(['politics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://feeds.folha.uol.com.br/internacional/rss091.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'la-diaria-uy',
      name:            'la diaria',
      description:     'Independent Uruguayan daily — progressive journalism covering politics, culture, environment',
      url:             'https://ladiaria.com.uy',
      tier:            'major',
      trust_score:     0.83,
      language:        'es',
      country:         'UY',
      categories:      JSON.stringify(['politics', 'culture', 'environment']),
      rss_feeds:       JSON.stringify(['https://ladiaria.com.uy/rss/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'el-espectador-co',
      name:            'El Espectador',
      description:     'Oldest continuously published newspaper in Colombia — politics, conflict, judicial affairs',
      url:             'https://www.elespectador.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'es',
      country:         'CO',
      categories:      JSON.stringify(['politics', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.elespectador.com/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'perfil-ar',
      name:            'Perfil',
      description:     'Argentine news and political analysis — politics, economy, opinion, investigative journalism',
      url:             'https://www.perfil.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'es',
      country:         'AR',
      categories:      JSON.stringify(['politics', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.perfil.com/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'ciper-chile-cl',
      name:            'CIPER Chile',
      description:     'Centro de Investigación Periodística — Chile\'s premier investigative journalism outlet',
      url:             'https://www.ciperchile.cl',
      tier:            'premium',
      trust_score:     0.90,
      language:        'es',
      country:         'CL',
      categories:      JSON.stringify(['politics', 'corruption', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.ciperchile.cl/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Telecommunications & Cyber ───────────────────────────────────────────
    {
      slug:            'light-reading-us',
      name:            'Light Reading',
      description:     'Telecom industry news — 5G, broadband, network infrastructure, edge computing',
      url:             'https://www.lightreading.com',
      tier:            'major',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.lightreading.com/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'telecoms-com-gb',
      name:            'Telecoms.com',
      description:     'Global telecommunications industry news — operators, infrastructure, regulation, digital transformation',
      url:             'https://telecoms.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['technology', 'economy']),
      rss_feeds:       JSON.stringify(['https://telecoms.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'fierce-telecom-us',
      name:            'Fierce Telecom',
      description:     'Enterprise and wholesale telecom news — fiber, SD-WAN, unified communications',
      url:             'https://www.fiercetelecom.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.fiercetelecom.com/rss/xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'capacity-media-gb',
      name:            'Capacity Media',
      description:     'Wholesale telecom and data centre industry — submarine cables, cloud, connectivity markets',
      url:             'https://www.capacitymedia.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['technology', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.capacitymedia.com/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'telegeography-us',
      name:            'TeleGeography',
      description:     'Submarine cable maps, internet exchange, and global bandwidth research — telecom infrastructure data',
      url:             'https://www.telegeography.com',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://blog.telegeography.com/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Disaster Response & Resilience ───────────────────────────────────────
    {
      slug:            'preventionweb-un',
      name:            'PreventionWeb (UNDRR)',
      description:     'UN Office for Disaster Risk Reduction knowledge platform — Sendai Framework, DRR policy, early warning',
      url:             'https://www.preventionweb.net',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['disaster', 'climate', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.preventionweb.net/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'reliefweb-disasters',
      name:            'ReliefWeb Disasters',
      description:     'UN OCHA humanitarian information service — active disaster tracking, situation reports, maps',
      url:             'https://reliefweb.int/disasters',
      tier:            'premium',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['disaster', 'conflict', 'health']),
      rss_feeds:       JSON.stringify(['https://reliefweb.int/disasters/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'ifrc-news-ch',
      name:            'IFRC — International Federation of Red Cross and Red Crescent Societies',
      description:     'World\'s largest humanitarian network — disaster response, health, climate adaptation',
      url:             'https://www.ifrc.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['disaster', 'health', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.ifrc.org/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'floodlist-eu',
      name:            'FloodList',
      description:     'Global flood and heavy rainfall event tracking — real-time flood disaster news and analysis',
      url:             'https://floodlist.com',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'EU',
      categories:      JSON.stringify(['disaster', 'climate', 'environment']),
      rss_feeds:       JSON.stringify(['https://floodlist.com/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'adpc-th',
      name:            'Asian Disaster Preparedness Center',
      description:     'Regional organisation supporting disaster risk reduction across Asia-Pacific — early warning, capacity building',
      url:             'https://www.adpc.net',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'TH',
      categories:      JSON.stringify(['disaster', 'climate', 'science']),
      rss_feeds:       JSON.stringify(['https://www.adpc.net/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
  ]

  // Idempotent: ON CONFLICT(slug) DO NOTHING
  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'icij-global', 'bellingcat-gb', 'tbij-gb', 'propublica-us', 'irpi-media-it',
    'arctic-today-us', 'cryosphere-journal', 'antarctic-sun-us', 'polar-journal-ch', 'carbon-brief-gb-2',
    'benarnews-ph', 'coconuts-media-th', 'this-week-in-asia-hk', 'new-naratif-sg', 'frontier-myanmar-mm',
    'dfrlab-atlantic-council', 'first-draft-news', 'eu-disinfo-lab-be', 'media-defence-gb', 'credibility-coalition-us',
    'un-women-news', 'girls-not-brides-gb', 'women-deliver-us', 'equality-now-us', 'opendemocracy-5050',
    'cepi-no', 'gavi-alliance-ch', 'epi-innovations', 'ghsa-global', 'isid-global',
    'ifes-us', 'carter-center-us', 'eu-eom', 'ndi-us', 'idea-se-elections',
    'folha-br-depth', 'la-diaria-uy', 'el-espectador-co', 'perfil-ar', 'ciper-chile-cl',
    'light-reading-us', 'telecoms-com-gb', 'fierce-telecom-us', 'capacity-media-gb', 'telegeography-us',
    'preventionweb-un', 'reliefweb-disasters', 'ifrc-news-ch', 'floodlist-eu', 'adpc-th',
  ]
  await knex('sources').whereIn('slug', slugs).del()
}
