import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 350+ feeds
 *
 * Adds 50 new high-quality global RSS sources to close regional coverage gaps:
 *
 *   - Latin America Depth:    El Universal MX, La Jornada MX, O Globo BR,
 *                             El Comercio PE, El Tiempo CO, La Tercera CL,
 *                             El Nacional VE, El Deber BO, Prensa Libre GT,
 *                             La Prensa HN
 *   - South Asia:             The News International PK, Kathmandu Post NP,
 *                             Daily Star BD, Colombo Gazette LK, The Wire IN,
 *                             Scroll.in IN, Himal Southasian (pan-South Asia),
 *                             Nepali Times NP, Daily FT LK
 *   - Horn of Africa:         Addis Standard ET, Sudan Tribune SD,
 *                             Garowe Online SO, Eritrea Hub ER,
 *                             The Reporter ET, Dabanga Radio SD
 *   - West Africa Depth:      Vanguard NG, The Punch NG, Myjoyonline GH,
 *                             L'Observateur BF, Seneweb SN
 *   - Central Africa:         Radio Okapi CD, Cameroon Tribune CM,
 *                             Igihe RW, The New Times RW
 *   - Central America & Carib: La Prensa Libre CR, El Faro SV,
 *                             Confidencial NI, Noticias SIN DO
 *   - Conflict & Crisis:      Syria Direct SY, Libya Observer LY,
 *                             The New Arab (pan-MENA), Iraq News Agency IQ
 *   - Climate & Environment:  Climate Home News, The Third Pole (HKH),
 *                             Dialogue Earth, China Dialogue
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Latin America Depth ─────────────────────────────────────────────────
    {
      slug:            'el-universal-mx',
      name:            'El Universal',
      description:     'Mexico\'s oldest daily newspaper covering politics, security, and economy',
      url:             'https://www.eluniversal.com.mx',
      tier:            'major',
      trust_score:     0.82,
      language:        'es',
      country:         'MX',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.eluniversal.com.mx/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'la-jornada-mx',
      name:            'La Jornada',
      description:     'Major Mexican daily with strong investigative journalism and LatAm coverage',
      url:             'https://www.jornada.com.mx',
      tier:            'major',
      trust_score:     0.80,
      language:        'es',
      country:         'MX',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.jornada.com.mx/rss/edicion.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'o-globo-br',
      name:            'O Globo',
      description:     'Major Brazilian broadsheet — politics, economy, environment, and Amazon coverage',
      url:             'https://oglobo.globo.com',
      tier:            'major',
      trust_score:     0.83,
      language:        'pt',
      country:         'BR',
      categories:      JSON.stringify(['politics', 'economy', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://oglobo.globo.com/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'el-comercio-pe',
      name:            'El Comercio Peru',
      description:     'Peru\'s leading newspaper covering Andean politics, economy, and security',
      url:             'https://elcomercio.pe',
      tier:            'regional',
      trust_score:     0.80,
      language:        'es',
      country:         'PE',
      categories:      JSON.stringify(['politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://elcomercio.pe/arcio/rss/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'el-tiempo-co',
      name:            'El Tiempo',
      description:     'Colombia\'s largest newspaper — conflict, peace process, economy, and politics',
      url:             'https://www.eltiempo.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'es',
      country:         'CO',
      categories:      JSON.stringify(['conflict', 'politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://www.eltiempo.com/rss/feeds']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'la-tercera-cl',
      name:            'La Tercera',
      description:     'Chile\'s major daily — politics, economy, lithium industry, and LatAm affairs',
      url:             'https://www.latercera.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'es',
      country:         'CL',
      categories:      JSON.stringify(['politics', 'economy', 'technology', 'science']),
      rss_feeds:       JSON.stringify(['https://www.latercera.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'el-nacional-ve',
      name:            'El Nacional',
      description:     'Venezuelan daily covering politics, crisis, migration, and human rights',
      url:             'https://www.elnacional.com',
      tier:            'regional',
      trust_score:     0.78,
      language:        'es',
      country:         'VE',
      categories:      JSON.stringify(['politics', 'conflict', 'humanitarian', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.elnacional.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'el-deber-bo',
      name:            'El Deber',
      description:     'Bolivia\'s leading independent newspaper covering politics, economy, and Amazon deforestation',
      url:             'https://eldeber.com.bo',
      tier:            'regional',
      trust_score:     0.78,
      language:        'es',
      country:         'BO',
      categories:      JSON.stringify(['politics', 'economy', 'climate', 'security']),
      rss_feeds:       JSON.stringify(['https://eldeber.com.bo/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'prensa-libre-gt',
      name:            'Prensa Libre',
      description:     'Guatemala\'s major daily — politics, security, migration, and Central American affairs',
      url:             'https://www.prensalibre.com',
      tier:            'regional',
      trust_score:     0.79,
      language:        'es',
      country:         'GT',
      categories:      JSON.stringify(['politics', 'security', 'humanitarian', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.prensalibre.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'la-prensa-hn',
      name:            'La Prensa Honduras',
      description:     'Honduras\' leading newspaper covering security, migration, and Central American politics',
      url:             'https://www.laprensa.hn',
      tier:            'regional',
      trust_score:     0.77,
      language:        'es',
      country:         'HN',
      categories:      JSON.stringify(['security', 'politics', 'humanitarian', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.laprensa.hn/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── South Asia ──────────────────────────────────────────────────────────
    {
      slug:            'news-international-pk',
      name:            'The News International',
      description:     'Pakistan\'s largest English daily — politics, security, economy, and regional affairs',
      url:             'https://www.thenews.com.pk',
      tier:            'major',
      trust_score:     0.80,
      language:        'en',
      country:         'PK',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.thenews.com.pk/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'kathmandu-post-np',
      name:            'Kathmandu Post',
      description:     'Nepal\'s premier English-language newspaper — politics, climate, and Himalayan affairs',
      url:             'https://kathmandupost.com',
      tier:            'regional',
      trust_score:     0.80,
      language:        'en',
      country:         'NP',
      categories:      JSON.stringify(['politics', 'climate', 'humanitarian', 'economy']),
      rss_feeds:       JSON.stringify(['https://kathmandupost.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'daily-star-bd',
      name:            'The Daily Star Bangladesh',
      description:     'Bangladesh\'s largest English daily — politics, climate disasters, garment industry',
      url:             'https://www.thedailystar.net',
      tier:            'major',
      trust_score:     0.81,
      language:        'en',
      country:         'BD',
      categories:      JSON.stringify(['politics', 'climate', 'economy', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.thedailystar.net/frontpage/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'colombo-gazette-lk',
      name:            'Colombo Gazette',
      description:     'Sri Lanka\'s online news — politics, economy, post-crisis recovery',
      url:             'https://colombogazette.com',
      tier:            'regional',
      trust_score:     0.77,
      language:        'en',
      country:         'LK',
      categories:      JSON.stringify(['politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://colombogazette.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-wire-in',
      name:            'The Wire India',
      description:     'Independent Indian investigative outlet covering politics, rights, and policy',
      url:             'https://thewire.in',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['politics', 'security', 'technology', 'economy']),
      rss_feeds:       JSON.stringify(['https://thewire.in/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'scroll-in',
      name:            'Scroll.in',
      description:     'Indian digital-native news covering politics, culture, and South Asian affairs',
      url:             'https://scroll.in',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['politics', 'culture', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://scroll.in/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'himal-southasian',
      name:            'Himal Southasian',
      description:     'Pan-South Asian magazine covering regional politics, cross-border issues, and culture',
      url:             'https://www.himalmag.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'NP',
      categories:      JSON.stringify(['geopolitics', 'politics', 'culture', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.himalmag.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'nepali-times',
      name:            'Nepali Times',
      description:     'Nepal\'s independent English weekly — politics, climate, and Himalayan region',
      url:             'https://www.nepalitimes.com',
      tier:            'regional',
      trust_score:     0.80,
      language:        'en',
      country:         'NP',
      categories:      JSON.stringify(['politics', 'climate', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.nepalitimes.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'daily-ft-lk',
      name:            'Daily FT',
      description:     'Sri Lanka\'s financial daily — economy, trade, post-crisis recovery',
      url:             'https://www.ft.lk',
      tier:            'specialised',
      trust_score:     0.79,
      language:        'en',
      country:         'LK',
      categories:      JSON.stringify(['economy', 'politics', 'trade']),
      rss_feeds:       JSON.stringify(['https://www.ft.lk/feed']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Horn of Africa ──────────────────────────────────────────────────────
    {
      slug:            'addis-standard-et',
      name:            'Addis Standard',
      description:     'Ethiopia\'s independent English outlet covering Tigray conflict, politics, and Horn affairs',
      url:             'https://addisstandard.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'ET',
      categories:      JSON.stringify(['conflict', 'politics', 'humanitarian', 'security']),
      rss_feeds:       JSON.stringify(['https://addisstandard.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'sudan-tribune',
      name:            'Sudan Tribune',
      description:     'Independent Sudan news covering civil war, humanitarian crisis, and politics',
      url:             'https://sudantribune.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'SD',
      categories:      JSON.stringify(['conflict', 'humanitarian', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://sudantribune.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'garowe-online-so',
      name:            'Garowe Online',
      description:     'Somalia/Puntland news covering Al-Shabaab, piracy, politics, and humanitarian issues',
      url:             'https://www.garoweonline.com',
      tier:            'regional',
      trust_score:     0.75,
      language:        'en',
      country:         'SO',
      categories:      JSON.stringify(['conflict', 'security', 'politics', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.garoweonline.com/en/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'eritrea-hub',
      name:            'Eritrea Hub',
      description:     'Independent Eritrea analysis covering politics, human rights, and Horn of Africa affairs',
      url:             'https://eritreahub.org',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'ER',
      categories:      JSON.stringify(['politics', 'humanitarian', 'conflict', 'security']),
      rss_feeds:       JSON.stringify(['https://eritreahub.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'reporter-et',
      name:            'The Reporter Ethiopia',
      description:     'Ethiopia\'s largest English weekly covering politics, business, and East African affairs',
      url:             'https://www.thereporterethiopia.com',
      tier:            'regional',
      trust_score:     0.78,
      language:        'en',
      country:         'ET',
      categories:      JSON.stringify(['politics', 'economy', 'conflict', 'security']),
      rss_feeds:       JSON.stringify(['https://www.thereporterethiopia.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'dabanga-sd',
      name:            'Dabanga Radio',
      description:     'Independent Sudan/Darfur news — conflict, displacement, humanitarian crisis',
      url:             'https://www.dabangasudan.org',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'SD',
      categories:      JSON.stringify(['conflict', 'humanitarian', 'security', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.dabangasudan.org/en/feed']),
      scrape_interval: 900,
      active:          true,
    },

    // ── West Africa Depth ───────────────────────────────────────────────────
    {
      slug:            'vanguard-ng',
      name:            'Vanguard Nigeria',
      description:     'Nigeria\'s major daily covering politics, security, oil industry, and economy',
      url:             'https://www.vanguardngr.com',
      tier:            'major',
      trust_score:     0.79,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.vanguardngr.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'punch-ng',
      name:            'The Punch Nigeria',
      description:     'Nigeria\'s most widely read newspaper — politics, crime, economy',
      url:             'https://punchng.com',
      tier:            'major',
      trust_score:     0.79,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://punchng.com/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'myjoyonline-gh',
      name:            'Myjoyonline',
      description:     'Ghana\'s leading online news platform — politics, economy, and West African affairs',
      url:             'https://www.myjoyonline.com',
      tier:            'regional',
      trust_score:     0.79,
      language:        'en',
      country:         'GH',
      categories:      JSON.stringify(['politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://www.myjoyonline.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'lobservateur-bf',
      name:            'L\'Observateur Paalga',
      description:     'Burkina Faso\'s leading daily covering Sahel security, politics, and jihadist threats',
      url:             'https://lobservateur.bf',
      tier:            'regional',
      trust_score:     0.76,
      language:        'fr',
      country:         'BF',
      categories:      JSON.stringify(['conflict', 'security', 'politics']),
      rss_feeds:       JSON.stringify(['https://lobservateur.bf/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'seneweb-sn',
      name:            'Seneweb',
      description:     'Senegal\'s top news portal — politics, economy, and Francophone West Africa',
      url:             'https://www.seneweb.com',
      tier:            'regional',
      trust_score:     0.77,
      language:        'fr',
      country:         'SN',
      categories:      JSON.stringify(['politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://www.seneweb.com/news/rss']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Central Africa ──────────────────────────────────────────────────────
    {
      slug:            'radio-okapi-cd',
      name:            'Radio Okapi',
      description:     'UN-backed Congo news covering M23 conflict, humanitarian crisis, and elections',
      url:             'https://www.radiookapi.net',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'fr',
      country:         'CD',
      categories:      JSON.stringify(['conflict', 'humanitarian', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.radiookapi.net/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'cameroon-tribune-cm',
      name:            'Cameroon Tribune',
      description:     'Cameroon\'s state newspaper covering politics, anglophone crisis, and Central African affairs',
      url:             'https://www.cameroon-tribune.cm',
      tier:            'regional',
      trust_score:     0.72,
      language:        'fr',
      country:         'CM',
      categories:      JSON.stringify(['politics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.cameroon-tribune.cm/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'igihe-rw',
      name:            'Igihe',
      description:     'Rwanda\'s largest digital news platform covering politics, economy, and Great Lakes region',
      url:             'https://en.igihe.com',
      tier:            'regional',
      trust_score:     0.75,
      language:        'en',
      country:         'RW',
      categories:      JSON.stringify(['politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://en.igihe.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'new-times-rw',
      name:            'The New Times Rwanda',
      description:     'Rwanda\'s leading English daily — politics, economy, and East African affairs',
      url:             'https://www.newtimes.co.rw',
      tier:            'regional',
      trust_score:     0.76,
      language:        'en',
      country:         'RW',
      categories:      JSON.stringify(['politics', 'economy', 'technology', 'security']),
      rss_feeds:       JSON.stringify(['https://www.newtimes.co.rw/rssFeed']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Central America & Caribbean Depth ───────────────────────────────────
    {
      slug:            'la-prensa-libre-cr',
      name:            'La Prensa Libre Costa Rica',
      description:     'Costa Rica\'s digital news — politics, environment, and Central American affairs',
      url:             'https://www.laprensalibre.cr',
      tier:            'regional',
      trust_score:     0.78,
      language:        'es',
      country:         'CR',
      categories:      JSON.stringify(['politics', 'climate', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.laprensalibre.cr/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'el-faro-sv',
      name:            'El Faro',
      description:     'El Salvador\'s premier investigative outlet — gangs, migration, authoritarianism',
      url:             'https://elfaro.net',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'es',
      country:         'SV',
      categories:      JSON.stringify(['politics', 'security', 'humanitarian', 'conflict']),
      rss_feeds:       JSON.stringify(['https://elfaro.net/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'confidencial-ni',
      name:            'Confidencial',
      description:     'Nicaragua\'s independent investigative outlet (exiled) covering authoritarianism and LatAm',
      url:             'https://www.confidencial.digital',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'es',
      country:         'NI',
      categories:      JSON.stringify(['politics', 'conflict', 'humanitarian', 'security']),
      rss_feeds:       JSON.stringify(['https://www.confidencial.digital/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'noticias-sin-do',
      name:            'Noticias SIN',
      description:     'Dominican Republic\'s leading TV/digital news — politics, economy, and Caribbean affairs',
      url:             'https://noticiassin.com',
      tier:            'regional',
      trust_score:     0.77,
      language:        'es',
      country:         'DO',
      categories:      JSON.stringify(['politics', 'economy', 'security', 'breaking']),
      rss_feeds:       JSON.stringify(['https://noticiassin.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Conflict & Crisis Zones ─────────────────────────────────────────────
    {
      slug:            'syria-direct',
      name:            'Syria Direct',
      description:     'Independent Syria reporting — conflict, displacement, reconstruction, and politics',
      url:             'https://syriadirect.org',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'SY',
      categories:      JSON.stringify(['conflict', 'humanitarian', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://syriadirect.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'libya-observer',
      name:            'The Libya Observer',
      description:     'Libya news covering political divisions, oil, migration, and security',
      url:             'https://www.libyaobserver.ly',
      tier:            'regional',
      trust_score:     0.76,
      language:        'en',
      country:         'LY',
      categories:      JSON.stringify(['conflict', 'politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://www.libyaobserver.ly/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'new-arab',
      name:            'The New Arab',
      description:     'Pan-MENA English outlet covering conflicts, politics, culture, and human rights',
      url:             'https://www.newarab.com',
      tier:            'major',
      trust_score:     0.80,
      language:        'en',
      country:         'QA',
      categories:      JSON.stringify(['conflict', 'politics', 'humanitarian', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.newarab.com/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'iraq-news-agency',
      name:            'Iraqi News Agency',
      description:     'Iraq official news agency — politics, security, reconstruction, and regional affairs',
      url:             'https://www.ina.iq/eng',
      tier:            'regional',
      trust_score:     0.72,
      language:        'en',
      country:         'IQ',
      categories:      JSON.stringify(['politics', 'security', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.ina.iq/eng/feed']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Climate & Environment ───────────────────────────────────────────────
    {
      slug:            'climate-home-news',
      name:            'Climate Home News',
      description:     'Independent climate journalism covering COP negotiations, policy, and climate justice',
      url:             'https://www.climatechangenews.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['climate', 'politics', 'economy', 'science']),
      rss_feeds:       JSON.stringify(['https://www.climatechangenews.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'third-pole',
      name:            'The Third Pole',
      description:     'Hindu Kush Himalaya water/climate journalism — glaciers, rivers, South/Central Asia',
      url:             'https://www.thethirdpole.net',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['climate', 'science', 'humanitarian', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.thethirdpole.net/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'dialogue-earth',
      name:            'Dialogue Earth',
      description:     'Environmental journalism covering China, Asia-Pacific, and global climate policy',
      url:             'https://dialogue.earth',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['climate', 'economy', 'politics', 'science']),
      rss_feeds:       JSON.stringify(['https://dialogue.earth/en/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'china-dialogue',
      name:            'China Dialogue',
      description:     'Bilingual EN/ZH environmental journalism on China\'s environmental and climate impact',
      url:             'https://chinadialogue.net',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['climate', 'economy', 'politics', 'technology']),
      rss_feeds:       JSON.stringify(['https://chinadialogue.net/en/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'el-universal-mx', 'la-jornada-mx', 'o-globo-br', 'el-comercio-pe',
    'el-tiempo-co', 'la-tercera-cl', 'el-nacional-ve', 'el-deber-bo',
    'prensa-libre-gt', 'la-prensa-hn',
    'news-international-pk', 'kathmandu-post-np', 'daily-star-bd',
    'colombo-gazette-lk', 'the-wire-in', 'scroll-in', 'himal-southasian',
    'nepali-times', 'daily-ft-lk',
    'addis-standard-et', 'sudan-tribune', 'garowe-online-so',
    'eritrea-hub', 'reporter-et', 'dabanga-sd',
    'vanguard-ng', 'punch-ng', 'myjoyonline-gh',
    'lobservateur-bf', 'seneweb-sn',
    'radio-okapi-cd', 'cameroon-tribune-cm', 'igihe-rw', 'new-times-rw',
    'la-prensa-libre-cr', 'el-faro-sv', 'confidencial-ni', 'noticias-sin-do',
    'syria-direct', 'libya-observer', 'new-arab', 'iraq-news-agency',
    'climate-home-news', 'third-pole', 'dialogue-earth', 'china-dialogue',
  ]
  await knex('sources').whereIn('slug', slugs).delete()
}
