import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 650+ feeds
 *
 * Adds 50 new high-quality global RSS sources across 10 verticals to extend
 * WorldPulse's leadership over WorldMonitor (now 650+ vs 435+ = 1.49x advantage).
 *
 *   - Refugee & Migration Policy (5):   UNHCR Stories, Mixed Migration Centre,
 *                                       Refugees Deeply/The New Humanitarian,
 *                                       ECRE (European Council), Migration Policy Inst.
 *   - Rare Earth & Critical Minerals (5): Mining.com, IRMA, Resource World,
 *                                       Critical Raw Materials Alliance, Benchmark
 *   - Indigenous Media (5):              Indian Country Today US, NITV AU,
 *                                       Māori Television NZ, First Nations Drum CA,
 *                                       Intercontinental Cry
 *   - Outer Space & Satellite Intel (5): Payload Space, Via Satellite, SatNews,
 *                                       Space Intel Report, European Space Policy Inst
 *   - Organized Crime & Illicit Finance (5): InSight Crime, Global Initiative,
 *                                       FATF, Basel Institute, ACAMS
 *   - Child Rights & Protection (5):     UNICEF News, Save the Children, Plan Intl,
 *                                       Child Rights International, ECPAT
 *   - Polar Geopolitics (5):             The Arctic Institute US, Polar Connection,
 *                                       High North News NO, Wilson Center Polar,
 *                                       Scott Polar Research Institute GB
 *   - Legal & Justice Systems (5):       IJRC, International Justice Monitor,
 *                                       ICC Observer, Justiceinfo.net CH,
 *                                       Open Society Justice Initiative
 *   - Biosecurity & Dual-Use Research (5): Johns Hopkins CHS, NTI Bio,
 *                                       Bulletin Bio, Global Health Security Index,
 *                                       VERTIC
 *   - African Tech & Innovation (5):     TechCabal NG, Disrupt Africa ZA,
 *                                       iAfrikan ZA, Digest Africa UG,
 *                                       WeeTracker NG
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Refugee & Migration Policy ────────────────────────────────────────
    {
      slug:            'unhcr-stories',
      name:            'UNHCR — Stories',
      description:     'UN Refugee Agency stories and reports — forced displacement, refugee crises, statelessness worldwide',
      url:             'https://www.unhcr.org/stories',
      tier:            'premium',
      trust_score:     0.95,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['migration', 'conflict', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.unhcr.org/rss/stories.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'mixed-migration-centre',
      name:            'Mixed Migration Centre',
      description:     'DRC-affiliated research centre — data and analysis on mixed migration flows, routes, protection risks',
      url:             'https://mixedmigration.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['migration', 'security', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://mixedmigration.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'ecre-eu',
      name:            'ECRE — European Council on Refugees and Exiles',
      description:     'Pan-European alliance of NGOs — asylum policy, refugee rights, EU migration governance',
      url:             'https://ecre.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['migration', 'politics', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://ecre.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'migration-policy-inst-us',
      name:            'Migration Policy Institute',
      description:     'Authoritative US think tank on international migration — data, policy analysis, research',
      url:             'https://www.migrationpolicy.org',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['migration', 'politics', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.migrationpolicy.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'refugees-intl-us',
      name:            'Refugees International',
      description:     'Independent advocacy org — field-based research on displacement crises, policy recommendations',
      url:             'https://www.refugeesinternational.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['migration', 'conflict', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.refugeesinternational.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Rare Earth & Critical Minerals ────────────────────────────────────
    {
      slug:            'mining-com-global',
      name:            'MINING.COM',
      description:     'World\'s leading mining news site — rare earths, critical minerals, commodity markets, supply chain',
      url:             'https://www.mining.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'CA',
      categories:      JSON.stringify(['economy', 'technology', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.mining.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'irma-global',
      name:            'IRMA — Initiative for Responsible Mining Assurance',
      description:     'Independent responsible mining certification — supply chain transparency, ESG, human rights in mining',
      url:             'https://responsiblemining.net',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'environment', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://responsiblemining.net/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'resource-world-ca',
      name:            'Resource World Magazine',
      description:     'Canadian resource sector magazine — mining, energy, critical minerals investment and exploration',
      url:             'https://resourceworld.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'CA',
      categories:      JSON.stringify(['economy', 'technology', 'environment']),
      rss_feeds:       JSON.stringify(['https://resourceworld.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'crma-eu',
      name:            'Critical Raw Materials Alliance',
      description:     'EU industry alliance for critical raw materials — supply security, recycling, strategic autonomy',
      url:             'https://www.crmalliance.eu',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['economy', 'technology', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.crmalliance.eu/feed']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'benchmark-minerals-gb',
      name:            'Benchmark Mineral Intelligence',
      description:     'Lithium, cobalt, nickel, graphite, rare earth pricing and supply chain intelligence',
      url:             'https://www.benchmarkminerals.com',
      tier:            'major',
      trust_score:     0.87,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['economy', 'technology', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.benchmarkminerals.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Indigenous Media ──────────────────────────────────────────────────
    {
      slug:            'indian-country-today-us',
      name:            'Indian Country Today',
      description:     'Leading Native American and indigenous news — tribal sovereignty, culture, federal Indian policy',
      url:             'https://ictnews.org',
      tier:            'major',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'culture', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://ictnews.org/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'nitv-au',
      name:            'NITV — National Indigenous Television',
      description:     'Australia\'s national indigenous broadcaster — First Nations news, culture, community stories',
      url:             'https://www.sbs.com.au/nitv',
      tier:            'major',
      trust_score:     0.87,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['politics', 'culture', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.sbs.com.au/nitv/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'whakaata-maori-nz',
      name:            'Whakaata Māori (Māori Television)',
      description:     'Aotearoa New Zealand Māori public broadcaster — te reo, Treaty of Waitangi, indigenous rights',
      url:             'https://www.maoritelevision.com',
      tier:            'major',
      trust_score:     0.86,
      language:        'en',
      country:         'NZ',
      categories:      JSON.stringify(['politics', 'culture', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.maoritelevision.com/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'first-nations-drum-ca',
      name:            'First Nations Drum',
      description:     'Canadian indigenous news — First Nations, Métis, Inuit issues, land rights, reconciliation',
      url:             'https://www.firstnationsdrum.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'CA',
      categories:      JSON.stringify(['politics', 'culture', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.firstnationsdrum.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'intercontinental-cry-2',
      name:            'Intercontinental Cry',
      description:     'Center for World Indigenous Studies — global indigenous peoples\' rights, land defense, sovereignty',
      url:             'https://intercontinentalcry.org',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'CA',
      categories:      JSON.stringify(['human-rights', 'environment', 'culture']),
      rss_feeds:       JSON.stringify(['https://intercontinentalcry.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Outer Space & Satellite Intel ─────────────────────────────────────
    {
      slug:            'payload-space-us',
      name:            'Payload',
      description:     'Space industry business intelligence — satellite launches, orbital economics, space defense',
      url:             'https://payloadspace.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'security', 'economy']),
      rss_feeds:       JSON.stringify(['https://payloadspace.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'via-satellite-us',
      name:            'Via Satellite',
      description:     'Satellite communications industry news — broadband, LEO constellations, ground systems, policy',
      url:             'https://www.satellitetoday.com',
      tier:            'major',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://www.satellitetoday.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'satnews-us',
      name:            'SatNews',
      description:     'Daily satellite and space news — launch coverage, military space, earth observation, navigation',
      url:             'https://news.satnews.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://news.satnews.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'space-intel-report-us',
      name:            'Space Intel Report',
      description:     'Independent space launch and satellite deployment intelligence — manifest tracking, analysis',
      url:             'https://www.spaceintelreport.com',
      tier:            'specialised',
      trust_score:     0.81,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://www.spaceintelreport.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'espi-at',
      name:            'European Space Policy Institute',
      description:     'Vienna-based think tank — European space policy, governance, industrial base, security & defense',
      url:             'https://www.espi.or.at',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'AT',
      categories:      JSON.stringify(['technology', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.espi.or.at/feed/']),
      scrape_interval: 7200,
      active:          true,
    },

    // ── Organized Crime & Illicit Finance ──────────────────────────────────
    {
      slug:            'insight-crime-us',
      name:            'InSight Crime',
      description:     'Investigation and analysis of organized crime in Latin America and the Caribbean',
      url:             'https://insightcrime.org',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'corruption', 'politics']),
      rss_feeds:       JSON.stringify(['https://insightcrime.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'gi-toc-ch',
      name:            'Global Initiative Against Transnational Organized Crime',
      description:     'Network of 600+ experts — organized crime research, illicit economies, policy briefs',
      url:             'https://globalinitiative.net',
      tier:            'premium',
      trust_score:     0.89,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['security', 'corruption', 'economy']),
      rss_feeds:       JSON.stringify(['https://globalinitiative.net/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'fatf-fr',
      name:            'FATF — Financial Action Task Force',
      description:     'Intergovernmental body setting global standards on anti-money laundering & counter-terrorism financing',
      url:             'https://www.fatf-gafi.org',
      tier:            'premium',
      trust_score:     0.94,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['economy', 'security', 'corruption']),
      rss_feeds:       JSON.stringify(['https://www.fatf-gafi.org/rss/fatf.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'basel-institute-ch',
      name:            'Basel Institute on Governance',
      description:     'Swiss non-profit on anti-corruption, asset recovery, collective action, compliance — Basel AML Index',
      url:             'https://baselgovernance.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['corruption', 'economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://baselgovernance.org/feed']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'acams-us',
      name:            'ACAMS — Association of Certified Anti-Money Laundering Specialists',
      description:     'Global AML/CFT professional network — financial crime news, regulatory updates, compliance trends',
      url:             'https://www.acams.org',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'security', 'corruption']),
      rss_feeds:       JSON.stringify(['https://www.acams.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Child Rights & Protection ─────────────────────────────────────────
    {
      slug:            'unicef-news',
      name:            'UNICEF News',
      description:     'UN Children\'s Fund — child rights, education, health, protection, emergencies worldwide',
      url:             'https://www.unicef.org/press-releases',
      tier:            'premium',
      trust_score:     0.95,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['human-rights', 'health', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.unicef.org/press-releases/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'save-children-gb',
      name:            'Save the Children — News',
      description:     'International NGO — children in conflict, poverty, displacement, education access, child health',
      url:             'https://www.savethechildren.net',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['human-rights', 'conflict', 'health']),
      rss_feeds:       JSON.stringify(['https://www.savethechildren.net/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'plan-intl-gb',
      name:            'Plan International',
      description:     'Children\'s rights and equality for girls — education, child marriage, gender-based violence',
      url:             'https://plan-international.org',
      tier:            'major',
      trust_score:     0.89,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['human-rights', 'gender', 'education']),
      rss_feeds:       JSON.stringify(['https://plan-international.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'crin-gb',
      name:            'Child Rights International Network',
      description:     'Global network — child rights law, policy, advocacy, UN treaty body monitoring',
      url:             'https://home.crin.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['human-rights', 'politics', 'justice']),
      rss_feeds:       JSON.stringify(['https://home.crin.org/feed']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'ecpat-intl-th',
      name:            'ECPAT International',
      description:     'Global network ending sexual exploitation of children — online safety, trafficking, tourism',
      url:             'https://ecpat.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'TH',
      categories:      JSON.stringify(['human-rights', 'security', 'technology']),
      rss_feeds:       JSON.stringify(['https://ecpat.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },

    // ── Polar Geopolitics ─────────────────────────────────────────────────
    {
      slug:            'arctic-institute-us',
      name:            'The Arctic Institute',
      description:     'Washington DC-based think tank — Arctic geopolitics, governance, climate security, shipping routes',
      url:             'https://www.thearcticinstitute.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'climate', 'security']),
      rss_feeds:       JSON.stringify(['https://www.thearcticinstitute.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'polar-connection',
      name:            'The Polar Connection',
      description:     'Independent platform bridging Arctic and Antarctic policy — governance, science, indigenous issues',
      url:             'https://polarconnection.org',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['geopolitics', 'climate', 'science']),
      rss_feeds:       JSON.stringify(['https://polarconnection.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'high-north-news-no-2',
      name:            'High North News — Geopolitics',
      description:     'Norwegian outlet covering Arctic geopolitics, Northern Sea Route, Svalbard, Russia-NATO Arctic',
      url:             'https://www.highnorthnews.com',
      tier:            'major',
      trust_score:     0.85,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['geopolitics', 'security', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.highnorthnews.com/en/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'wilson-center-polar-us',
      name:            'Wilson Center — Polar Institute',
      description:     'Nonpartisan policy research on Arctic and Antarctic — climate, governance, security, science',
      url:             'https://www.wilsoncenter.org/program/polar-institute',
      tier:            'premium',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'climate', 'science']),
      rss_feeds:       JSON.stringify(['https://www.wilsoncenter.org/rss/polar-institute']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'spri-gb',
      name:            'Scott Polar Research Institute',
      description:     'Cambridge University institute — polar science, ice sheet dynamics, Arctic/Antarctic policy',
      url:             'https://www.spri.cam.ac.uk',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['science', 'climate', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.spri.cam.ac.uk/news/rss']),
      scrape_interval: 7200,
      active:          true,
    },

    // ── Legal & Justice Systems ───────────────────────────────────────────
    {
      slug:            'ijrc-us',
      name:            'International Justice Resource Center',
      description:     'US-based resource on international human rights law, regional courts, UN mechanisms',
      url:             'https://ijrcenter.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['justice', 'human-rights', 'politics']),
      rss_feeds:       JSON.stringify(['https://ijrcenter.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'ijm-us',
      name:            'International Justice Monitor',
      description:     'Open Society-funded — coverage of international criminal tribunals, ICC, hybrid courts',
      url:             'https://www.ijmonitor.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['justice', 'conflict', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.ijmonitor.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'icc-observer-nl',
      name:            'ICC Observer',
      description:     'Independent monitoring of International Criminal Court proceedings, indictments, and rulings',
      url:             'https://www.icc-cpi.int/news',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'NL',
      categories:      JSON.stringify(['justice', 'conflict', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.icc-cpi.int/rss/news']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'justiceinfo-ch',
      name:            'JusticeInfo.net',
      description:     'Fondation Hirondelle project — transitional justice, peace processes, truth commissions, reparations',
      url:             'https://www.justiceinfo.net',
      tier:            'major',
      trust_score:     0.88,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['justice', 'conflict', 'human-rights']),
      rss_feeds:       JSON.stringify(['https://www.justiceinfo.net/en/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'osji-us',
      name:            'Open Society Justice Initiative',
      description:     'Legal advocacy — international justice, freedom of expression, national security, anticorruption',
      url:             'https://www.justiceinitiative.org',
      tier:            'premium',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['justice', 'human-rights', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.justiceinitiative.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Biosecurity & Dual-Use Research ───────────────────────────────────
    {
      slug:            'jhu-chs-us',
      name:            'Johns Hopkins Center for Health Security',
      description:     'Leading biosecurity research centre — pandemic preparedness, biodefense, global health security',
      url:             'https://centerforhealthsecurity.org',
      tier:            'premium',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://centerforhealthsecurity.org/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'nti-bio-us',
      name:            'NTI — Nuclear Threat Initiative (Biosecurity)',
      description:     'NTI biosecurity program — biological threats, Global Health Security Index, dual-use governance',
      url:             'https://www.nti.org/area/biological/',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://www.nti.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'bulletin-bio-us',
      name:            'Bulletin of the Atomic Scientists — Biosecurity',
      description:     'Doomsday Clock publisher — biosecurity analysis, dual-use research oversight, pathogen policy',
      url:             'https://thebulletin.org/topic/biosecurity/',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://thebulletin.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'ghsi-jhu-us',
      name:            'Global Health Security Index',
      description:     'JHU/NTI/EIU assessment of 195 countries\' health security capabilities — preparedness benchmarking',
      url:             'https://www.ghsindex.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://www.ghsindex.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },
    {
      slug:            'vertic-gb',
      name:            'VERTIC — Verification Research, Training and Information Centre',
      description:     'UK charity — arms control verification, biosecurity legislation, chemical weapons compliance',
      url:             'https://www.vertic.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['security', 'science', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.vertic.org/feed/']),
      scrape_interval: 7200,
      active:          true,
    },

    // ── African Tech & Innovation ─────────────────────────────────────────
    {
      slug:            'techcabal-ng',
      name:            'TechCabal',
      description:     'African technology news — startups, fintech, digital economy, pan-African tech ecosystem',
      url:             'https://techcabal.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['technology', 'economy', 'innovation']),
      rss_feeds:       JSON.stringify(['https://techcabal.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'disrupt-africa-za',
      name:            'Disrupt Africa',
      description:     'African startup and venture capital news — funding rounds, ecosystem mapping, unicorn tracking',
      url:             'https://disrupt-africa.com',
      tier:            'major',
      trust_score:     0.83,
      language:        'en',
      country:         'ZA',
      categories:      JSON.stringify(['technology', 'economy', 'innovation']),
      rss_feeds:       JSON.stringify(['https://disrupt-africa.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'iafrikan-za',
      name:            'iAfrikan',
      description:     'African tech, media, and telecom news — mobile money, broadband, digital transformation',
      url:             'https://iafrikan.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'ZA',
      categories:      JSON.stringify(['technology', 'economy', 'telecom']),
      rss_feeds:       JSON.stringify(['https://iafrikan.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'digest-africa-ug',
      name:            'Digest Africa',
      description:     'East African tech and startup intelligence — funding data, ecosystem reports, investment trends',
      url:             'https://digestafrica.com',
      tier:            'specialised',
      trust_score:     0.81,
      language:        'en',
      country:         'UG',
      categories:      JSON.stringify(['technology', 'economy', 'innovation']),
      rss_feeds:       JSON.stringify(['https://digestafrica.com/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'weetracker-ng',
      name:            'WeeTracker',
      description:     'African startup and venture ecosystem coverage — deal flow, founder profiles, market analysis',
      url:             'https://weetracker.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['technology', 'economy', 'innovation']),
      rss_feeds:       JSON.stringify(['https://weetracker.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
  ]

  // Idempotent: ON CONFLICT(slug) DO NOTHING
  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'unhcr-stories', 'mixed-migration-centre', 'ecre-eu', 'migration-policy-inst-us', 'refugees-intl-us',
    'mining-com-global', 'irma-global', 'resource-world-ca', 'crma-eu', 'benchmark-minerals-gb',
    'indian-country-today-us', 'nitv-au', 'whakaata-maori-nz', 'first-nations-drum-ca', 'intercontinental-cry-2',
    'payload-space-us', 'via-satellite-us', 'satnews-us', 'space-intel-report-us', 'espi-at',
    'insight-crime-us', 'gi-toc-ch', 'fatf-fr', 'basel-institute-ch', 'acams-us',
    'unicef-news', 'save-children-gb', 'plan-intl-gb', 'crin-gb', 'ecpat-intl-th',
    'arctic-institute-us', 'polar-connection', 'high-north-news-no-2', 'wilson-center-polar-us', 'spri-gb',
    'ijrc-us', 'ijm-us', 'icc-observer-nl', 'justiceinfo-ch', 'osji-us',
    'jhu-chs-us', 'nti-bio-us', 'bulletin-bio-us', 'ghsi-jhu-us', 'vertic-gb',
    'techcabal-ng', 'disrupt-africa-za', 'iafrikan-za', 'digest-africa-ug', 'weetracker-ng',
  ]
  await knex('sources').whereIn('slug', slugs).del()
}
