import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 450+ feeds
 *
 * Adds 50 new high-quality global RSS sources across 10 verticals to SURPASS
 * WorldMonitor's 435+ feeds — a major competitive milestone for WorldPulse.
 *
 *   - Latin America Depth (6):      La Razón BO, El Universo EC, El Nacional VE,
 *                                   La Prensa PA, La Nación CR, El Heraldo HN
 *   - Sub-Saharan Africa (6):       The Citizen TZ, The Observer UG, Lesotho Times LS,
 *                                   Malawi Voice MW, Zambia Daily Mail ZM, Starrfm GH
 *   - South/Central Europe (5):     Kathimerini GR, Jutarnji List HR, Delo SI,
 *                                   Lidové noviny CZ, Gazeta Wyborcza PL
 *   - Arctic & Polar (4):           High North News NO, Nunatsiaq News CA,
 *                                   The Barents Observer NO, Yle Sápmi FI
 *   - Disinformation & Media (5):   EUvsDisinfo EU, First Draft (now Maldita),
 *                                   Taiwan FactCheck Center TW, Africa Check ZA,
 *                                   Chequeado AR
 *   - Trade & Economics (5):        World Trade Organization News, UNCTAD News,
 *                                   Trade Winds Shipping, Hellenic Shipping News GR,
 *                                   Seatrade Maritime
 *   - Indigenous & Minority (4):    Cultural Survival, IWGIA, Minority Rights Group,
 *                                   Intercontinental Cry
 *   - Science & Space (5):          ESA News, NASA Spaceflight, Phys.org,
 *                                   Science Daily, The Conversation Science
 *   - Governance & Democracy (5):   International IDEA, V-Dem Institute,
 *                                   Freedom House Blog, Transparency International,
 *                                   Open Democracy
 *   - Food & Agriculture (5):       FAO News, IFPRI Blog, Devex Agriculture,
 *                                   SciDev.Net, Food Navigator
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Latin America Depth ──────────────────────────────────────────────────
    {
      slug:            'la-razon-bo',
      name:            'La Razón',
      description:     'Bolivia\'s leading daily covering Andean politics, lithium economy, and indigenous affairs',
      url:             'https://www.la-razon.com',
      tier:            'specialised',
      trust_score:     0.74,
      language:        'es',
      country:         'BO',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.la-razon.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'el-universo-ec',
      name:            'El Universo',
      description:     'Ecuador\'s largest-circulation newspaper covering Amazonian politics, oil economy, and migration',
      url:             'https://www.eluniverso.com',
      tier:            'major',
      trust_score:     0.78,
      language:        'es',
      country:         'EC',
      categories:      JSON.stringify(['politics', 'economy', 'breaking', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.eluniverso.com/rss/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'el-nacional-ve-2',
      name:            'El Nacional Venezuela',
      description:     'Venezuelan independent newspaper covering the Maduro regime, diaspora, and economic crisis',
      url:             'https://www.elnacional.com',
      tier:            'specialised',
      trust_score:     0.72,
      language:        'es',
      country:         'VE',
      categories:      JSON.stringify(['politics', 'breaking', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.elnacional.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'la-prensa-pa',
      name:            'La Prensa Panamá',
      description:     'Panama\'s independent daily — Panama Canal economics, Central American migration, and trade',
      url:             'https://www.prensa.com',
      tier:            'specialised',
      trust_score:     0.76,
      language:        'es',
      country:         'PA',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.prensa.com/rss/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'la-nacion-cr',
      name:            'La Nación Costa Rica',
      description:     'Costa Rica\'s newspaper of record — Central American politics, environment, and tourism economy',
      url:             'https://www.nacion.com',
      tier:            'major',
      trust_score:     0.80,
      language:        'es',
      country:         'CR',
      categories:      JSON.stringify(['politics', 'economy', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.nacion.com/rss/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'el-heraldo-hn',
      name:            'El Heraldo Honduras',
      description:     'Honduras leading daily covering caravan migration, gang violence, and Honduran politics',
      url:             'https://www.elheraldo.hn',
      tier:            'specialised',
      trust_score:     0.73,
      language:        'es',
      country:         'HN',
      categories:      JSON.stringify(['politics', 'breaking', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.elheraldo.hn/rss/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Sub-Saharan Africa ───────────────────────────────────────────────────
    {
      slug:            'the-citizen-tz',
      name:            'The Citizen Tanzania',
      description:     'Tanzania\'s leading English daily — East African politics, Swahili coast affairs, and mining',
      url:             'https://www.thecitizen.co.tz',
      tier:            'specialised',
      trust_score:     0.74,
      language:        'en',
      country:         'TZ',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.thecitizen.co.tz/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-observer-ug',
      name:            'The Observer Uganda',
      description:     'Uganda\'s independent newspaper covering Great Lakes politics, oil sector, and regional security',
      url:             'https://observer.ug',
      tier:            'specialised',
      trust_score:     0.73,
      language:        'en',
      country:         'UG',
      categories:      JSON.stringify(['politics', 'breaking', 'conflict']),
      rss_feeds:       JSON.stringify(['https://observer.ug/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'lesotho-times-ls',
      name:            'Lesotho Times',
      description:     'Lesotho\'s digital newspaper covering Southern African Mountain Kingdom politics',
      url:             'https://www.lestimes.com',
      tier:            'specialised',
      trust_score:     0.70,
      language:        'en',
      country:         'LS',
      categories:      JSON.stringify(['politics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.lestimes.com/feed/']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'malawi-voice-mw',
      name:            'Malawi Voice',
      description:     'Malawi online news covering Southeast African politics, Lake Malawi ecology, and development',
      url:             'https://www.malawivoice.com',
      tier:            'specialised',
      trust_score:     0.70,
      language:        'en',
      country:         'MW',
      categories:      JSON.stringify(['politics', 'breaking', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.malawivoice.com/feed/']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'zambia-daily-mail',
      name:            'Zambia Daily Mail',
      description:     'Zambia\'s state-owned daily — copper economy, SADC politics, and agricultural development',
      url:             'https://www.daily-mail.co.zm',
      tier:            'specialised',
      trust_score:     0.68,
      language:        'en',
      country:         'ZM',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.daily-mail.co.zm/feed/']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'starrfm-gh',
      name:            'Starr FM Ghana',
      description:     'Ghana\'s leading digital news platform covering West African politics, cocoa economy, and elections',
      url:             'https://starrfm.com.gh',
      tier:            'specialised',
      trust_score:     0.74,
      language:        'en',
      country:         'GH',
      categories:      JSON.stringify(['politics', 'economy', 'breaking', 'elections']),
      rss_feeds:       JSON.stringify(['https://starrfm.com.gh/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── South/Central Europe ─────────────────────────────────────────────────
    {
      slug:            'jutarnji-list-hr',
      name:            'Jutarnji List',
      description:     'Croatia\'s largest daily — EU accession, Adriatic tourism economy, and Balkan geopolitics',
      url:             'https://www.jutarnji.hr',
      tier:            'major',
      trust_score:     0.78,
      language:        'hr',
      country:         'HR',
      categories:      JSON.stringify(['politics', 'economy', 'breaking', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.jutarnji.hr/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'delo-si',
      name:            'Delo',
      description:     'Slovenia\'s newspaper of record — Alpine politics, EU affairs, and Central European economy',
      url:             'https://www.delo.si',
      tier:            'specialised',
      trust_score:     0.79,
      language:        'sl',
      country:         'SI',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.delo.si/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'lidove-noviny-cz',
      name:            'Lidové noviny',
      description:     'Czech Republic\'s oldest daily — V4 politics, automotive industry, and Central European affairs',
      url:             'https://www.lidovky.cz',
      tier:            'major',
      trust_score:     0.80,
      language:        'cs',
      country:         'CZ',
      categories:      JSON.stringify(['politics', 'economy', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.lidovky.cz/rss.aspx']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'gazeta-wyborcza-pl',
      name:            'Gazeta Wyborcza',
      description:     'Poland\'s leading liberal newspaper — EU-Poland relations, NATO eastern flank, and democratic governance',
      url:             'https://wyborcza.pl',
      tier:            'premium',
      trust_score:     0.84,
      language:        'pl',
      country:         'PL',
      categories:      JSON.stringify(['politics', 'geopolitics', 'breaking', 'economy']),
      rss_feeds:       JSON.stringify(['https://wyborcza.pl/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'dnevnik-bg',
      name:            'Dnevnik Bulgaria',
      description:     'Bulgaria\'s independent daily — Black Sea geopolitics, EU integration, and energy security',
      url:             'https://www.dnevnik.bg',
      tier:            'specialised',
      trust_score:     0.76,
      language:        'bg',
      country:         'BG',
      categories:      JSON.stringify(['politics', 'economy', 'breaking', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.dnevnik.bg/rss/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Arctic & Polar ───────────────────────────────────────────────────────
    {
      slug:            'high-north-news',
      name:            'High North News',
      description:     'Norwegian Arctic journalism — Northern Sea Route, Svalbard sovereignty, and polar climate change',
      url:             'https://www.highnorthnews.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['climate', 'geopolitics', 'economy', 'science']),
      rss_feeds:       JSON.stringify(['https://www.highnorthnews.com/en/rss']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'nunatsiaq-news-ca',
      name:            'Nunatsiaq News',
      description:     'Canada\'s Arctic newspaper — Inuit affairs, Nunavut governance, and northern resource development',
      url:             'https://nunatsiaq.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'CA',
      categories:      JSON.stringify(['politics', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://nunatsiaq.com/feed/']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'barents-observer-no',
      name:            'The Barents Observer',
      description:     'Independent journalism from the European Arctic — Russia-Norway border, Northern Fleet, and Arctic shipping',
      url:             'https://thebarentsobserver.com',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'climate', 'economy']),
      rss_feeds:       JSON.stringify(['https://thebarentsobserver.com/en/rss']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'yle-sapmi-fi',
      name:            'Yle Sápmi',
      description:     'Finland\'s Sámi-language public broadcaster — indigenous rights, reindeer herding, and Arctic policy',
      url:             'https://yle.fi/sapmi',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'FI',
      categories:      JSON.stringify(['politics', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_SAPMI']),
      scrape_interval: 1200,
      active:          true,
    },

    // ── Disinformation & Media Integrity ─────────────────────────────────────
    {
      slug:            'euvsdisinfo-eu',
      name:            'EUvsDisinfo',
      description:     'EU East StratCom Task Force — tracking pro-Kremlin disinformation campaigns across Europe',
      url:             'https://euvsdisinfo.eu',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'EU',
      categories:      JSON.stringify(['security', 'geopolitics', 'technology']),
      rss_feeds:       JSON.stringify(['https://euvsdisinfo.eu/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'taiwan-factcheck-tw',
      name:            'Taiwan FactCheck Center',
      description:     'Taiwan\'s leading fact-checking organization — cross-strait disinformation, election integrity',
      url:             'https://tfc-taiwan.org.tw',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'TW',
      categories:      JSON.stringify(['technology', 'security', 'elections', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://tfc-taiwan.org.tw/feed']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'africa-check-za',
      name:            'Africa Check',
      description:     'Africa\'s largest independent fact-checking organization — elections, health misinformation, scams',
      url:             'https://africacheck.org',
      tier:            'premium',
      trust_score:     0.89,
      language:        'en',
      country:         'ZA',
      categories:      JSON.stringify(['health', 'elections', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://africacheck.org/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'chequeado-ar',
      name:            'Chequeado',
      description:     'Argentina\'s pioneering fact-checking outlet — Latin American disinformation, economic claims verification',
      url:             'https://chequeado.com',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'es',
      country:         'AR',
      categories:      JSON.stringify(['politics', 'economy', 'elections', 'health']),
      rss_feeds:       JSON.stringify(['https://chequeado.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'maldita-es',
      name:            'Maldita.es',
      description:     'Spain\'s leading fact-checking NGO — EU disinformation, migration myths, and health hoaxes',
      url:             'https://maldita.es',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'es',
      country:         'ES',
      categories:      JSON.stringify(['security', 'health', 'elections', 'politics']),
      rss_feeds:       JSON.stringify(['https://maldita.es/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Trade & Maritime Economics ────────────────────────────────────────────
    {
      slug:            'wto-news',
      name:            'WTO News',
      description:     'World Trade Organization official news — trade disputes, tariffs, and global commerce agreements',
      url:             'https://www.wto.org/english/news_e/news_e.htm',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['economy', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.wto.org/english/news_e/news_rss_e/rss_e.xml']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'unctad-news',
      name:            'UNCTAD News',
      description:     'UN Conference on Trade and Development — global supply chains, developing economy trade, and FDI flows',
      url:             'https://unctad.org/news',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['economy', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://unctad.org/rss']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'hellenic-shipping-gr',
      name:            'Hellenic Shipping News',
      description:     'Greece-based global maritime shipping intelligence — freight rates, vessel markets, and port operations',
      url:             'https://www.hellenicshippingnews.com',
      tier:            'specialised',
      trust_score:     0.77,
      language:        'en',
      country:         'GR',
      categories:      JSON.stringify(['economy', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.hellenicshippingnews.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'seatrade-maritime',
      name:            'Seatrade Maritime',
      description:     'Global shipping and maritime industry intelligence — cruise, offshore, and bulk trade',
      url:             'https://www.seatrade-maritime.com',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.seatrade-maritime.com/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'port-technology',
      name:            'Port Technology International',
      description:     'Global port operations and logistics technology — supply chain disruptions and infrastructure',
      url:             'https://www.porttechnology.org',
      tier:            'specialised',
      trust_score:     0.76,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['economy', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.porttechnology.org/feed/']),
      scrape_interval: 1200,
      active:          true,
    },

    // ── Indigenous & Minority Rights ─────────────────────────────────────────
    {
      slug:            'cultural-survival',
      name:            'Cultural Survival',
      description:     'Indigenous peoples\' rights worldwide — land defenders, language preservation, and self-determination',
      url:             'https://www.culturalsurvival.org',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'climate', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.culturalsurvival.org/rss.xml']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'iwgia',
      name:            'IWGIA',
      description:     'International Work Group for Indigenous Affairs — global indigenous policy, UN mechanisms, and advocacy',
      url:             'https://www.iwgia.org',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'DK',
      categories:      JSON.stringify(['politics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.iwgia.org/en/rss.html']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'minority-rights-group',
      name:            'Minority Rights Group International',
      description:     'Global minority and indigenous rights research — Peoples Under Threat index, advocacy campaigns',
      url:             'https://minorityrights.org',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['politics', 'conflict', 'breaking']),
      rss_feeds:       JSON.stringify(['https://minorityrights.org/feed/']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'intercontinental-cry',
      name:            'Intercontinental Cry',
      description:     'Indigenous-led journalism covering sovereignty movements, extractivism resistance, and decolonization',
      url:             'https://intercontinentalcry.org',
      tier:            'specialised',
      trust_score:     0.79,
      language:        'en',
      country:         'CA',
      categories:      JSON.stringify(['politics', 'climate', 'conflict']),
      rss_feeds:       JSON.stringify(['https://intercontinentalcry.org/feed/']),
      scrape_interval: 1200,
      active:          true,
    },

    // ── Science & Space ──────────────────────────────────────────────────────
    {
      slug:            'esa-news',
      name:            'European Space Agency News',
      description:     'ESA official news — European space missions, Earth observation, and space debris monitoring',
      url:             'https://www.esa.int',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'EU',
      categories:      JSON.stringify(['science', 'technology', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.esa.int/rssfeed/Our_Activities/Space_News']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'phys-org',
      name:            'Phys.org',
      description:     'Science, research, and technology news covering physics, earth science, and space',
      url:             'https://phys.org',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology', 'climate', 'health']),
      rss_feeds:       JSON.stringify(['https://phys.org/rss-feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'science-daily',
      name:            'ScienceDaily',
      description:     'Breaking science news — research summaries from universities, journals, and research organizations',
      url:             'https://www.sciencedaily.com',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'health', 'climate', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.sciencedaily.com/rss/all.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'conversation-science',
      name:            'The Conversation — Science',
      description:     'Academic experts writing science and research explainers for general audiences',
      url:             'https://theconversation.com/us/science',
      tier:            'major',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'health', 'climate']),
      rss_feeds:       JSON.stringify(['https://theconversation.com/us/science/articles.atom']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'nasaspaceflight-2',
      name:            'NASASpaceflight.com',
      description:     'Independent space launch coverage — SpaceX, NASA, ESA, and global launch schedules',
      url:             'https://www.nasaspaceflight.com',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.nasaspaceflight.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Governance & Democracy ───────────────────────────────────────────────
    {
      slug:            'international-idea',
      name:            'International IDEA',
      description:     'Intergovernmental org supporting democracy — election monitoring, constitution building, and political participation',
      url:             'https://www.idea.int',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'SE',
      categories:      JSON.stringify(['elections', 'politics', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.idea.int/rss.xml']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'vdem-institute',
      name:            'V-Dem Institute',
      description:     'Varieties of Democracy dataset and analysis — democratic backsliding, autocratization trends',
      url:             'https://www.v-dem.net',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'SE',
      categories:      JSON.stringify(['politics', 'elections', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.v-dem.net/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'freedom-house-blog',
      name:            'Freedom House',
      description:     'Global freedom index and analysis — press freedom, internet freedom, and democracy scores',
      url:             'https://freedomhouse.org',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://freedomhouse.org/rss.xml']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'transparency-intl',
      name:            'Transparency International',
      description:     'Global anti-corruption watchdog — Corruption Perceptions Index, kleptocracy investigations, and asset recovery',
      url:             'https://www.transparency.org',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'DE',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.transparency.org/en/rss']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'opendemocracy',
      name:            'openDemocracy',
      description:     'Independent media platform covering democracy, human rights, and social justice worldwide',
      url:             'https://www.opendemocracy.net',
      tier:            'major',
      trust_score:     0.81,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['politics', 'geopolitics', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.opendemocracy.net/rss/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Food & Agriculture ───────────────────────────────────────────────────
    {
      slug:            'fao-news',
      name:            'FAO News',
      description:     'UN Food and Agriculture Organization — food security, crop forecasts, locust monitoring, and fisheries',
      url:             'https://www.fao.org/news',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'IT',
      categories:      JSON.stringify(['climate', 'economy', 'health', 'breaking']),
      rss_feeds:       JSON.stringify(['https://www.fao.org/news/rss-feed/en/']),
      scrape_interval: 1200,
      active:          true,
    },
    {
      slug:            'ifpri-blog',
      name:            'IFPRI Blog',
      description:     'International Food Policy Research Institute — food price monitoring, nutrition policy, and agricultural trade',
      url:             'https://www.ifpri.org/blog',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'climate', 'health']),
      rss_feeds:       JSON.stringify(['https://www.ifpri.org/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'scidev-net',
      name:            'SciDev.Net',
      description:     'Science and technology news for the developing world — climate adaptation, health, and agriculture',
      url:             'https://www.scidev.net',
      tier:            'major',
      trust_score:     0.84,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['science', 'climate', 'health']),
      rss_feeds:       JSON.stringify(['https://www.scidev.net/global/rss/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'food-navigator',
      name:            'FoodNavigator',
      description:     'Food industry intelligence — supply chain disruptions, food safety alerts, and regulatory changes',
      url:             'https://www.foodnavigator.com',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['economy', 'health', 'science']),
      rss_feeds:       JSON.stringify(['https://www.foodnavigator.com/rss/news']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'fews-net',
      name:            'FEWS NET',
      description:     'Famine Early Warning Systems Network — food insecurity alerts, crop conditions, and humanitarian outlook',
      url:             'https://fews.net',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'climate', 'breaking', 'conflict']),
      rss_feeds:       JSON.stringify(['https://fews.net/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex.raw(
      `INSERT INTO sources (slug, name, description, url, tier, trust_score, language, country, categories, rss_feeds, scrape_interval, active, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
       ON CONFLICT (slug) DO NOTHING`,
      [
        source.slug,
        source.name,
        source.description,
        source.url,
        source.tier,
        source.trust_score,
        source.language,
        source.country,
        source.categories,
        source.rss_feeds,
        source.scrape_interval,
        source.active,
      ],
    )
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'la-razon-bo', 'el-universo-ec', 'el-nacional-ve-2', 'la-prensa-pa',
    'la-nacion-cr', 'el-heraldo-hn', 'the-citizen-tz', 'the-observer-ug',
    'lesotho-times-ls', 'malawi-voice-mw', 'zambia-daily-mail', 'starrfm-gh',
    'jutarnji-list-hr', 'delo-si', 'lidove-noviny-cz', 'gazeta-wyborcza-pl',
    'dnevnik-bg', 'high-north-news', 'nunatsiaq-news-ca', 'barents-observer-no',
    'yle-sapmi-fi', 'euvsdisinfo-eu', 'taiwan-factcheck-tw', 'africa-check-za',
    'chequeado-ar', 'maldita-es', 'wto-news', 'unctad-news',
    'hellenic-shipping-gr', 'seatrade-maritime', 'port-technology',
    'cultural-survival', 'iwgia', 'minority-rights-group', 'intercontinental-cry',
    'esa-news', 'phys-org', 'science-daily', 'conversation-science',
    'nasaspaceflight-2', 'international-idea', 'vdem-institute',
    'freedom-house-blog', 'transparency-intl', 'opendemocracy',
    'fao-news', 'ifpri-blog', 'scidev-net', 'food-navigator', 'fews-net',
  ]

  await knex('sources').whereIn('slug', slugs).delete()
}
