import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 550+ feeds
 *
 * Adds 50 new high-quality global RSS sources across 10 verticals to extend
 * WorldPulse's leadership over WorldMonitor (now 550+ vs 435+ = 1.26x advantage).
 *
 *   - West Africa Anglophone (5):    Premium Post NG, GhanaWeb GH, Sierra Leone
 *                                    Telegraph SL, Liberian Observer LR, The Gambia
 *                                    Standard GM
 *   - Francophone Africa (5):        Jeune Afrique FR, RFI Afrique FR, Le Monde
 *                                    Afrique FR, Abidjan.net CI, Le Faso BF
 *   - Caribbean & Small Island (5):  Jamaica Gleaner JM, Trinidad Express TT,
 *                                    Barbados Today BB, St. Lucia Times LC,
 *                                    Guyana Chronicle GY
 *   - Conflict & Peace Studies (5):  International Crisis Group, Peace Research
 *                                    Institute Oslo, Stockholm Forum, Conciliation
 *                                    Resources, Saferworld
 *   - Supply Chain & Trade (5):      Supply Chain Dive US, FreightWaves US,
 *                                    The Loadstar GB, Journal of Commerce US,
 *                                    Container News GB
 *   - Education & Development (5):   UNESCO News, University World News ZA,
 *                                    Times Higher Education GB, The PIE News GB,
 *                                    Global Partnership for Education
 *   - Wildlife & Conservation (5):   Mongabay US, TRAFFIC Wildlife Trade,
 *                                    WWF News, IUCN News, Conservation International
 *   - Disability & Inclusion (5):    Disability Rights International, Inclusive
 *                                    City Maker, Leonard Cheshire GB, Light for
 *                                    the World AT, International Disability Alliance
 *   - Corruption & Transparency (5): OCCRP, Global Witness GB, Tax Justice
 *                                    Network GB, Stolen Asset Recovery (StAR),
 *                                    Anti-Corruption Digest
 *   - Artificial Intelligence (5):   The AI Index (Stanford), AI News GB, MIT
 *                                    Technology Review AI, VentureBeat AI, The Batch
 *                                    (DeepLearning.AI)
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── West Africa Anglophone ───────────────────────────────────────────────
    {
      slug:            'premium-times-ng',
      name:            'Premium Times Nigeria',
      description:     'Independent investigative journalism from Nigeria — politics, business, health, sports',
      url:             'https://www.premiumtimesng.com',
      tier:            'premium',
      trust_score:     0.82,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['politics', 'economy', 'conflict', 'health']),
      rss_feeds:       JSON.stringify(['https://www.premiumtimesng.com/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'ghanaweb-gh',
      name:            'GhanaWeb',
      description:     'Ghana\'s leading news portal — politics, business, entertainment, diaspora',
      url:             'https://www.ghanaweb.com',
      tier:            'major',
      trust_score:     0.75,
      language:        'en',
      country:         'GH',
      categories:      JSON.stringify(['politics', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://www.ghanaweb.com/GhanaHomePage/NewsArchive/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'sierra-leone-telegraph-sl',
      name:            'Sierra Leone Telegraph',
      description:     'Independent news from Sierra Leone — politics, economy, human rights',
      url:             'https://www.thesierraleonetelegraph.com',
      tier:            'specialised',
      trust_score:     0.72,
      language:        'en',
      country:         'SL',
      categories:      JSON.stringify(['politics', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://www.thesierraleonetelegraph.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'liberian-observer-lr',
      name:            'Liberian Observer',
      description:     'Liberia\'s oldest independent daily — politics, business, opinion',
      url:             'https://www.liberianobserver.com',
      tier:            'specialised',
      trust_score:     0.70,
      language:        'en',
      country:         'LR',
      categories:      JSON.stringify(['politics', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://www.liberianobserver.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'the-gambia-standard-gm',
      name:            'The Standard (Gambia)',
      description:     'The Gambia\'s independent newspaper — politics, human rights, West African affairs',
      url:             'https://standard.gm',
      tier:            'specialised',
      trust_score:     0.70,
      language:        'en',
      country:         'GM',
      categories:      JSON.stringify(['politics', 'society', 'conflict']),
      rss_feeds:       JSON.stringify(['https://standard.gm/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Francophone Africa ───────────────────────────────────────────────────
    {
      slug:            'jeune-afrique-fr',
      name:            'Jeune Afrique',
      description:     'Premier pan-African francophone magazine — politics, economy, culture across 54 nations',
      url:             'https://www.jeuneafrique.com',
      tier:            'premium',
      trust_score:     0.85,
      language:        'fr',
      country:         'FR',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics', 'society']),
      rss_feeds:       JSON.stringify(['https://www.jeuneafrique.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'rfi-afrique-fr',
      name:            'RFI Afrique',
      description:     'Radio France Internationale Africa desk — breaking news, analysis, culture in French',
      url:             'https://www.rfi.fr/fr/afrique/',
      tier:            'premium',
      trust_score:     0.88,
      language:        'fr',
      country:         'FR',
      categories:      JSON.stringify(['politics', 'conflict', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://www.rfi.fr/fr/afrique/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'le-monde-afrique-fr',
      name:            'Le Monde Afrique',
      description:     'Le Monde\'s Africa vertical — in-depth investigation, politics, economy, francophone coverage',
      url:             'https://www.lemonde.fr/afrique/',
      tier:            'premium',
      trust_score:     0.90,
      language:        'fr',
      country:         'FR',
      categories:      JSON.stringify(['politics', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.lemonde.fr/afrique/rss_full.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'abidjan-net-ci',
      name:            'Abidjan.net',
      description:     'Côte d\'Ivoire\'s leading digital news platform — politics, economy, sports, culture',
      url:             'https://news.abidjan.net',
      tier:            'major',
      trust_score:     0.73,
      language:        'fr',
      country:         'CI',
      categories:      JSON.stringify(['politics', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://news.abidjan.net/rss/abidjan.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'le-faso-bf',
      name:            'LeFaso.net',
      description:     'Burkina Faso\'s leading online news portal — politics, security, Sahel affairs',
      url:             'https://lefaso.net',
      tier:            'specialised',
      trust_score:     0.70,
      language:        'fr',
      country:         'BF',
      categories:      JSON.stringify(['politics', 'conflict', 'society']),
      rss_feeds:       JSON.stringify(['https://lefaso.net/spip.php?page=backend']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Caribbean & Small Island States ──────────────────────────────────────
    {
      slug:            'jamaica-gleaner-jm',
      name:            'Jamaica Gleaner',
      description:     'Jamaica\'s oldest newspaper (est. 1834) — politics, economy, sports, Caribbean affairs',
      url:             'https://jamaica-gleaner.com',
      tier:            'major',
      trust_score:     0.80,
      language:        'en',
      country:         'JM',
      categories:      JSON.stringify(['politics', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://jamaica-gleaner.com/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'trinidad-express-tt',
      name:            'Trinidad Express',
      description:     'Trinidad and Tobago daily — politics, crime, energy sector, Caribbean economy',
      url:             'https://trinidadexpress.com',
      tier:            'major',
      trust_score:     0.76,
      language:        'en',
      country:         'TT',
      categories:      JSON.stringify(['politics', 'economy', 'energy']),
      rss_feeds:       JSON.stringify(['https://trinidadexpress.com/search/?f=rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'barbados-today-bb',
      name:            'Barbados Today',
      description:     'Barbados leading digital news — politics, tourism economy, climate, CARICOM affairs',
      url:             'https://barbadostoday.bb',
      tier:            'specialised',
      trust_score:     0.74,
      language:        'en',
      country:         'BB',
      categories:      JSON.stringify(['politics', 'economy', 'climate']),
      rss_feeds:       JSON.stringify(['https://barbadostoday.bb/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'st-lucia-times-lc',
      name:            'St. Lucia Times',
      description:     'Saint Lucia\'s premier online news — politics, tourism, crime, Eastern Caribbean',
      url:             'https://stluciatimes.com',
      tier:            'specialised',
      trust_score:     0.72,
      language:        'en',
      country:         'LC',
      categories:      JSON.stringify(['politics', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://stluciatimes.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'guyana-chronicle-gy',
      name:            'Guyana Chronicle',
      description:     'Guyana\'s national newspaper — politics, oil & gas economy, agriculture, CARICOM',
      url:             'https://guyanachronicle.com',
      tier:            'major',
      trust_score:     0.73,
      language:        'en',
      country:         'GY',
      categories:      JSON.stringify(['politics', 'economy', 'energy']),
      rss_feeds:       JSON.stringify(['https://guyanachronicle.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Conflict & Peace Studies ─────────────────────────────────────────────
    {
      slug:            'international-crisis-group',
      name:            'International Crisis Group',
      description:     'Leading conflict prevention organization — analysis, early warnings, peace mediation across 70+ crises',
      url:             'https://www.crisisgroup.org',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.crisisgroup.org/latest-updates/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'prio-no',
      name:            'Peace Research Institute Oslo (PRIO)',
      description:     'Norwegian peace research institute — armed conflict data, migration, peacebuilding, gender',
      url:             'https://www.prio.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'NO',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'society']),
      rss_feeds:       JSON.stringify(['https://www.prio.org/rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'sipri-se',
      name:            'Stockholm International Peace Research Institute (SIPRI)',
      description:     'World\'s leading arms and disarmament research institute — military expenditure, arms transfers, conflict',
      url:             'https://www.sipri.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'SE',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'military']),
      rss_feeds:       JSON.stringify(['https://www.sipri.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'conciliation-resources-gb',
      name:            'Conciliation Resources',
      description:     'UK-based peacebuilding charity — conflict analysis, dialogue, inclusive peace processes',
      url:             'https://www.c-r.org',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['conflict', 'society', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.c-r.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'saferworld-gb',
      name:            'Saferworld',
      description:     'International peacebuilding organization — conflict prevention, security, justice, gender',
      url:             'https://www.saferworld.org.uk',
      tier:            'specialised',
      trust_score:     0.84,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['conflict', 'society', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.saferworld.org.uk/feed']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Supply Chain & Trade ─────────────────────────────────────────────────
    {
      slug:            'supply-chain-dive-us',
      name:            'Supply Chain Dive',
      description:     'US supply chain intelligence — logistics, procurement, warehousing, disruption tracking',
      url:             'https://www.supplychaindive.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'trade', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.supplychaindive.com/feeds/news/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'freightwaves-us',
      name:            'FreightWaves',
      description:     'Real-time freight market intelligence — trucking, maritime, air cargo, supply chain data',
      url:             'https://www.freightwaves.com',
      tier:            'major',
      trust_score:     0.80,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'trade', 'maritime']),
      rss_feeds:       JSON.stringify(['https://www.freightwaves.com/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-loadstar-gb',
      name:            'The Loadstar',
      description:     'UK-based global freight and logistics news — container shipping, air cargo, supply chains',
      url:             'https://theloadstar.com',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['economy', 'trade', 'maritime']),
      rss_feeds:       JSON.stringify(['https://theloadstar.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'journal-of-commerce-us',
      name:            'Journal of Commerce',
      description:     'IHS Markit trade publication — container shipping, port operations, trade policy, customs',
      url:             'https://www.joc.com',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'trade', 'maritime']),
      rss_feeds:       JSON.stringify(['https://www.joc.com/rss/all']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'container-news-gb',
      name:            'Container News',
      description:     'Global container shipping and logistics intelligence — rates, port congestion, fleet tracking',
      url:             'https://container-news.com',
      tier:            'specialised',
      trust_score:     0.76,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['economy', 'trade', 'maritime']),
      rss_feeds:       JSON.stringify(['https://container-news.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Education & Development ──────────────────────────────────────────────
    {
      slug:            'unesco-news',
      name:            'UNESCO News',
      description:     'United Nations educational, scientific & cultural organization — education, heritage, science, culture',
      url:             'https://www.unesco.org/en/articles',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['society', 'education', 'science']),
      rss_feeds:       JSON.stringify(['https://www.unesco.org/en/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'university-world-news-za',
      name:            'University World News',
      description:     'Global higher education news — research policy, academic freedom, university rankings, mobility',
      url:             'https://www.universityworldnews.com',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'ZA',
      categories:      JSON.stringify(['education', 'society', 'science']),
      rss_feeds:       JSON.stringify(['https://www.universityworldnews.com/rss.php']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'times-higher-education-gb',
      name:            'Times Higher Education',
      description:     'UK-based global university news — rankings, research, policy, academic freedom, student mobility',
      url:             'https://www.timeshighereducation.com',
      tier:            'premium',
      trust_score:     0.85,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['education', 'society', 'science']),
      rss_feeds:       JSON.stringify(['https://www.timeshighereducation.com/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'the-pie-news-gb',
      name:            'The PIE News',
      description:     'International education industry news — study abroad, ed-tech, recruitment, policy',
      url:             'https://thepienews.com',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['education', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://thepienews.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'global-partnership-education',
      name:            'Global Partnership for Education',
      description:     'Multilateral partnership funding education in 90 low-income countries — data, advocacy, results',
      url:             'https://www.globalpartnership.org',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['education', 'society', 'development']),
      rss_feeds:       JSON.stringify(['https://www.globalpartnership.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Wildlife & Conservation ──────────────────────────────────────────────
    {
      slug:            'mongabay-us',
      name:            'Mongabay',
      description:     'Non-profit conservation and environmental science news — deforestation, biodiversity, wildlife trade',
      url:             'https://news.mongabay.com',
      tier:            'premium',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['environment', 'science', 'society']),
      rss_feeds:       JSON.stringify(['https://news.mongabay.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'traffic-wildlife-trade',
      name:            'TRAFFIC',
      description:     'Global wildlife trade monitoring network — CITES, illegal trafficking, conservation enforcement',
      url:             'https://www.traffic.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['environment', 'society', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.traffic.org/news/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'wwf-news',
      name:            'WWF News',
      description:     'World Wildlife Fund global news — climate, oceans, forests, species, sustainability',
      url:             'https://www.worldwildlife.org/stories',
      tier:            'premium',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['environment', 'climate', 'society']),
      rss_feeds:       JSON.stringify(['https://www.worldwildlife.org/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'iucn-news',
      name:            'IUCN News',
      description:     'International Union for Conservation of Nature — Red List, protected areas, ecosystem restoration',
      url:             'https://www.iucn.org/news',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['environment', 'science', 'society']),
      rss_feeds:       JSON.stringify(['https://www.iucn.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'conservation-international',
      name:            'Conservation International',
      description:     'Global conservation organization — biodiversity hotspots, climate, indigenous partnerships, ocean health',
      url:             'https://www.conservation.org/blog',
      tier:            'major',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['environment', 'climate', 'science']),
      rss_feeds:       JSON.stringify(['https://www.conservation.org/blog/feed']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Disability & Inclusion ───────────────────────────────────────────────
    {
      slug:            'disability-rights-intl',
      name:            'Disability Rights International',
      description:     'Global disability rights advocacy — institutional reform, inclusive education, legal capacity',
      url:             'https://www.driadvocacy.org',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['society', 'health', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.driadvocacy.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'inclusive-city-maker',
      name:            'Inclusive City Maker',
      description:     'Urban accessibility and inclusive design — transportation, housing, digital inclusion, universal design',
      url:             'https://www.integratedtransport.co.uk',
      tier:            'specialised',
      trust_score:     0.72,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['society', 'technology', 'urban']),
      rss_feeds:       JSON.stringify(['https://www.integratedtransport.co.uk/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'leonard-cheshire-gb',
      name:            'Leonard Cheshire',
      description:     'UK disability charity — employment, education, assistive technology, global South programs',
      url:             'https://www.leonardcheshire.org',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['society', 'health', 'education']),
      rss_feeds:       JSON.stringify(['https://www.leonardcheshire.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'light-for-the-world-at',
      name:            'Light for the World',
      description:     'International disability inclusion NGO — eye health, education, livelihoods in Africa and Asia',
      url:             'https://www.light-for-the-world.org',
      tier:            'specialised',
      trust_score:     0.80,
      language:        'en',
      country:         'AT',
      categories:      JSON.stringify(['society', 'health', 'development']),
      rss_feeds:       JSON.stringify(['https://www.light-for-the-world.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'intl-disability-alliance',
      name:            'International Disability Alliance',
      description:     'Network of global disability organizations — CRPD advocacy, UN engagement, inclusive development',
      url:             'https://www.internationaldisabilityalliance.org',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'CH',
      categories:      JSON.stringify(['society', 'politics', 'development']),
      rss_feeds:       JSON.stringify(['https://www.internationaldisabilityalliance.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Corruption & Transparency ────────────────────────────────────────────
    {
      slug:            'occrp',
      name:            'Organized Crime and Corruption Reporting Project (OCCRP)',
      description:     'Global investigative journalism network — cross-border corruption, money laundering, organized crime',
      url:             'https://www.occrp.org',
      tier:            'premium',
      trust_score:     0.93,
      language:        'en',
      country:         'NL',
      categories:      JSON.stringify(['politics', 'economy', 'conflict', 'society']),
      rss_feeds:       JSON.stringify(['https://www.occrp.org/en/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'global-witness-gb',
      name:            'Global Witness',
      description:     'Investigative NGO — natural resource corruption, land rights defenders, corporate accountability',
      url:             'https://www.globalwitness.org',
      tier:            'premium',
      trust_score:     0.90,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['politics', 'economy', 'environment', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.globalwitness.org/en/rss/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'tax-justice-network-gb',
      name:            'Tax Justice Network',
      description:     'Research and advocacy on tax havens, illicit financial flows, financial secrecy, corporate transparency',
      url:             'https://taxjustice.net',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['economy', 'politics', 'society']),
      rss_feeds:       JSON.stringify(['https://taxjustice.net/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'star-stolen-asset-recovery',
      name:            'Stolen Asset Recovery Initiative (StAR)',
      description:     'World Bank/UNODC partnership — asset recovery, anti-corruption, mutual legal assistance',
      url:             'https://star.worldbank.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'politics', 'society']),
      rss_feeds:       JSON.stringify(['https://star.worldbank.org/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'anti-corruption-digest',
      name:            'Anti-Corruption Digest',
      description:     'Curated news digest on global anti-corruption efforts — FCPA, UK Bribery Act, enforcement actions',
      url:             'https://anticorruptiondigest.com',
      tier:            'specialised',
      trust_score:     0.76,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['politics', 'economy', 'society']),
      rss_feeds:       JSON.stringify(['https://anticorruptiondigest.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Artificial Intelligence & Tech Policy ────────────────────────────────
    {
      slug:            'stanford-ai-index',
      name:            'Stanford HAI AI Index',
      description:     'Stanford Institute for Human-Centered AI — annual AI index, research, policy, talent tracking',
      url:             'https://aiindex.stanford.edu',
      tier:            'premium',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'science', 'politics']),
      rss_feeds:       JSON.stringify(['https://hai.stanford.edu/news/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'ai-news-gb',
      name:            'AI News',
      description:     'UK-based AI industry news — enterprise AI, generative AI, regulation, startups, research',
      url:             'https://www.artificialintelligence-news.com',
      tier:            'major',
      trust_score:     0.78,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['technology', 'economy', 'science']),
      rss_feeds:       JSON.stringify(['https://www.artificialintelligence-news.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'mit-tech-review-ai',
      name:            'MIT Technology Review — AI',
      description:     'MIT\'s flagship tech publication AI vertical — research breakthroughs, ethics, regulation, industry',
      url:             'https://www.technologyreview.com/topic/artificial-intelligence/',
      tier:            'premium',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'science', 'society']),
      rss_feeds:       JSON.stringify(['https://www.technologyreview.com/topic/artificial-intelligence/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'venturebeat-ai',
      name:            'VentureBeat AI',
      description:     'VentureBeat\'s AI vertical — enterprise AI, startups, funding, product launches, GPU market',
      url:             'https://venturebeat.com/category/ai/',
      tier:            'major',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy', 'science']),
      rss_feeds:       JSON.stringify(['https://venturebeat.com/category/ai/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'the-batch-deeplearningai',
      name:            'The Batch (DeepLearning.AI)',
      description:     'Andrew Ng\'s weekly AI newsletter — research papers, industry news, technical tutorials, career advice',
      url:             'https://www.deeplearning.ai/the-batch/',
      tier:            'major',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'science', 'education']),
      rss_feeds:       JSON.stringify(['https://www.deeplearning.ai/the-batch/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex('sources')
      .insert(source)
      .onConflict('slug')
      .ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    // West Africa Anglophone
    'premium-times-ng', 'ghanaweb-gh', 'sierra-leone-telegraph-sl',
    'liberian-observer-lr', 'the-gambia-standard-gm',
    // Francophone Africa
    'jeune-afrique-fr', 'rfi-afrique-fr', 'le-monde-afrique-fr',
    'abidjan-net-ci', 'le-faso-bf',
    // Caribbean & Small Island
    'jamaica-gleaner-jm', 'trinidad-express-tt', 'barbados-today-bb',
    'st-lucia-times-lc', 'guyana-chronicle-gy',
    // Conflict & Peace Studies
    'international-crisis-group', 'prio-no', 'sipri-se',
    'conciliation-resources-gb', 'saferworld-gb',
    // Supply Chain & Trade
    'supply-chain-dive-us', 'freightwaves-us', 'the-loadstar-gb',
    'journal-of-commerce-us', 'container-news-gb',
    // Education & Development
    'unesco-news', 'university-world-news-za', 'times-higher-education-gb',
    'the-pie-news-gb', 'global-partnership-education',
    // Wildlife & Conservation
    'mongabay-us', 'traffic-wildlife-trade', 'wwf-news',
    'iucn-news', 'conservation-international',
    // Disability & Inclusion
    'disability-rights-intl', 'inclusive-city-maker', 'leonard-cheshire-gb',
    'light-for-the-world-at', 'intl-disability-alliance',
    // Corruption & Transparency
    'occrp', 'global-witness-gb', 'tax-justice-network-gb',
    'star-stolen-asset-recovery', 'anti-corruption-digest',
    // Artificial Intelligence
    'stanford-ai-index', 'ai-news-gb', 'mit-tech-review-ai',
    'venturebeat-ai', 'the-batch-deeplearningai',
  ]

  await knex('sources').whereIn('slug', slugs).del()
}
