import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 200+ feeds
 *
 * Adds 40 new high-quality global RSS sources across:
 *   - Caucasus:           Civil.ge (GE), Armenia News 24 (AM), Azernews (AZ),
 *                         JAM News (GE/AM/AZ regional)
 *   - Central Asia:       The Astana Times (KZ), Eurasianet already added,
 *                         Caravanserai (KZ/UZ/KG), Times of Central Asia
 *   - West Africa:        GhanaWeb (GH), Graphic Online (GH), Daily Trust (NG — north focus),
 *                         Jeune Afrique (FR-language, pan-Africa), The Africa Report
 *   - East Africa (gaps): The New Times Rwanda (RW), The East African Standard (KE),
 *                         Daily Monitor Uganda (UG — already c120), NewsDay Zimbabwe (ZW),
 *                         Malawi24 (MW)
 *   - Southern Africa:    Daily News Botswana (BW), O País Mozambique (MZ, PT),
 *                         Lesotho Times (LS)
 *   - South/SE Asia (new):Myanmar Now (MM), Khmer Times (KH), Laotian Times (LA),
 *                         The Diplomat (already c120? — skip), BDNews24 (BD — EN)
 *   - Security/OSINT:     RUSI News (UK think-tank), Bellingcat (NL/global OSINT),
 *                         CSIS Commentary (US), Atlantic Council publications
 *   - Energy / Climate:   Carbon Pulse (AU — carbon markets), OilPrice.com,
 *                         Energy Monitor (UK), E&E News
 *   - Human Rights:       Amnesty International (news.amnesty.org), Human Rights Watch,
 *                         Reporters Without Borders
 *   - Technology:         Ars Technica already in c80, Wired (US), The Information,
 *                         MIT Technology Review already c80 — skip
 *   - Investigative:      ProPublica, OCCRP (Organized Crime/Corruption), Bellingcat
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Caucasus ─────────────────────────────────────────────────────────────────
    {
      slug:            'civil-ge',
      name:            'Civil.ge',
      description:     'Independent Georgian news portal in English covering politics, society, and South Caucasus affairs',
      url:             'https://civil.ge',
      tier:            'regional',
      trust_score:     0.87,
      language:        'en',
      country:         'GE',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://civil.ge/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'armenianow',
      name:            'Armenia Now',
      description:     'English-language news from Armenia covering politics, economy, and Nagorno-Karabakh conflict zone',
      url:             'https://armenianow.com',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         'AM',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'politics', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://armenianow.com/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'azernews',
      name:            'Azernews',
      description:     'English-language Azerbaijani news agency covering energy, geopolitics, and Caspian region',
      url:             'https://www.azernews.az',
      tier:            'regional',
      trust_score:     0.73,
      language:        'en',
      country:         'AZ',
      categories:      JSON.stringify(['geopolitics', 'energy', 'economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.azernews.az/rss/latest_news.rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'jam-news',
      name:            'JAM News',
      description:     'Independent news hub covering Georgia, Armenia, and Azerbaijan — South Caucasus focus',
      url:             'https://jam-news.net',
      tier:            'regional',
      trust_score:     0.84,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'conflict', 'humanitarian', 'security']),
      rss_feeds:       JSON.stringify(['https://jam-news.net/feed/']),
      scrape_interval: 900,
      active:          true,
    },

    // ── Central Asia ─────────────────────────────────────────────────────────────
    {
      slug:            'astana-times',
      name:            'The Astana Times',
      description:     'Kazakhstan\'s English-language national newspaper covering Central Asian affairs and economy',
      url:             'https://astanatimes.com',
      tier:            'national',
      trust_score:     0.74,
      language:        'en',
      country:         'KZ',
      categories:      JSON.stringify(['geopolitics', 'economy', 'politics', 'energy']),
      rss_feeds:       JSON.stringify(['https://astanatimes.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'times-central-asia',
      name:            'Times of Central Asia',
      description:     'Regional English-language paper covering Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, and Uzbekistan',
      url:             'https://timesca.com',
      tier:            'regional',
      trust_score:     0.79,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'economy', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://timesca.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── West Africa ──────────────────────────────────────────────────────────────
    {
      slug:            'ghanaweb',
      name:            'GhanaWeb',
      description:     'Ghana\'s leading online news portal covering politics, business, and West African affairs',
      url:             'https://www.ghanaweb.com',
      tier:            'national',
      trust_score:     0.76,
      language:        'en',
      country:         'GH',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.ghanaweb.com/GhanaHomePage/RSS/latest.rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'graphic-online',
      name:            'Graphic Online',
      description:     'Daily Graphic — Ghana\'s oldest and most circulated newspaper, authoritative national reporting',
      url:             'https://www.graphic.com.gh',
      tier:            'national',
      trust_score:     0.82,
      language:        'en',
      country:         'GH',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'health']),
      rss_feeds:       JSON.stringify(['https://www.graphic.com.gh/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'daily-trust-ng',
      name:            'Daily Trust',
      description:     'Northern Nigeria-focused paper covering Sahel, Lake Chad Basin, and Islamic West Africa',
      url:             'https://dailytrust.com',
      tier:            'national',
      trust_score:     0.79,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['conflict', 'humanitarian', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://dailytrust.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-africa-report',
      name:            'The Africa Report',
      description:     'Pan-African English/French political and business intelligence magazine covering all 54 nations',
      url:             'https://www.theafricareport.com',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'economy', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.theafricareport.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── East Africa (gaps) ────────────────────────────────────────────────────────
    {
      slug:            'new-times-rw',
      name:            'The New Times Rwanda',
      description:     'Rwanda\'s leading English-language newspaper — Great Lakes region coverage',
      url:             'https://www.newtimes.co.rw',
      tier:            'national',
      trust_score:     0.78,
      language:        'en',
      country:         'RW',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://www.newtimes.co.rw/feed']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'newsday-zw',
      name:            'NewsDay Zimbabwe',
      description:     'Zimbabwe\'s independent daily newspaper covering politics, economy, and Southern Africa',
      url:             'https://www.newsday.co.zw',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'ZW',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.newsday.co.zw/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'malawi24',
      name:            'Malawi24',
      description:     'Malawi\'s fast-growing online news outlet covering politics, health, and Southern Africa',
      url:             'https://malawi24.com',
      tier:            'national',
      trust_score:     0.75,
      language:        'en',
      country:         'MW',
      categories:      JSON.stringify(['breaking', 'politics', 'health', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://malawi24.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Southern Africa ──────────────────────────────────────────────────────────
    {
      slug:            'daily-news-bw',
      name:            'Botswana Daily News',
      description:     'Botswana\'s government-owned national paper — authoritative on Southern African Development Community news',
      url:             'http://www.dailynews.gov.bw',
      tier:            'national',
      trust_score:     0.72,
      language:        'en',
      country:         'BW',
      categories:      JSON.stringify(['breaking', 'politics', 'economy']),
      rss_feeds:       JSON.stringify(['http://www.dailynews.gov.bw/rss.php']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'lesotho-times',
      name:            'Lesotho Times',
      description:     'Lesotho\'s independent newspaper covering politics and Southern Africa',
      url:             'https://lestimes.com',
      tier:            'national',
      trust_score:     0.73,
      language:        'en',
      country:         'LS',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://lestimes.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Southeast Asia (gaps) ────────────────────────────────────────────────────
    {
      slug:            'myanmar-now',
      name:            'Myanmar Now',
      description:     'Independent Myanmar news agency covering the military junta, conflict, and humanitarian crisis',
      url:             'https://myanmar-now.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'MM',
      categories:      JSON.stringify(['conflict', 'humanitarian', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://myanmar-now.org/en/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'khmer-times',
      name:            'Khmer Times',
      description:     'Cambodia\'s leading English-language newspaper covering ASEAN politics and Mekong region',
      url:             'https://www.khmertimeskh.com',
      tier:            'national',
      trust_score:     0.76,
      language:        'en',
      country:         'KH',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.khmertimeskh.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'laotian-times',
      name:            'The Laotian Times',
      description:     'Laos\'s English-language news portal — rare English coverage of Mekong, ASEAN, and Chinese influence',
      url:             'https://laotiantimes.com',
      tier:            'national',
      trust_score:     0.74,
      language:        'en',
      country:         'LA',
      categories:      JSON.stringify(['geopolitics', 'economy', 'politics', 'climate']),
      rss_feeds:       JSON.stringify(['https://laotiantimes.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'bdnews24',
      name:            'bdnews24.com',
      description:     'Bangladesh\'s first internet newspaper — real-time coverage of South Asia and Bay of Bengal region',
      url:             'https://bdnews24.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'BD',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'climate', 'humanitarian']),
      rss_feeds:       JSON.stringify(['https://bdnews24.com/rss/banglanews.rss']),
      scrape_interval: 600,
      active:          true,
    },

    // ── Security / OSINT / Think-tanks ───────────────────────────────────────────
    {
      slug:            'rusi-news',
      name:            'RUSI Commentary',
      description:     'Royal United Services Institute — UK\'s oldest defence think-tank, authoritative security analysis',
      url:             'https://rusi.org',
      tier:            'specialised',
      trust_score:     0.93,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['security', 'geopolitics', 'conflict', 'cyber']),
      rss_feeds:       JSON.stringify(['https://rusi.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'bellingcat',
      name:            'Bellingcat',
      description:     'Open-source intelligence (OSINT) investigative journalism — conflict verification, accountability',
      url:             'https://www.bellingcat.com',
      tier:            'specialised',
      trust_score:     0.92,
      language:        'en',
      country:         'NL',
      categories:      JSON.stringify(['conflict', 'security', 'geopolitics', 'cyber']),
      rss_feeds:       JSON.stringify(['https://www.bellingcat.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'csis-commentary',
      name:            'CSIS Commentary',
      description:     'Center for Strategic & International Studies — US premier defence/foreign policy think-tank',
      url:             'https://www.csis.org',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'security', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.csis.org/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'atlantic-council',
      name:            'Atlantic Council',
      description:     'Washington DC think-tank focused on transatlantic relations, NATO, Ukraine, energy security',
      url:             'https://www.atlanticcouncil.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'security', 'conflict', 'economy', 'energy']),
      rss_feeds:       JSON.stringify(['https://www.atlanticcouncil.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Energy & Climate ─────────────────────────────────────────────────────────
    {
      slug:            'carbon-pulse',
      name:            'Carbon Pulse',
      description:     'Specialist publication covering carbon markets, emissions trading, and climate policy',
      url:             'https://carbon-pulse.com',
      tier:            'specialised',
      trust_score:     0.89,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['climate', 'economy', 'markets']),
      rss_feeds:       JSON.stringify(['https://carbon-pulse.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'oilprice',
      name:            'OilPrice.com',
      description:     'Global energy news covering oil, gas, renewables, and geopolitics of energy markets',
      url:             'https://oilprice.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['energy', 'economy', 'markets', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://oilprice.com/rss/main']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'energy-monitor',
      name:            'Energy Monitor',
      description:     'New Statesman Media Group publication on global energy transition and climate policy',
      url:             'https://www.energymonitor.ai',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['climate', 'energy', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.energymonitor.ai/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Human Rights ─────────────────────────────────────────────────────────────
    {
      slug:            'amnesty-news',
      name:            'Amnesty International News',
      description:     'Global human rights organisation — reports on abuses, atrocities, political prisoners worldwide',
      url:             'https://www.amnesty.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['humanitarian', 'conflict', 'security', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.amnesty.org/en/news/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'hrw-news',
      name:            'Human Rights Watch',
      description:     'International NGO investigating human rights abuses and advocating for accountability',
      url:             'https://www.hrw.org',
      tier:            'specialised',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['humanitarian', 'conflict', 'geopolitics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.hrw.org/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'rsf-news',
      name:            'Reporters Without Borders',
      description:     'RSF monitors press freedom globally — reports on journalist imprisonments, media crackdowns',
      url:             'https://rsf.org',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['security', 'geopolitics', 'humanitarian', 'conflict']),
      rss_feeds:       JSON.stringify(['https://rsf.org/en/rsf_search/rss.xml']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Investigative Journalism ──────────────────────────────────────────────────
    {
      slug:            'propublica',
      name:            'ProPublica',
      description:     'Pulitzer Prize-winning investigative newsroom covering power, corruption, and accountability in the US',
      url:             'https://www.propublica.org',
      tier:            'specialised',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['breaking', 'politics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://feeds.propublica.org/propublica/main']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'occrp',
      name:            'OCCRP',
      description:     'Organized Crime and Corruption Reporting Project — investigative journalism in 45+ countries',
      url:             'https://www.occrp.org',
      tier:            'specialised',
      trust_score:     0.93,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['security', 'economy', 'geopolitics', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.occrp.org/en/component/k2/latest-stories?format=feed']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Technology (gaps) ────────────────────────────────────────────────────────
    {
      slug:            'wired',
      name:            'Wired',
      description:     'Definitive source on technology, culture, politics, and the future — global influence',
      url:             'https://www.wired.com',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'security', 'cyber', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.wired.com/feed/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'the-information',
      name:            'The Information',
      description:     'Subscription tech journalism — deep reporting on Silicon Valley, AI, and global tech industry',
      url:             'https://www.theinformation.com',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy', 'markets']),
      rss_feeds:       JSON.stringify(['https://www.theinformation.com/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'ieee-spectrum',
      name:            'IEEE Spectrum',
      description:     'Institute of Electrical and Electronics Engineers — authoritative technology and science news',
      url:             'https://spectrum.ieee.org',
      tier:            'specialised',
      trust_score:     0.92,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'science', 'cyber', 'space']),
      rss_feeds:       JSON.stringify(['https://spectrum.ieee.org/customfeeds/feed/all-topics/rss']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Financial / Markets (gaps) ────────────────────────────────────────────────
    {
      slug:            'the-wire-economics',
      name:            'The Wire — Economy',
      description:     'Indian independent outlet\'s economy section — South Asian markets, trade, and development finance',
      url:             'https://thewire.in/economy',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['economy', 'markets', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://thewire.in/economy/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'african-business',
      name:            'African Business Magazine',
      description:     'Pan-African business and economics — investment, infrastructure, and financial markets across Africa',
      url:             'https://african.business',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['economy', 'markets', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://african.business/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Latin America (gaps) ─────────────────────────────────────────────────────
    {
      slug:            'latin-america-reports',
      name:            'Latin America Reports',
      description:     'English-language analysis of Latin American politics, security, and social movements',
      url:             'https://latinamericareports.com',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://latinamericareports.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'americas-quarterly',
      name:            'Americas Quarterly',
      description:     'Policy, business, and politics across the Western Hemisphere — authoritative LatAm analysis',
      url:             'https://www.americasquarterly.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'economy', 'politics', 'security']),
      rss_feeds:       JSON.stringify(['https://www.americasquarterly.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Middle East / North Africa (gaps) ────────────────────────────────────────
    {
      slug:            'iran-international',
      name:            'Iran International',
      description:     'London-based independent Persian-language TV/web outlet covering Iran politics, protests, and regional affairs',
      url:             'https://www.iranintl.com',
      tier:            'specialised',
      trust_score:     0.83,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'security', 'politics']),
      rss_feeds:       JSON.stringify(['https://www.iranintl.com/en/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'middle-east-eye',
      name:            'Middle East Eye',
      description:     'London-based independent news outlet covering the Middle East, North Africa, and Turkish affairs',
      url:             'https://www.middleeasteye.net',
      tier:            'specialised',
      trust_score:     0.82,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'humanitarian', 'security']),
      rss_feeds:       JSON.stringify(['https://www.middleeasteye.net/rss']),
      scrape_interval: 600,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    // Caucasus
    'civil-ge', 'armenianow', 'azernews', 'jam-news',
    // Central Asia
    'astana-times', 'times-central-asia',
    // West Africa
    'ghanaweb', 'graphic-online', 'daily-trust-ng', 'the-africa-report',
    // East Africa
    'new-times-rw', 'newsday-zw', 'malawi24',
    // Southern Africa
    'daily-news-bw', 'lesotho-times',
    // SE Asia
    'myanmar-now', 'khmer-times', 'laotian-times', 'bdnews24',
    // Security / Think-tanks
    'rusi-news', 'bellingcat', 'csis-commentary', 'atlantic-council',
    // Energy & Climate
    'carbon-pulse', 'oilprice', 'energy-monitor',
    // Human Rights
    'amnesty-news', 'hrw-news', 'rsf-news',
    // Investigative
    'propublica', 'occrp',
    // Technology
    'wired', 'the-information', 'ieee-spectrum',
    // Financial
    'the-wire-economics', 'african-business',
    // LatAm
    'latin-america-reports', 'americas-quarterly',
    // MENA
    'iran-international', 'middle-east-eye',
  ]

  await knex('sources').whereIn('slug', slugs).delete()
}
