import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 80+ feeds
 *
 * Adds 35 new high-quality global RSS sources across:
 *   - Wire services: AFP, Bloomberg, NHK World
 *   - Africa: Daily Maverick, AllAfrica, The East African
 *   - Asia/Pacific: South China Morning Post, The Hindu, Dawn, Straits Times, ABC Australia
 *   - Europe: Le Monde, Der Spiegel, El País, Folha de São Paulo, The Local
 *   - Middle East: Haaretz, The National (UAE), Arab News, Al-Monitor
 *   - English International: The Conversation, Foreign Policy, Rest of World
 *   - Science/Health: Nature News, ScienceAlert, STAT News, Devex
 *   - Tech: The Register, Ars Technica, TechCrunch
 *   - OSINT/Conflict: Kyiv Independent, Bellingcat, Meduza, VOA News
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Wire Services ──────────────────────────────────────────────────────────
    {
      slug:            'afp-english',
      name:            'AFP English',
      description:     'Agence France-Presse — French international wire service (English)',
      url:             'https://www.afp.com/en',
      tier:            'wire',
      trust_score:     0.95,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'conflict', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.afp.com/en/latest-news-rss']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'bloomberg-world',
      name:            'Bloomberg World',
      description:     'Bloomberg News — global financial and business journalism',
      url:             'https://www.bloomberg.com/world',
      tier:            'wire',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['economy', 'technology', 'geopolitics', 'markets']),
      rss_feeds:       JSON.stringify(['https://feeds.bloomberg.com/markets/news.rss', 'https://feeds.bloomberg.com/politics/news.rss']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'nhk-world',
      name:            'NHK World',
      description:     'NHK World — Japan Broadcasting Corporation international',
      url:             'https://www3.nhk.or.jp/nhkworld/',
      tier:            'wire',
      trust_score:     0.93,
      language:        'en',
      country:         'JP',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'science', 'culture']),
      rss_feeds:       JSON.stringify(['https://www3.nhk.or.jp/rss/news/cat0.xml', 'https://www3.nhk.or.jp/rss/news/cat6.xml']),
      scrape_interval: 600,
      active:          true,
    },
    // ── Africa ─────────────────────────────────────────────────────────────────
    {
      slug:            'daily-maverick',
      name:            'Daily Maverick',
      description:     'Daily Maverick — South African investigative journalism',
      url:             'https://dailymaverick.co.za',
      tier:            'national',
      trust_score:     0.88,
      language:        'en',
      country:         'ZA',
      categories:      JSON.stringify(['geopolitics', 'economy', 'conflict', 'climate']),
      rss_feeds:       JSON.stringify(['https://dailymaverick.co.za/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'allafrica',
      name:            'AllAfrica',
      description:     'AllAfrica — aggregator of African news from 130+ news organizations',
      url:             'https://allafrica.com',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'economy', 'health', 'conflict']),
      rss_feeds:       JSON.stringify(['https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'east-african',
      name:            'The East African',
      description:     'The East African — leading regional newspaper covering East Africa',
      url:             'https://www.theeastafrican.co.ke',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'KE',
      categories:      JSON.stringify(['economy', 'geopolitics', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.theeastafrican.co.ke/tea/news.rss']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'premium-times-ng',
      name:            'Premium Times Nigeria',
      description:     'Premium Times — Nigerian investigative and online journalism',
      url:             'https://www.premiumtimesng.com',
      tier:            'national',
      trust_score:     0.84,
      language:        'en',
      country:         'NG',
      categories:      JSON.stringify(['geopolitics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.premiumtimesng.com/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    // ── Asia / Pacific ──────────────────────────────────────────────────────────
    {
      slug:            'scmp',
      name:            'South China Morning Post',
      description:     'SCMP — Hong Kong-based leading English-language news on China and Asia',
      url:             'https://www.scmp.com',
      tier:            'national',
      trust_score:     0.85,
      language:        'en',
      country:         'HK',
      categories:      JSON.stringify(['geopolitics', 'economy', 'technology', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.scmp.com/rss/91/feed', 'https://www.scmp.com/rss/2/feed']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'the-hindu',
      name:            'The Hindu',
      description:     'The Hindu — leading Indian English-language daily',
      url:             'https://www.thehindu.com',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['geopolitics', 'economy', 'science', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.thehindu.com/feeder/default.rss', 'https://www.thehindu.com/sci-tech/science/feeder/default.rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'dawn-pk',
      name:            'Dawn',
      description:     'Dawn — Pakistan\'s largest English-language newspaper',
      url:             'https://www.dawn.com',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'PK',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.dawn.com/feeds/home', 'https://www.dawn.com/feeds/world-news']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'straits-times',
      name:            'The Straits Times',
      description:     'The Straits Times — Singapore\'s leading English newspaper, Southeast Asia focus',
      url:             'https://www.straitstimes.com',
      tier:            'national',
      trust_score:     0.86,
      language:        'en',
      country:         'SG',
      categories:      JSON.stringify(['geopolitics', 'economy', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.straitstimes.com/news/asia/rss.xml', 'https://www.straitstimes.com/news/world/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'abc-australia',
      name:            'ABC News Australia',
      description:     'ABC News — Australian Broadcasting Corporation, Pacific and Asia-Pacific coverage',
      url:             'https://www.abc.net.au/news',
      tier:            'national',
      trust_score:     0.91,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'climate', 'science']),
      rss_feeds:       JSON.stringify(['https://www.abc.net.au/news/feed/51120/rss.xml', 'https://www.abc.net.au/news/feed/45910/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'nikkei-asia',
      name:            'Nikkei Asia',
      description:     'Nikkei Asia — English-language Asian business and geopolitics news',
      url:             'https://asia.nikkei.com',
      tier:            'national',
      trust_score:     0.89,
      language:        'en',
      country:         'JP',
      categories:      JSON.stringify(['economy', 'technology', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://asia.nikkei.com/rss/feed/nar']),
      scrape_interval: 900,
      active:          true,
    },
    // ── Europe ──────────────────────────────────────────────────────────────────
    {
      slug:            'le-monde-en',
      name:            'Le Monde (English)',
      description:     'Le Monde — France\'s leading newspaper, English section',
      url:             'https://www.lemonde.fr/en/',
      tier:            'national',
      trust_score:     0.90,
      language:        'en',
      country:         'FR',
      categories:      JSON.stringify(['geopolitics', 'economy', 'culture', 'science']),
      rss_feeds:       JSON.stringify(['https://www.lemonde.fr/en/rss/une.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'der-spiegel-en',
      name:            'Der Spiegel (English)',
      description:     'Der Spiegel — Germany\'s leading news magazine, international edition',
      url:             'https://www.spiegel.de/international/',
      tier:            'national',
      trust_score:     0.89,
      language:        'en',
      country:         'DE',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.spiegel.de/international/index.rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'elpais-en',
      name:            'El País (English)',
      description:     'El País — Spain\'s leading newspaper, English edition',
      url:             'https://english.elpais.com',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'ES',
      categories:      JSON.stringify(['geopolitics', 'economy', 'culture', 'climate']),
      rss_feeds:       JSON.stringify(['https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'euractiv',
      name:            'Euractiv',
      description:     'Euractiv — EU policy and European affairs specialist',
      url:             'https://www.euractiv.com',
      tier:            'regional',
      trust_score:     0.85,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['geopolitics', 'economy', 'technology', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.euractiv.com/sections/all/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'politico-eu',
      name:            'Politico Europe',
      description:     'Politico Europe — European politics and policy journalism',
      url:             'https://www.politico.eu',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'BE',
      categories:      JSON.stringify(['geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://rss.politico.eu/politics']),
      scrape_interval: 900,
      active:          true,
    },
    // ── Middle East ─────────────────────────────────────────────────────────────
    {
      slug:            'haaretz-en',
      name:            'Haaretz (English)',
      description:     'Haaretz — Israel\'s oldest newspaper, Middle East coverage',
      url:             'https://www.haaretz.com',
      tier:            'national',
      trust_score:     0.85,
      language:        'en',
      country:         'IL',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.haaretz.com/cmlink/1.628765']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-national-uae',
      name:            'The National (UAE)',
      description:     'The National — UAE-based English daily covering the Gulf and MENA',
      url:             'https://www.thenationalnews.com',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'AE',
      categories:      JSON.stringify(['geopolitics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.thenationalnews.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'arab-news',
      name:            'Arab News',
      description:     'Arab News — Saudi Arabia-based Pan-Arab English daily',
      url:             'https://www.arabnews.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'SA',
      categories:      JSON.stringify(['geopolitics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.arabnews.com/rss.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'al-monitor',
      name:            'Al-Monitor',
      description:     'Al-Monitor — independent Middle East news, policy and analysis',
      url:             'https://www.al-monitor.com',
      tier:            'regional',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['conflict', 'geopolitics', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.al-monitor.com/rss.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    // ── English International ───────────────────────────────────────────────────
    {
      slug:            'the-conversation',
      name:            'The Conversation',
      description:     'The Conversation — expert academic analysis of news events',
      url:             'https://theconversation.com',
      tier:            'regional',
      trust_score:     0.88,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['science', 'climate', 'health', 'economy', 'technology']),
      rss_feeds:       JSON.stringify(['https://theconversation.com/global/articles.atom', 'https://theconversation.com/us/articles.atom']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'foreign-policy',
      name:            'Foreign Policy',
      description:     'Foreign Policy — global affairs, international security and diplomacy',
      url:             'https://foreignpolicy.com',
      tier:            'national',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://foreignpolicy.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'rest-of-world',
      name:            'Rest of World',
      description:     'Rest of World — technology\'s impact beyond the Western world',
      url:             'https://restofworld.org',
      tier:            'regional',
      trust_score:     0.86,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://restofworld.org/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'the-wire-india',
      name:            'The Wire',
      description:     'The Wire — India-based independent investigative journalism',
      url:             'https://thewire.in',
      tier:            'regional',
      trust_score:     0.84,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'science', 'economy']),
      rss_feeds:       JSON.stringify(['https://thewire.in/rss']),
      scrape_interval: 1800,
      active:          true,
    },
    // ── OSINT / Conflict ────────────────────────────────────────────────────────
    {
      slug:            'kyiv-independent',
      name:            'Kyiv Independent',
      description:     'Kyiv Independent — English-language Ukrainian news and war coverage',
      url:             'https://kyivindependent.com',
      tier:            'regional',
      trust_score:     0.85,
      language:        'en',
      country:         'UA',
      categories:      JSON.stringify(['conflict', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://kyivindependent.com/rss/']),
      scrape_interval: 300,
      active:          true,
    },
    {
      slug:            'voa-news',
      name:            'Voice of America',
      description:     'VOA News — US federal government international broadcast service',
      url:             'https://www.voanews.com',
      tier:            'wire',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'conflict', 'health']),
      rss_feeds:       JSON.stringify(['https://www.voanews.com/api/epiqq', 'https://www.voanews.com/z/1729.rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'radio-free-europe',
      name:            'Radio Free Europe / Radio Liberty',
      description:     'RFE/RL — coverage of Central/Eastern Europe, Russia, and Central Asia',
      url:             'https://www.rferl.org',
      tier:            'regional',
      trust_score:     0.83,
      language:        'en',
      country:         'CZ',
      categories:      JSON.stringify(['conflict', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.rferl.org/api/zp-eqivm-qooter_lbzrt/1']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'meduza',
      name:            'Meduza',
      description:     'Meduza — independent Russian investigative journalism in exile',
      url:             'https://meduza.io/en',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         'LV',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://meduza.io/rss/en/all']),
      scrape_interval: 1800,
      active:          true,
    },
    // ── Science / Health ────────────────────────────────────────────────────────
    {
      slug:            'nature-news',
      name:            'Nature News',
      description:     'Nature — world\'s leading multidisciplinary science journal news',
      url:             'https://www.nature.com/news',
      tier:            'regional',
      trust_score:     0.97,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['science', 'health', 'climate', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.nature.com/nature.rss', 'https://www.nature.com/news-and-comment.rss']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'sciencealert',
      name:            'ScienceAlert',
      description:     'ScienceAlert — science and technology news for a global audience',
      url:             'https://www.sciencealert.com',
      tier:            'regional',
      trust_score:     0.83,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['science', 'health', 'technology', 'space']),
      rss_feeds:       JSON.stringify(['https://www.sciencealert.com/feed']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'stat-news',
      name:            'STAT News',
      description:     'STAT News — health, medicine, and biotech journalism',
      url:             'https://www.statnews.com',
      tier:            'regional',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'science', 'technology']),
      rss_feeds:       JSON.stringify(['https://www.statnews.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'devex',
      name:            'Devex',
      description:     'Devex — international development and global health journalism',
      url:             'https://www.devex.com',
      tier:            'regional',
      trust_score:     0.84,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['health', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.devex.com/news.rss']),
      scrape_interval: 3600,
      active:          true,
    },
    // ── Technology ──────────────────────────────────────────────────────────────
    {
      slug:            'ars-technica',
      name:            'Ars Technica',
      description:     'Ars Technica — technology, science, and policy in depth',
      url:             'https://arstechnica.com',
      tier:            'regional',
      trust_score:     0.87,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'science', 'security']),
      rss_feeds:       JSON.stringify(['https://feeds.arstechnica.com/arstechnica/index']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'the-register',
      name:            'The Register',
      description:     'The Register — independent tech journalism since 1994',
      url:             'https://www.theregister.com',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['technology', 'security', 'science']),
      rss_feeds:       JSON.stringify(['https://www.theregister.com/headlines.atom']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'techcrunch',
      name:            'TechCrunch',
      description:     'TechCrunch — technology startup news and venture capital',
      url:             'https://techcrunch.com',
      tier:            'regional',
      trust_score:     0.83,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['technology', 'economy']),
      rss_feeds:       JSON.stringify(['https://techcrunch.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    // ── Latin America ────────────────────────────────────────────────────────────
    {
      slug:            'folha-sp-en',
      name:            'Folha de S.Paulo (English)',
      description:     'Folha de S.Paulo — Brazil\'s largest newspaper (English digest)',
      url:             'https://www1.folha.uol.com.br/internacional/en/',
      tier:            'national',
      trust_score:     0.86,
      language:        'en',
      country:         'BR',
      categories:      JSON.stringify(['geopolitics', 'economy', 'climate', 'culture']),
      rss_feeds:       JSON.stringify(['https://feeds.folha.uol.com.br/emcimadahora/rss091.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'mercopress',
      name:            'MercoPress',
      description:     'MercoPress — South Atlantic News Agency covering South America and Falklands',
      url:             'https://en.mercopress.com',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         'UY',
      categories:      JSON.stringify(['geopolitics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://en.mercopress.com/rss/en/latest-news.xml']),
      scrape_interval: 1800,
      active:          true,
    },
  ]

  // Use INSERT ... ON CONFLICT DO NOTHING for idempotency
  for (const source of sources) {
    await knex('sources')
      .insert(source)
      .onConflict('slug')
      .ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    'afp-english', 'bloomberg-world', 'nhk-world',
    'daily-maverick', 'allafrica', 'east-african', 'premium-times-ng',
    'scmp', 'the-hindu', 'dawn-pk', 'straits-times', 'abc-australia', 'nikkei-asia',
    'le-monde-en', 'der-spiegel-en', 'elpais-en', 'euractiv', 'politico-eu',
    'haaretz-en', 'the-national-uae', 'arab-news', 'al-monitor',
    'the-conversation', 'foreign-policy', 'rest-of-world', 'the-wire-india',
    'kyiv-independent', 'voa-news', 'radio-free-europe', 'meduza',
    'nature-news', 'sciencealert', 'stat-news', 'devex',
    'ars-technica', 'the-register', 'techcrunch',
    'folha-sp-en', 'mercopress',
  ]
  await knex('sources').whereIn('slug', slugs).delete()
}
