import type { Knex } from 'knex'

/**
 * Migration: Expand source registry to 150+ feeds
 *
 * Adds 35 new high-quality global RSS sources across:
 *   - Oceania:          The Australian, Sydney Morning Herald, NZ Herald, RNZ, PACNEWS,
 *                       PNG Post-Courier, RNZ Pacific, Fiji Times
 *   - Caribbean:        Jamaica Gleaner, Trinidad Express, Barbados Nation, Dominican Today
 *   - Nordic / Baltic:  YLE International (FI), The Local SE, ERR (EE), LRT English (LT),
 *                       LSM English (LV)
 *   - South Asia (new): Daily Star Bangladesh, Kathmandu Post, Scroll.in, Colombo Telegraph
 *   - Academic / Research: Science Magazine (AAAS), EurekAlert!, ScienceDaily,
 *                           Physics World, Harvard Gazette, Quanta Magazine
 *   - Middle East / Africa gaps: Al-Ahram (EG), Morocco World News (MA),
 *                                The Citizen TZ, Ethiopian Reporter, Jordan Times (JO)
 *   - Geopolitics / Analysis: openDemocracy, War on the Rocks, CEPA News
 *
 * Uses INSERT ... ON CONFLICT DO NOTHING (idempotent — safe to re-run).
 */

export async function up(knex: Knex): Promise<void> {
  const sources = [
    // ── Oceania ─────────────────────────────────────────────────────────────────
    {
      slug:            'the-australian',
      name:            'The Australian',
      description:     'Australia\'s national broadsheet covering politics, business, and foreign affairs',
      url:             'https://www.theaustralian.com.au',
      tier:            'national',
      trust_score:     0.85,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.theaustralian.com.au/feed/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'sydney-morning-herald',
      name:            'Sydney Morning Herald',
      description:     'Australia\'s oldest newspaper — authoritative coverage of national and global affairs',
      url:             'https://www.smh.com.au',
      tier:            'national',
      trust_score:     0.88,
      language:        'en',
      country:         'AU',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'health', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.smh.com.au/rss/feed.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'nz-herald',
      name:            'NZ Herald',
      description:     'New Zealand\'s largest daily newspaper covering national and Pacific affairs',
      url:             'https://www.nzherald.co.nz',
      tier:            'national',
      trust_score:     0.86,
      language:        'en',
      country:         'NZ',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.nzherald.co.nz/arc/outboundfeeds/rss/']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'rnz-news',
      name:            'RNZ News',
      description:     'Radio New Zealand public broadcaster — independent, non-commercial, trusted',
      url:             'https://www.rnz.co.nz',
      tier:            'national',
      trust_score:     0.93,
      language:        'en',
      country:         'NZ',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'climate', 'health']),
      rss_feeds:       JSON.stringify(['https://www.rnz.co.nz/rss/news.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'rnz-pacific',
      name:            'RNZ Pacific',
      description:     'Radio New Zealand\'s Pacific service — primary English-language news wire for the Pacific Islands',
      url:             'https://www.rnz.co.nz/international/pacific-news',
      tier:            'regional',
      trust_score:     0.91,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['breaking', 'geopolitics', 'climate', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.rnz.co.nz/rss/pacificnews.xml']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'pacnews',
      name:            'PACNEWS',
      description:     'Pacific Islands News Association wire service covering 24 Pacific Island nations',
      url:             'https://www.pina.com.fj',
      tier:            'regional',
      trust_score:     0.82,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['breaking', 'geopolitics', 'climate', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.pina.com.fj/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'png-post-courier',
      name:            'PNG Post-Courier',
      description:     'Papua New Guinea\'s leading daily newspaper',
      url:             'https://postcourier.com.pg',
      tier:            'national',
      trust_score:     0.78,
      language:        'en',
      country:         'PG',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://postcourier.com.pg/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'fiji-times',
      name:            'The Fiji Times',
      description:     'Fiji\'s oldest and most widely read newspaper',
      url:             'https://www.fijitimes.com',
      tier:            'national',
      trust_score:     0.78,
      language:        'en',
      country:         'FJ',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.fijitimes.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Caribbean ────────────────────────────────────────────────────────────────
    {
      slug:            'jamaica-gleaner',
      name:            'Jamaica Gleaner',
      description:     'Jamaica\'s oldest newspaper, covering Caribbean and international affairs',
      url:             'https://jamaica-gleaner.com',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'JM',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://jamaica-gleaner.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'trinidad-express',
      name:            'Trinidad Express',
      description:     'Trinidad and Tobago\'s Express Newspapers — regional Caribbean coverage',
      url:             'https://trinidadexpress.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'TT',
      categories:      JSON.stringify(['breaking', 'economy', 'geopolitics', 'culture']),
      rss_feeds:       JSON.stringify(['https://trinidadexpress.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'barbados-nation',
      name:            'Barbados Nation',
      description:     'The Nation Publishing Co. — primary news source for Barbados and Eastern Caribbean',
      url:             'https://www.nationnews.com',
      tier:            'national',
      trust_score:     0.79,
      language:        'en',
      country:         'BB',
      categories:      JSON.stringify(['breaking', 'economy', 'culture', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://www.nationnews.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'dominican-today',
      name:            'Dominican Today',
      description:     'Dominican Republic\'s English-language digital newspaper',
      url:             'https://dominicantoday.com',
      tier:            'national',
      trust_score:     0.78,
      language:        'en',
      country:         'DO',
      categories:      JSON.stringify(['breaking', 'economy', 'geopolitics', 'culture']),
      rss_feeds:       JSON.stringify(['https://dominicantoday.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Nordic / Baltic ──────────────────────────────────────────────────────────
    {
      slug:            'yle-news-en',
      name:            'YLE International',
      description:     'Finland\'s national public broadcaster — trusted Nordic and European journalism',
      url:             'https://yle.fi/news/osasto/news',
      tier:            'national',
      trust_score:     0.93,
      language:        'en',
      country:         'FI',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'science', 'climate']),
      rss_feeds:       JSON.stringify(['https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'the-local-se',
      name:            'The Local Sweden',
      description:     'Sweden\'s English-language news site — Nordic politics, society, and economy',
      url:             'https://www.thelocal.se',
      tier:            'regional',
      trust_score:     0.83,
      language:        'en',
      country:         'SE',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.thelocal.se/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'err-news',
      name:            'ERR News',
      description:     'Estonian Public Broadcasting English service — Baltic affairs and EU policy',
      url:             'https://news.err.ee',
      tier:            'national',
      trust_score:     0.89,
      language:        'en',
      country:         'EE',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://news.err.ee/rss']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'lrt-english',
      name:            'LRT English',
      description:     'Lithuania\'s national public broadcaster English-language service',
      url:             'https://www.lrt.lt/en/news-in-english',
      tier:            'national',
      trust_score:     0.88,
      language:        'en',
      country:         'LT',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://www.lrt.lt/rss/news-in-english']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'lsm-en',
      name:            'LSM English',
      description:     'Latvian Public Broadcasting English service — Baltic and Russian border coverage',
      url:             'https://eng.lsm.lv',
      tier:            'national',
      trust_score:     0.87,
      language:        'en',
      country:         'LV',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'security']),
      rss_feeds:       JSON.stringify(['https://eng.lsm.lv/rss/']),
      scrape_interval: 600,
      active:          true,
    },

    // ── South Asia (expanded) ─────────────────────────────────────────────────────
    {
      slug:            'daily-star-bd',
      name:            'The Daily Star Bangladesh',
      description:     'Bangladesh\'s most widely read English-language daily newspaper',
      url:             'https://www.thedailystar.net',
      tier:            'national',
      trust_score:     0.81,
      language:        'en',
      country:         'BD',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'climate', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.thedailystar.net/frontpage/rss.xml']),
      scrape_interval: 600,
      active:          true,
    },
    {
      slug:            'kathmandu-post',
      name:            'The Kathmandu Post',
      description:     'Nepal\'s leading English-language newspaper covering South Asia and Himalayan affairs',
      url:             'https://kathmandupost.com',
      tier:            'national',
      trust_score:     0.83,
      language:        'en',
      country:         'NP',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'climate', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://kathmandupost.com/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'scroll-in',
      name:            'Scroll.in',
      description:     'India\'s independent digital journalism platform — politics, rights, and investigative reporting',
      url:             'https://scroll.in',
      tier:            'specialised',
      trust_score:     0.86,
      language:        'en',
      country:         'IN',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture', 'conflict']),
      rss_feeds:       JSON.stringify(['https://scroll.in/rss']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'colombo-telegraph',
      name:            'Colombo Telegraph',
      description:     'Sri Lanka\'s independent digital news outlet covering governance and conflict',
      url:             'https://www.colombotelegraph.com',
      tier:            'specialised',
      trust_score:     0.78,
      language:        'en',
      country:         'LK',
      categories:      JSON.stringify(['geopolitics', 'conflict', 'breaking', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.colombotelegraph.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Academic / Research ───────────────────────────────────────────────────────
    {
      slug:            'science-magazine',
      name:            'Science Magazine (AAAS)',
      description:     'American Association for the Advancement of Science — peer-reviewed science news and research',
      url:             'https://www.science.org',
      tier:            'specialised',
      trust_score:     0.97,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'health', 'technology', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.science.org/rss/news_current.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'eureka-alert',
      name:            'EurekAlert!',
      description:     'AAAS\'s global scientific news service — press releases from universities and research institutions',
      url:             'https://www.eurekalert.org',
      tier:            'specialised',
      trust_score:     0.88,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'health', 'technology', 'climate', 'economy']),
      rss_feeds:       JSON.stringify(['https://www.eurekalert.org/rss/general.xml']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'science-daily',
      name:            'ScienceDaily',
      description:     'Top science news from universities and journals worldwide — updated continuously',
      url:             'https://www.sciencedaily.com',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'health', 'technology', 'climate']),
      rss_feeds:       JSON.stringify(['https://www.sciencedaily.com/rss/top/science.xml']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'physics-world',
      name:            'Physics World',
      description:     'Institute of Physics flagship magazine — authoritative physics and applied science news',
      url:             'https://physicsworld.com',
      tier:            'specialised',
      trust_score:     0.91,
      language:        'en',
      country:         'GB',
      categories:      JSON.stringify(['science', 'technology']),
      rss_feeds:       JSON.stringify(['https://physicsworld.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'harvard-gazette',
      name:            'Harvard Gazette',
      description:     'Harvard University\'s official news publication — research breakthroughs across all disciplines',
      url:             'https://news.harvard.edu',
      tier:            'specialised',
      trust_score:     0.90,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'health', 'technology', 'economy', 'geopolitics']),
      rss_feeds:       JSON.stringify(['https://news.harvard.edu/gazette/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'quanta-magazine',
      name:            'Quanta Magazine',
      description:     'Independent, non-profit science journalism — mathematics, physics, biology, and CS',
      url:             'https://www.quantamagazine.org',
      tier:            'specialised',
      trust_score:     0.94,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['science', 'technology']),
      rss_feeds:       JSON.stringify(['https://api.quantamagazine.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },

    // ── Middle East / Africa (gap fills) ─────────────────────────────────────────
    {
      slug:            'al-ahram-en',
      name:            'Al-Ahram Weekly',
      description:     'Egypt\'s state-affiliated but editorially significant English weekly — regional context',
      url:             'https://english.ahram.org.eg',
      tier:            'national',
      trust_score:     0.78,
      language:        'en',
      country:         'EG',
      categories:      JSON.stringify(['geopolitics', 'breaking', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://english.ahram.org.eg/rss.aspx']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'morocco-world-news',
      name:            'Morocco World News',
      description:     'Morocco\'s leading English-language digital newspaper covering North Africa and MENA',
      url:             'https://www.moroccoworldnews.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'MA',
      categories:      JSON.stringify(['geopolitics', 'breaking', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.moroccoworldnews.com/feed/']),
      scrape_interval: 900,
      active:          true,
    },
    {
      slug:            'the-citizen-tz',
      name:            'The Citizen Tanzania',
      description:     'Tanzania\'s leading English daily — East Africa coverage beyond Kenya and Uganda',
      url:             'https://www.thecitizen.co.tz',
      tier:            'national',
      trust_score:     0.79,
      language:        'en',
      country:         'TZ',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'culture']),
      rss_feeds:       JSON.stringify(['https://www.thecitizen.co.tz/rss/feed']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'ethiopian-reporter',
      name:            'The Ethiopian Reporter',
      description:     'Ethiopia\'s oldest private English newspaper — Horn of Africa coverage',
      url:             'https://www.ethiopianreporter.com',
      tier:            'national',
      trust_score:     0.78,
      language:        'en',
      country:         'ET',
      categories:      JSON.stringify(['breaking', 'geopolitics', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://www.ethiopianreporter.com/feed/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'jordan-times',
      name:            'The Jordan Times',
      description:     'Jordan\'s English-language daily of record — Levant and broader Middle East coverage',
      url:             'https://jordantimes.com',
      tier:            'national',
      trust_score:     0.80,
      language:        'en',
      country:         'JO',
      categories:      JSON.stringify(['geopolitics', 'breaking', 'economy', 'conflict']),
      rss_feeds:       JSON.stringify(['https://jordantimes.com/rss/all']),
      scrape_interval: 1800,
      active:          true,
    },

    // ── Geopolitics / Analysis ────────────────────────────────────────────────────
    {
      slug:            'open-democracy',
      name:            'openDemocracy',
      description:     'Independent international media covering democracy, power, and accountability globally',
      url:             'https://www.opendemocracy.net',
      tier:            'specialised',
      trust_score:     0.85,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'conflict', 'economy', 'culture', 'security']),
      rss_feeds:       JSON.stringify(['https://www.opendemocracy.net/en/rss/']),
      scrape_interval: 1800,
      active:          true,
    },
    {
      slug:            'war-on-the-rocks',
      name:            'War on the Rocks',
      description:     'US national security, defence, and international affairs analysis by practitioners',
      url:             'https://warontherocks.com',
      tier:            'specialised',
      trust_score:     0.89,
      language:        'en',
      country:         'US',
      categories:      JSON.stringify(['security', 'geopolitics', 'conflict']),
      rss_feeds:       JSON.stringify(['https://warontherocks.com/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
    {
      slug:            'cepa-news',
      name:            'CEPA (Center for European Policy Analysis)',
      description:     'Washington/Warsaw-based think tank covering Russia, Eastern Europe, and transatlantic affairs',
      url:             'https://cepa.org',
      tier:            'specialised',
      trust_score:     0.87,
      language:        'en',
      country:         null,
      categories:      JSON.stringify(['geopolitics', 'security', 'conflict', 'economy']),
      rss_feeds:       JSON.stringify(['https://cepa.org/feed/']),
      scrape_interval: 3600,
      active:          true,
    },
  ]

  for (const source of sources) {
    await knex('sources').insert(source).onConflict('slug').ignore()
  }
}

export async function down(knex: Knex): Promise<void> {
  const slugs = [
    // Oceania
    'the-australian', 'sydney-morning-herald', 'nz-herald', 'rnz-news',
    'rnz-pacific', 'pacnews', 'png-post-courier', 'fiji-times',
    // Caribbean
    'jamaica-gleaner', 'trinidad-express', 'barbados-nation', 'dominican-today',
    // Nordic / Baltic
    'yle-news-en', 'the-local-se', 'err-news', 'lrt-english', 'lsm-en',
    // South Asia
    'daily-star-bd', 'kathmandu-post', 'scroll-in', 'colombo-telegraph',
    // Academic / Research
    'science-magazine', 'eureka-alert', 'science-daily', 'physics-world',
    'harvard-gazette', 'quanta-magazine',
    // Middle East / Africa
    'al-ahram-en', 'morocco-world-news', 'the-citizen-tz', 'ethiopian-reporter', 'jordan-times',
    // Geopolitics / Analysis
    'open-democracy', 'war-on-the-rocks', 'cepa-news',
  ]
  await knex('sources').whereIn('slug', slugs).delete()
}
