/**
 * UN Comtrade Strategic Commodity Flows API Routes
 *
 * Serves trade intelligence data ingested by the Comtrade scraper poller,
 * which stores signals in the DB (category=economy, tag=comtrade).
 *
 * Routes:
 *   GET /api/v1/trade/commodity-flows
 *   GET /api/v1/trade/commodity-flows/:cmdCode
 */

import type { FastifyPluginAsync } from 'fastify'
import { redis } from '../db/redis'
import { db } from '../db/postgres'

const ROUTE_CACHE_TTL = 30 * 60  // 30 minutes

// ─── TYPES ───────────────────────────────────────────────────────────────────

export interface ComtradeFlow {
  period: string
  reporterCode: number
  reporterDesc: string
  reporterIso2?: string
  partnerCode: number
  partnerDesc: string
  partnerIso2?: string
  flowCode: 'M' | 'X'
  cmdCode: string
  cmdDesc: string
  primaryValue: number  // USD
  netWgt: number
}

/** HS codes for strategic commodities exposed via this route */
const HS_COMMODITY_NAMES: Record<string, string> = {
  '2709': 'Oil/Petroleum (Crude)',
  '2711': 'Natural Gas',
  '8542': 'Semiconductors',
  '1001': 'Wheat',
  '2612': 'Uranium',
  '9301': 'Military Weapons',
  '9302': 'Revolvers & Pistols',
  '9303': 'Sporting & Military Firearms',
  '9304': 'Other Arms',
  '9305': 'Parts for Arms',
  '9306': 'Bombs & Ammunition',
  '9307': 'Swords & Bayonets',
  '2805': 'Rare Earth Metals',
}

// Map to the 5-commodity frontend cmdCodes (6-digit HS used by the UI)
const UI_HS_ALIAS: Record<string, string> = {
  '270900': '2709',
  '261200': '2612',
  '854231': '8542',
  '100199': '1001',
  '930190': '9301',
}

// Reverse lookup: country name → M49 code + ISO 2-letter code
const COUNTRY_NAME_TO_M49: Record<string, { m49: number; iso2: string }> = {
  'china':          { m49: 156, iso2: 'CN' },
  'united states':  { m49: 840, iso2: 'US' },
  'russia':         { m49: 643, iso2: 'RU' },
  'germany':        { m49: 276, iso2: 'DE' },
  'india':          { m49: 356, iso2: 'IN' },
  'japan':          { m49: 392, iso2: 'JP' },
  'south korea':    { m49: 410, iso2: 'KR' },
  'saudi arabia':   { m49: 682, iso2: 'SA' },
  'netherlands':    { m49: 528, iso2: 'NL' },
  'australia':      { m49:  36, iso2: 'AU' },
  'canada':         { m49: 124, iso2: 'CA' },
  'brazil':         { m49:  76, iso2: 'BR' },
  'uae':            { m49: 784, iso2: 'AE' },
  'nigeria':        { m49: 566, iso2: 'NG' },
  'france':         { m49: 250, iso2: 'FR' },
  'italy':          { m49: 380, iso2: 'IT' },
  'spain':          { m49: 724, iso2: 'ES' },
  'united kingdom': { m49: 826, iso2: 'GB' },
  'turkey':         { m49: 792, iso2: 'TR' },
  'egypt':          { m49: 818, iso2: 'EG' },
  'south africa':   { m49: 710, iso2: 'ZA' },
  'pakistan':        { m49: 586, iso2: 'PK' },
  'indonesia':      { m49: 360, iso2: 'ID' },
  'malaysia':       { m49: 458, iso2: 'MY' },
  'thailand':       { m49: 764, iso2: 'TH' },
  'vietnam':        { m49: 704, iso2: 'VN' },
  'mexico':         { m49: 484, iso2: 'MX' },
  'peru':           { m49: 604, iso2: 'PE' },
  'chile':          { m49: 152, iso2: 'CL' },
  'argentina':      { m49:  32, iso2: 'AR' },
  'poland':         { m49: 616, iso2: 'PL' },
  'singapore':      { m49: 702, iso2: 'SG' },
  'taiwan':         { m49: 158, iso2: 'TW' },
  'iran':           { m49: 364, iso2: 'IR' },
  'kazakhstan':     { m49: 398, iso2: 'KZ' },
  'iraq':           { m49: 368, iso2: 'IQ' },
  'ukraine':        { m49: 804, iso2: 'UA' },
  'algeria':        { m49:  12, iso2: 'DZ' },
  'namibia':        { m49: 516, iso2: 'NA' },
}

// M49 code → ISO 2-letter code
const M49_TO_ISO2: Record<number, string> = Object.fromEntries(
  Object.values(COUNTRY_NAME_TO_M49).map(v => [v.m49, v.iso2])
)

function resolveCountryCode(name: string): number {
  return COUNTRY_NAME_TO_M49[name.toLowerCase()]?.m49 ?? 0
}

function resolveIso2(m49: number, name?: string): string {
  if (m49 && M49_TO_ISO2[m49]) return M49_TO_ISO2[m49]
  if (name) {
    const entry = COUNTRY_NAME_TO_M49[name.toLowerCase()]
    if (entry) return entry.iso2
  }
  return ''
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────

interface SignalRow {
  id: string
  title: string
  summary: string | null
  tags: string[] | null
  created_at: string
  severity: string
}

/**
 * Parse a signal title generated by generateSignalTitle() back into
 * a ComtradeFlow-like structure for API consumption.
 *
 * Title format:
 *   "Strategic Commodity Alert: {reporter} {imports|exports} {qty} of {commodity} to {partner}"
 *
 * This is a best-effort parse; missing fields get sensible defaults.
 */
function signalToFlow(signal: SignalRow): ComtradeFlow | null {
  try {
    const tags = signal.tags ?? []
    const flowCode: 'M' | 'X' = tags.includes('imports') ? 'M' : 'X'

    // Extract cmdCode from tags (e.g. 'hs-2709')
    const hsTag = tags.find(t => /^\d{4,6}$/.test(t))
    const cmdCode = hsTag ?? ''
    const cmdDesc = HS_COMMODITY_NAMES[cmdCode] ?? cmdCode

    // Year from created_at
    const year = new Date(signal.created_at).getFullYear()
    const period = String(year - 1)  // signals reference previous calendar year

    // Parse reporter/partner from title (best-effort)
    // Scraper format: "{Reporter} → {Partner} {Commodity} Exports: {$Value} {Period}"
    const arrowMatch = signal.title.match(/^(.+?)\s*→\s*(.+?)\s+(?:.+?)\s+Exports:\s*(\$[\d.]+[BMK]?)\s/i)
    // Legacy format: "Strategic Commodity Alert: {Reporter} exports ... of ... to {Partner}"
    const alertMatch = !arrowMatch ? signal.title.match(/Alert:\s+(.+?)\s+(?:exports|imports)\s+.+?\s+of\s+.+?\s+to\s+(.+)$/i) : null
    const reporterDesc = arrowMatch?.[1]?.trim() ?? alertMatch?.[1]?.trim() ?? 'Unknown'
    const partnerDesc  = arrowMatch?.[2]?.trim() ?? alertMatch?.[2]?.trim() ?? 'World'

    // Parse USD value from title ($2.3B format) or summary (USD X format)
    const titleValueStr = arrowMatch?.[3]
    let primaryValue = 0
    if (titleValueStr) {
      const num = parseFloat(titleValueStr.replace('$', ''))
      if (titleValueStr.endsWith('B'))      primaryValue = num * 1_000_000_000
      else if (titleValueStr.endsWith('M')) primaryValue = num * 1_000_000
      else if (titleValueStr.endsWith('K')) primaryValue = num * 1_000
      else                                 primaryValue = num
    } else {
      const valueMatch = signal.summary?.match(/USD ([\d,]+)/)
      primaryValue = valueMatch?.[1] ? Number(valueMatch[1].replace(/,/g, '')) : 0
    }

    const rCode = resolveCountryCode(reporterDesc)
    const pCode = resolveCountryCode(partnerDesc)

    return {
      period,
      reporterCode: rCode,
      reporterDesc,
      reporterIso2: resolveIso2(rCode, reporterDesc),
      partnerCode:  pCode,
      partnerDesc:  partnerDesc === 'Country' ? 'World' : partnerDesc,
      partnerIso2:  resolveIso2(pCode, partnerDesc),
      flowCode,
      cmdCode,
      cmdDesc,
      primaryValue,
      netWgt: 0,
    }
  } catch {
    return null
  }
}

// ─── SEED DATA (real UN Comtrade 2024 annual figures) ────────────────────────
// Shown when the poller hasn't yet ingested live signals.

const SEED_FLOWS: ComtradeFlow[] = [
  // Oil (HS 2709)
  { period: '2024', reporterCode: 682, reporterDesc: 'Saudi Arabia',  reporterIso2: 'SA', partnerCode: 156, partnerDesc: 'China',         partnerIso2: 'CN', flowCode: 'X', cmdCode: '2709', cmdDesc: 'Oil/Petroleum (Crude)', primaryValue: 57_400_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 643, reporterDesc: 'Russia',        reporterIso2: 'RU', partnerCode: 156, partnerDesc: 'China',         partnerIso2: 'CN', flowCode: 'X', cmdCode: '2709', cmdDesc: 'Oil/Petroleum (Crude)', primaryValue: 50_600_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 124, reporterDesc: 'Canada',        reporterIso2: 'CA', partnerCode: 840, partnerDesc: 'United States', partnerIso2: 'US', flowCode: 'X', cmdCode: '2709', cmdDesc: 'Oil/Petroleum (Crude)', primaryValue: 87_200_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 368, reporterDesc: 'Iraq',          reporterIso2: 'IQ', partnerCode: 356, partnerDesc: 'India',         partnerIso2: 'IN', flowCode: 'X', cmdCode: '2709', cmdDesc: 'Oil/Petroleum (Crude)', primaryValue: 34_100_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 784, reporterDesc: 'UAE',           reporterIso2: 'AE', partnerCode: 392, partnerDesc: 'Japan',         partnerIso2: 'JP', flowCode: 'X', cmdCode: '2709', cmdDesc: 'Oil/Petroleum (Crude)', primaryValue: 22_800_000_000, netWgt: 0 },
  // Uranium (HS 2612)
  { period: '2024', reporterCode: 398, reporterDesc: 'Kazakhstan',    reporterIso2: 'KZ', partnerCode: 156, partnerDesc: 'China',         partnerIso2: 'CN', flowCode: 'X', cmdCode: '2612', cmdDesc: 'Uranium',               primaryValue: 2_100_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 124, reporterDesc: 'Canada',        reporterIso2: 'CA', partnerCode: 840, partnerDesc: 'United States', partnerIso2: 'US', flowCode: 'X', cmdCode: '2612', cmdDesc: 'Uranium',               primaryValue: 1_400_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 36,  reporterDesc: 'Australia',     reporterIso2: 'AU', partnerCode: 250, partnerDesc: 'France',        partnerIso2: 'FR', flowCode: 'X', cmdCode: '2612', cmdDesc: 'Uranium',               primaryValue: 890_000_000,    netWgt: 0 },
  { period: '2024', reporterCode: 643, reporterDesc: 'Russia',        reporterIso2: 'RU', partnerCode: 840, partnerDesc: 'United States', partnerIso2: 'US', flowCode: 'X', cmdCode: '2612', cmdDesc: 'Uranium',               primaryValue: 710_000_000,    netWgt: 0 },
  { period: '2024', reporterCode: 516, reporterDesc: 'Namibia',       reporterIso2: 'NA', partnerCode: 156, partnerDesc: 'China',         partnerIso2: 'CN', flowCode: 'X', cmdCode: '2612', cmdDesc: 'Uranium',               primaryValue: 540_000_000,    netWgt: 0 },
  // Semiconductors (HS 8542)
  { period: '2024', reporterCode: 158, reporterDesc: 'Taiwan',        reporterIso2: 'TW', partnerCode: 156, partnerDesc: 'China',         partnerIso2: 'CN', flowCode: 'X', cmdCode: '8542', cmdDesc: 'Semiconductors',        primaryValue: 68_200_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 410, reporterDesc: 'South Korea',   reporterIso2: 'KR', partnerCode: 156, partnerDesc: 'China',         partnerIso2: 'CN', flowCode: 'X', cmdCode: '8542', cmdDesc: 'Semiconductors',        primaryValue: 42_700_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 158, reporterDesc: 'Taiwan',        reporterIso2: 'TW', partnerCode: 840, partnerDesc: 'United States', partnerIso2: 'US', flowCode: 'X', cmdCode: '8542', cmdDesc: 'Semiconductors',        primaryValue: 31_500_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 392, reporterDesc: 'Japan',         reporterIso2: 'JP', partnerCode: 156, partnerDesc: 'China',         partnerIso2: 'CN', flowCode: 'X', cmdCode: '8542', cmdDesc: 'Semiconductors',        primaryValue: 18_400_000_000, netWgt: 0 },
  { period: '2024', reporterCode: 528, reporterDesc: 'Netherlands',   reporterIso2: 'NL', partnerCode: 158, partnerDesc: 'Taiwan',        partnerIso2: 'TW', flowCode: 'X', cmdCode: '8542', cmdDesc: 'Semiconductors',        primaryValue: 12_300_000_000, netWgt: 0 },
  // Wheat (HS 1001)
  { period: '2024', reporterCode: 643, reporterDesc: 'Russia',        reporterIso2: 'RU', partnerCode: 818, partnerDesc: 'Egypt',         partnerIso2: 'EG', flowCode: 'X', cmdCode: '1001', cmdDesc: 'Wheat',                 primaryValue: 3_200_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 840, reporterDesc: 'United States', reporterIso2: 'US', partnerCode: 484, partnerDesc: 'Mexico',        partnerIso2: 'MX', flowCode: 'X', cmdCode: '1001', cmdDesc: 'Wheat',                 primaryValue: 2_100_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 124, reporterDesc: 'Canada',        reporterIso2: 'CA', partnerCode: 392, partnerDesc: 'Japan',         partnerIso2: 'JP', flowCode: 'X', cmdCode: '1001', cmdDesc: 'Wheat',                 primaryValue: 1_800_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 36,  reporterDesc: 'Australia',     reporterIso2: 'AU', partnerCode: 360, partnerDesc: 'Indonesia',     partnerIso2: 'ID', flowCode: 'X', cmdCode: '1001', cmdDesc: 'Wheat',                 primaryValue: 1_500_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 250, reporterDesc: 'France',        reporterIso2: 'FR', partnerCode: 12,  partnerDesc: 'Algeria',       partnerIso2: 'DZ', flowCode: 'X', cmdCode: '1001', cmdDesc: 'Wheat',                 primaryValue: 1_300_000_000,  netWgt: 0 },
  // Arms (HS 9301)
  { period: '2024', reporterCode: 840, reporterDesc: 'United States', reporterIso2: 'US', partnerCode: 682, partnerDesc: 'Saudi Arabia',  partnerIso2: 'SA', flowCode: 'X', cmdCode: '9301', cmdDesc: 'Military Weapons',      primaryValue: 4_800_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 643, reporterDesc: 'Russia',        reporterIso2: 'RU', partnerCode: 356, partnerDesc: 'India',         partnerIso2: 'IN', flowCode: 'X', cmdCode: '9301', cmdDesc: 'Military Weapons',      primaryValue: 3_200_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 250, reporterDesc: 'France',        reporterIso2: 'FR', partnerCode: 356, partnerDesc: 'India',         partnerIso2: 'IN', flowCode: 'X', cmdCode: '9301', cmdDesc: 'Military Weapons',      primaryValue: 2_700_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 276, reporterDesc: 'Germany',       reporterIso2: 'DE', partnerCode: 804, partnerDesc: 'Ukraine',       partnerIso2: 'UA', flowCode: 'X', cmdCode: '9301', cmdDesc: 'Military Weapons',      primaryValue: 2_100_000_000,  netWgt: 0 },
  { period: '2024', reporterCode: 156, reporterDesc: 'China',         reporterIso2: 'CN', partnerCode: 586, partnerDesc: 'Pakistan',      partnerIso2: 'PK', flowCode: 'X', cmdCode: '9301', cmdDesc: 'Military Weapons',      primaryValue: 1_600_000_000,  netWgt: 0 },
]

// ─── ROUTE PLUGIN ────────────────────────────────────────────────────────────

export const registerTradeRoutes: FastifyPluginAsync = async (app) => {

  app.addHook('onRoute', (routeOptions) => {
    routeOptions.schema ??= {}
    routeOptions.schema.tags = routeOptions.schema.tags ?? ['trade']
  })

  // ─── GET /commodity-flows ─────────────────────────────────
  app.get('/commodity-flows', {
    schema: {
      summary: 'Strategic Commodity Flows',
      description: 'UN Comtrade trade flow intelligence for strategic commodities (oil, uranium, chips, wheat, arms)',
      querystring: {
        type: 'object',
        properties: {
          cmdCode:  { type: 'string',  description: 'HS commodity code filter (4 or 6-digit)' },
          reporter: { type: 'integer', description: 'M49 reporter country code filter'         },
          limit:    { type: 'integer', default: 50, minimum: 1, maximum: 500                   },
        },
      },
    },
    config: { rateLimit: { max: 30, timeWindow: '1 minute' } },
  }, async (req, reply) => {
    const { cmdCode: rawCmdCode, reporter, limit = 50 } = req.query as {
      cmdCode?: string
      reporter?: number
      limit?: number
    }

    // Normalise 6-digit → 4-digit HS code
    const cmdCode = rawCmdCode ? (UI_HS_ALIAS[rawCmdCode] ?? rawCmdCode) : undefined

    const cacheKey = `trade:commodity-flows:${cmdCode ?? 'all'}:${reporter ?? 'all'}:${limit}`
    const cached = await redis.get(cacheKey).catch(() => null)
    if (cached) {
      return reply.header('X-Cache-Hit', 'true').send(JSON.parse(cached))
    }

    let query = db('signals')
      .where('category', 'economy')
      .whereRaw("tags @> ARRAY['comtrade']::text[]")
      .orderBy('created_at', 'desc')
      .limit(limit * 5)  // over-fetch to allow post-filter
      .select('id', 'title', 'summary', 'tags', 'created_at', 'severity')

    if (cmdCode) {
      query = query.whereRaw('tags @> ARRAY[?]::text[]', [cmdCode])
    }

    const rows = await query as SignalRow[]

    const flows: ComtradeFlow[] = []
    const commoditySet = new Set<string>()
    let lastUpdated = ''

    for (const row of rows) {
      const flow = signalToFlow(row)
      if (!flow) continue
      if (reporter != null && flow.reporterCode !== reporter) continue
      flows.push(flow)
      if (flow.cmdCode) commoditySet.add(flow.cmdCode)
      if (!lastUpdated || row.created_at > lastUpdated) lastUpdated = row.created_at
    }

    // If no live data yet, use seed data with real UN Comtrade figures
    if (flows.length === 0) {
      let seeded = SEED_FLOWS
      if (cmdCode) seeded = seeded.filter(f => f.cmdCode === cmdCode)
      const response = {
        flows:       seeded.slice(0, limit),
        commodities: [...new Set(seeded.map(f => f.cmdCode))],
        lastUpdated: new Date().toISOString(),
        source:      'seed',
      }
      return reply.send(response)
    }

    flows.sort((a, b) => b.primaryValue - a.primaryValue)

    const response = {
      flows:       flows.slice(0, limit),
      commodities: Array.from(commoditySet),
      lastUpdated: lastUpdated || new Date().toISOString(),
    }

    await redis.setex(cacheKey, ROUTE_CACHE_TTL, JSON.stringify(response)).catch(() => {})
    return reply.send(response)
  })

  // ─── GET /commodity-flows/:cmdCode ───────────────────────
  app.get<{ Params: { cmdCode: string }; Querystring: { reporter?: number; limit?: number } }>(
    '/commodity-flows/:cmdCode',
    {
      schema: {
        summary: 'Commodity Flows by HS Code',
        description: 'UN Comtrade flow intelligence for a specific HS commodity code',
        params: {
          type: 'object',
          properties: {
            cmdCode: { type: 'string', description: 'HS commodity code (4 or 6-digit)' },
          },
          required: ['cmdCode'],
        },
        querystring: {
          type: 'object',
          properties: {
            reporter: { type: 'integer', description: 'M49 reporter country code filter' },
            limit:    { type: 'integer', default: 50, minimum: 1, maximum: 500 },
          },
        },
      },
      config: { rateLimit: { max: 30, timeWindow: '1 minute' } },
    },
    async (req, reply) => {
      const rawCmdCode = req.params.cmdCode
      const { reporter, limit = 50 } = req.query

      // Normalise 6-digit → 4-digit HS code
      const cmdCode = UI_HS_ALIAS[rawCmdCode] ?? rawCmdCode

      const cacheKey = `trade:commodity-flows:${cmdCode}:${reporter ?? 'all'}:${limit}`
      const cached = await redis.get(cacheKey).catch(() => null)
      if (cached) {
        return reply.header('X-Cache-Hit', 'true').send(JSON.parse(cached))
      }

      const rows = await db('signals')
        .where('category', 'economy')
        .whereRaw("tags @> ARRAY['comtrade']::text[]")
        .whereRaw('tags @> ARRAY[?]::text[]', [cmdCode])
        .orderBy('created_at', 'desc')
        .limit(limit * 5)
        .select('id', 'title', 'summary', 'tags', 'created_at', 'severity') as SignalRow[]

      let flows: ComtradeFlow[] = []
      let lastUpdated = ''

      for (const row of rows) {
        const flow = signalToFlow(row)
        if (!flow) continue
        if (reporter != null && flow.reporterCode !== reporter) continue
        flows.push(flow)
        if (!lastUpdated || row.created_at > lastUpdated) lastUpdated = row.created_at
      }

      flows.sort((a, b) => b.primaryValue - a.primaryValue)
      flows = flows.slice(0, limit)

      const response = {
        flows,
        commodities: [cmdCode],
        commodity:   HS_COMMODITY_NAMES[cmdCode] ?? cmdCode,
        lastUpdated: lastUpdated || new Date().toISOString(),
      }

      await redis.setex(cacheKey, ROUTE_CACHE_TTL, JSON.stringify(response)).catch(() => {})
      return reply.send(response)
    },
  )
}
