/**
 * Seed data for the /sanctions/featured endpoint.
 *
 * Purpose: guarantees the /sanctions page always has content, even when
 * OpenSanctions' free-tier API hard-rate-limits us (which it does within
 * minutes on public endpoints). The seed is used as a fallback when live
 * fetches return zero entities.
 *
 * Updating this list: these are high-visibility, long-standing sanctioned
 * persons, organizations, and vessels. They rarely change. Review quarterly.
 *
 * Dataset references are OpenSanctions' canonical dataset IDs so the
 * dataset labels render correctly (see datasetLabel in lib/opensanctions.ts).
 */
import type { FeaturedEntity } from '../routes/sanctions'

export const FEATURED_SEED: FeaturedEntity[] = [
  // ─── Critical persons ──────────────────────────────────────────────────────
  {
    id: 'wp-seed-putin-vladimir',
    caption: 'Vladimir Vladimirovich Putin',
    schema: 'Person',
    schemaLabel: 'Person',
    datasets: ['us_ofac_sdn', 'eu_fsf', 'gb_hmt_sanctions'],
    datasetLabels: ['US OFAC SDN List', 'EU Consolidated Financial Sanctions', 'UK HMT Sanctions List'],
    threatLevel: 'critical',
    primaryAlias: 'Putin, Vladimir',
    aliases: ['Putin, Vladimir', 'V. Putin', 'Путин Владимир Владимирович'],
    countries: ['ru'],
    topics: ['role.pep', 'sanction'],
    score: 0.99,
  },
  {
    id: 'wp-seed-kim-jong-un',
    caption: 'Kim Jong Un',
    schema: 'Person',
    schemaLabel: 'Person',
    datasets: ['us_ofac_sdn', 'un_sc_sanctions', 'eu_fsf'],
    datasetLabels: ['US OFAC SDN List', 'UN Security Council Sanctions', 'EU Consolidated Financial Sanctions'],
    threatLevel: 'critical',
    primaryAlias: 'Kim Jong-un',
    aliases: ['Kim Jong-un', 'Kim Jong Eun', '김정은'],
    countries: ['kp'],
    topics: ['role.pep', 'sanction'],
    score: 0.98,
  },
  {
    id: 'wp-seed-lukashenko-alexander',
    caption: 'Alexander Grigoryevich Lukashenko',
    schema: 'Person',
    schemaLabel: 'Person',
    datasets: ['us_ofac_sdn', 'eu_fsf', 'gb_hmt_sanctions'],
    datasetLabels: ['US OFAC SDN List', 'EU Consolidated Financial Sanctions', 'UK HMT Sanctions List'],
    threatLevel: 'critical',
    primaryAlias: 'Lukashenko, Alexander',
    aliases: ['Lukashenko, Alexander', 'Лукашенко Александр'],
    countries: ['by'],
    topics: ['role.pep', 'sanction'],
    score: 0.95,
  },
  {
    id: 'wp-seed-assad-bashar',
    caption: 'Bashar Hafez al-Assad',
    schema: 'Person',
    schemaLabel: 'Person',
    datasets: ['us_ofac_sdn', 'eu_fsf', 'gb_hmt_sanctions'],
    datasetLabels: ['US OFAC SDN List', 'EU Consolidated Financial Sanctions', 'UK HMT Sanctions List'],
    threatLevel: 'critical',
    primaryAlias: 'al-Assad, Bashar',
    aliases: ['al-Assad, Bashar', 'Bashar Assad', 'بشار الأسد'],
    countries: ['sy'],
    topics: ['role.pep', 'sanction', 'crime.war'],
    score: 0.96,
  },
  {
    id: 'wp-seed-kadyrov-ramzan',
    caption: 'Ramzan Akhmadovich Kadyrov',
    schema: 'Person',
    schemaLabel: 'Person',
    datasets: ['us_ofac_sdn', 'eu_fsf', 'gb_hmt_sanctions'],
    datasetLabels: ['US OFAC SDN List', 'EU Consolidated Financial Sanctions', 'UK HMT Sanctions List'],
    threatLevel: 'high',
    primaryAlias: 'Kadyrov, Ramzan',
    aliases: ['Kadyrov, Ramzan', 'Кадыров Рамзан'],
    countries: ['ru'],
    topics: ['role.pep', 'sanction'],
    score: 0.92,
  },
  {
    id: 'wp-seed-khamenei-ali',
    caption: 'Ali Hosseini Khamenei',
    schema: 'Person',
    schemaLabel: 'Person',
    datasets: ['us_ofac_sdn', 'gb_hmt_sanctions', 'ca_sema_sanctions'],
    datasetLabels: ['US OFAC SDN List', 'UK HMT Sanctions List', 'Canada SEMA Sanctions'],
    threatLevel: 'critical',
    primaryAlias: 'Khamenei, Ali',
    aliases: ['Khamenei, Ali', 'Sayyid Ali Khamenei', 'علی خامنه‌ای'],
    countries: ['ir'],
    topics: ['role.pep', 'sanction'],
    score: 0.97,
  },

  // ─── Organizations ─────────────────────────────────────────────────────────
  {
    id: 'wp-seed-irgc',
    caption: 'Islamic Revolutionary Guard Corps',
    schema: 'Organization',
    schemaLabel: 'Organization',
    datasets: ['us_ofac_sdn', 'us_sdn_terror', 'eu_fsf'],
    datasetLabels: ['US OFAC SDN List', 'US OFAC Terror List', 'EU Consolidated Financial Sanctions'],
    threatLevel: 'critical',
    primaryAlias: 'IRGC',
    aliases: ['IRGC', 'Pasdaran', 'سپاه پاسداران انقلاب اسلامی'],
    countries: ['ir'],
    topics: ['sanction', 'crime.terror'],
    score: 0.98,
  },
  {
    id: 'wp-seed-wagner-group',
    caption: 'Wagner Group',
    schema: 'Organization',
    schemaLabel: 'Organization',
    datasets: ['us_ofac_sdn', 'eu_fsf', 'gb_hmt_sanctions'],
    datasetLabels: ['US OFAC SDN List', 'EU Consolidated Financial Sanctions', 'UK HMT Sanctions List'],
    threatLevel: 'critical',
    primaryAlias: 'Wagner Group',
    aliases: ['Wagner Group', 'PMC Wagner', 'Группа Вагнера'],
    countries: ['ru'],
    topics: ['sanction', 'crime.war'],
    score: 0.96,
  },
  {
    id: 'wp-seed-hezbollah',
    caption: 'Hezbollah',
    schema: 'Organization',
    schemaLabel: 'Organization',
    datasets: ['us_ofac_sdn', 'us_sdn_terror', 'gb_hmt_sanctions'],
    datasetLabels: ['US OFAC SDN List', 'US OFAC Terror List', 'UK HMT Sanctions List'],
    threatLevel: 'critical',
    primaryAlias: 'Hezbollah',
    aliases: ['Hezbollah', 'Hizballah', 'حزب الله'],
    countries: ['lb'],
    topics: ['sanction', 'crime.terror'],
    score: 0.95,
  },
  {
    id: 'wp-seed-hamas',
    caption: 'Hamas',
    schema: 'Organization',
    schemaLabel: 'Organization',
    datasets: ['us_ofac_sdn', 'us_sdn_terror', 'eu_fsf'],
    datasetLabels: ['US OFAC SDN List', 'US OFAC Terror List', 'EU Consolidated Financial Sanctions'],
    threatLevel: 'critical',
    primaryAlias: 'Hamas',
    aliases: ['Hamas', 'Harakat al-Muqawama al-Islamiyya', 'حركة المقاومة الإسلامية'],
    countries: ['ps'],
    topics: ['sanction', 'crime.terror'],
    score: 0.95,
  },
  {
    id: 'wp-seed-islamic-state',
    caption: 'Islamic State of Iraq and the Levant',
    schema: 'Organization',
    schemaLabel: 'Organization',
    datasets: ['us_sdn_terror', 'un_sc_sanctions', 'eu_fsf'],
    datasetLabels: ['US OFAC Terror List', 'UN Security Council Sanctions', 'EU Consolidated Financial Sanctions'],
    threatLevel: 'critical',
    primaryAlias: 'ISIL',
    aliases: ['ISIL', 'ISIS', 'Daesh', 'الدولة الإسلامية'],
    countries: ['iq', 'sy'],
    topics: ['sanction', 'crime.terror'],
    score: 0.97,
  },
  {
    id: 'wp-seed-al-qaida',
    caption: 'Al-Qaida',
    schema: 'Organization',
    schemaLabel: 'Organization',
    datasets: ['us_sdn_terror', 'un_sc_sanctions', 'gb_hmt_sanctions'],
    datasetLabels: ['US OFAC Terror List', 'UN Security Council Sanctions', 'UK HMT Sanctions List'],
    threatLevel: 'critical',
    primaryAlias: 'Al-Qaida',
    aliases: ['Al-Qaida', 'Al-Qaeda', 'القاعدة'],
    countries: ['af', 'pk'],
    topics: ['sanction', 'crime.terror'],
    score: 0.96,
  },

  // ─── Vessels (shadow fleet) ────────────────────────────────────────────────
  {
    id: 'wp-seed-vessel-ns-captain',
    caption: 'NS CAPTAIN',
    schema: 'Vessel',
    schemaLabel: 'Vessel',
    datasets: ['us_ofac_sdn'],
    datasetLabels: ['US OFAC SDN List'],
    threatLevel: 'high',
    primaryAlias: 'NS CAPTAIN',
    aliases: ['NS CAPTAIN'],
    countries: ['ru'],
    topics: ['sanction'],
    score: 0.82,
  },
  {
    id: 'wp-seed-vessel-sun-symbol',
    caption: 'SUN SYMBOL',
    schema: 'Vessel',
    schemaLabel: 'Vessel',
    datasets: ['us_ofac_sdn'],
    datasetLabels: ['US OFAC SDN List'],
    threatLevel: 'high',
    primaryAlias: 'SUN SYMBOL',
    aliases: ['SUN SYMBOL'],
    countries: ['ir'],
    topics: ['sanction'],
    score: 0.8,
  },
]
